export const GOOGLE_BUSINESS_CATEGORIES = [
  "Academia",
  "Açougue",
  "Advogado",
  "Agência de empregos",
  "Agência de marketing",
  "Agência de publicidade",
  "Agência de seguros",
  "Agência de viagens",
  "Agricultor",
  "Agropecuária",
  "Alfaiate",
  "Alojamento",
  "Armazém",
  "Arquiteto",
  "Associação",
  "Assistência técnica de celulares",
  "Assistência técnica de computadores",
  "Autoelétrica",
  "Bar",
  "Barbearia",
  "Bicicletaria",
  "Bistrô",
  "Borracharia",
  "Boutique",
  "Buffet",
  "Cafeteria",
  "Cartório",
  "Casa de carnes",
  "Casa de festas",
  "Centro automotivo",
  "Centro de diagnóstico",
  "Centro de educação infantil",
  "Centro de estética",
  "Centro de formação de condutores",
  "Centro médico",
  "Chácara",
  "Chaveiro",
  "Clínica de fisioterapia",
  "Clínica de psicologia",
  "Clínica de saúde",
  "Clínica odontológica",
  "Clube",
  "Comércio de animais",
  "Concessionária de automóveis",
  "Confeitaria",
  "Construtora",
  "Consultor",
  "Consultoria empresarial",
  "Contador",
  "Corretor de imóveis",
  "Creche",
  "Curso profissionalizante",
  "Dedetizadora",
  "Depósito de bebidas",
  "Designer gráfico",
  "Distribuidora",
  "Eletricista",
  "Empresa de limpeza",
  "Empresa de segurança",
  "Empresa de software",
  "Empresa de transporte",
  "Escola",
  "Escola de idiomas",
  "Escritório de advocacia",
  "Escritório de contabilidade",
  "Estacionamento",
  "Farmácia",
  "Fazenda",
  "Floricultura",
  "Fotógrafo",
  "Frigorífico",
  "Funerária",
  "Gráfica",
  "Guincho",
  "Hamburgueria",
  "Hotel",
  "Imobiliária",
  "Instalador de ar-condicionado",
  "Instituição de ensino",
  "Laboratório de análises clínicas",
  "Lanchonete",
  "Lavanderia",
  "Lava-jato",
  "Loja de acessórios para celulares",
  "Loja de alimentos naturais",
  "Loja de animais",
  "Loja de artigos esportivos",
  "Loja de autopeças",
  "Loja de bicicletas",
  "Loja de calçados",
  "Loja de celulares",
  "Loja de cosméticos",
  "Loja de eletrônicos",
  "Loja de ferramentas",
  "Loja de informática",
  "Loja de materiais de construção",
  "Loja de móveis",
  "Loja de roupas",
  "Loja de variedades",
  "Manutenção de computadores",
  "Manutenção elétrica",
  "Marceneiro",
  "Mecânico",
  "Mercado",
  "Mercearia",
  "Motel",
  "Nutricionista",
  "Oficina de bicicletas",
  "Oficina mecânica",
  "Ótica",
  "Padaria",
  "Papelaria",
  "Pet shop",
  "Pizzaria",
  "Posto de combustível",
  "Produtor rural",
  "Psicólogo",
  "Rancho",
  "Restaurante",
  "Salão de beleza",
  "Serralheiro",
  "Serviço de instalação elétrica",
  "Serviço de manutenção",
  "Serviço de pintura",
  "Serviço de saúde ocupacional",
  "Serviço de transporte",
  "Sorveteria",
  "Supermercado",
  "Transportadora",
  "Veterinário",
  "Vidraçaria"
] as const;
