import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { canManageDroneGestor } from "@/lib/dronegestor-role";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";

const BUCKET="dronegestor-documentos";
const ACTION="documento_piloto_v1";
const PILOT_ACTION="piloto_operacional_v1";
const MAX_BYTES=10*1024*1024;
const TYPES=new Set(["exame_teorico_anac","treinamento_operacional","outro"]);

type Context={userId:string;empresaId:string|null;canManage:boolean;userName:string};
function normalize(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function text(v:unknown,max=240){return typeof v==="string"?v.trim().slice(0,max):""}
function safe(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"sem-id"}
function scope(q:any,c:Context){return c.empresaId?q.eq("empresa_id",c.empresaId):q.eq("usuario_id",c.userId)}
async function context():Promise<{current:Context|null;response:NextResponse|null}>{const s=await getSessionProfile();if(!s.user||!s.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const t=normalize(s.profile.tipo||""),master=["super_admin","admin_master"].includes(t),allowed=(s.appsLiberados??[]).some(a=>a.slug==="dronegestor"&&a.canAccess);if(!master&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{userId:s.profile.id,empresaId:s.profile.empresa_id,userName:s.profile.nome||"Usuário",canManage:canManageDroneGestor({tipo:s.profile.tipo,isAdminMaster:master,permissoes:s.permissoes})},response:null}}
function detect(bytes:Buffer){if(bytes.length>=5&&bytes.subarray(0,5).toString("ascii")==="%PDF-")return{ext:"pdf",mime:"application/pdf"};if(bytes.length>=4&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return{ext:"jpg",mime:"image/jpeg"};if(bytes.length>=8&&bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return{ext:"png",mime:"image/png"};if(bytes.length>=12&&bytes.subarray(0,4).toString("ascii")==="RIFF"&&bytes.subarray(8,12).toString("ascii")==="WEBP")return{ext:"webp",mime:"image/webp"};return null}
async function findPilot(admin:any,c:Context,pilotId:string){let q=admin.from("core_logs").select("id,detalhes").eq("app_slug","dronegestor").eq("acao",PILOT_ACTION).contains("detalhes",{id:pilotId}).limit(1);q=scope(q,c);const{data,error}=await q.maybeSingle();if(error)throw error;return data}
async function authorizePilot(admin:any,c:Context,pilotId:string){const row=await findPilot(admin,c,pilotId);if(!row||row.detalhes?.ativo===false)return false;if(c.canManage)return true;return text(row.detalhes?.usuarioId,120)===c.userId}
async function signed(admin:any,row:any){const d=row?.detalhes??{},path=text(d.storagePath,600);if(!path)return null;const url=await admin.storage.from(BUCKET).createSignedUrl(path,15*60);return{id:String(row.id),pilotId:text(d.pilotId,120),tipo:text(d.tipo,60),nome:text(d.nome,240),numero:text(d.numero,120),validade:text(d.validade,40),uploadedAt:text(d.uploadedAt,60)||row.created_at,uploadedBy:text(d.uploadedBy,180),url:url.data?.signedUrl||""}}

export async function GET(request:NextRequest){try{const a=await context();if(a.response)return a.response;const c=a.current!,pilotId=text(request.nextUrl.searchParams.get("pilotId"),120);if(!pilotId)return NextResponse.json({ok:false,error:"Selecione um piloto."},{status:400});const admin=createSupabaseAdminClient() as any;if(!(await authorizePilot(admin,c,pilotId)))return NextResponse.json({ok:false,error:"Piloto não encontrado ou sem acesso."},{status:404});let q=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTION).order("created_at",{ascending:false}).limit(100);q=scope(q,c);const{data,error}=await q;if(error)throw error;const rows=(data??[]).filter((r:any)=>text(r?.detalhes?.pilotId,120)===pilotId);const items=(await Promise.all(rows.map((r:any)=>signed(admin,r)))).filter(Boolean);return NextResponse.json({ok:true,items,canManage:c.canManage})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao carregar documentos do piloto."},{status:500})}}

export async function POST(request:NextRequest){try{const a=await context();if(a.response)return a.response;const c=a.current!;if(!c.canManage)return NextResponse.json({ok:false,error:"Somente Gestor/RT pode incluir documentos de qualificação."},{status:403});const form=await request.formData(),pilotId=text(form.get("pilotId"),120),tipo=text(form.get("tipo"),60),file=form.get("arquivo");if(!pilotId)return NextResponse.json({ok:false,error:"Selecione um piloto."},{status:400});if(!TYPES.has(tipo))return NextResponse.json({ok:false,error:"Tipo de documento inválido."},{status:400});if(!(file instanceof File)||file.size<=0)return NextResponse.json({ok:false,error:"Escolha o arquivo."},{status:400});if(file.size>MAX_BYTES)return NextResponse.json({ok:false,error:"Arquivo maior que 10 MB."},{status:400});const admin=createSupabaseAdminClient() as any;if(!(await authorizePilot(admin,c,pilotId)))return NextResponse.json({ok:false,error:"Piloto não encontrado."},{status:404});const bytes=Buffer.from(await file.arrayBuffer()),detected=detect(bytes);if(!detected)return NextResponse.json({ok:false,error:"Envie PDF, JPG, PNG ou WebP."},{status:400});const id=crypto.randomUUID(),owner=c.empresaId?`empresa-${safe(c.empresaId)}`:`usuario-${safe(c.userId)}`,storagePath=`${owner}/pilotos/${safe(pilotId)}/${tipo}/${Date.now()}-${id}.${detected.ext}`;const upload=await admin.storage.from(BUCKET).upload(storagePath,bytes,{contentType:detected.mime,upsert:false,cacheControl:"3600"});if(upload.error)throw upload.error;const details={documentId:id,pilotId,tipo,nome:text(file.name,240),numero:text(form.get("numero"),120),validade:text(form.get("validade"),40),storagePath,uploadedAt:new Date().toISOString(),uploadedBy:c.userName,contentType:detected.mime,bytes:bytes.length};const inserted=await admin.from("core_logs").insert({empresa_id:c.empresaId,usuario_id:c.userId,app_slug:"dronegestor",acao:ACTION,detalhes:details}).select("id,detalhes,created_at").single();if(inserted.error){await admin.storage.from(BUCKET).remove([storagePath]);throw inserted.error}return NextResponse.json({ok:true,item:await signed(admin,inserted.data)})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao salvar documento do piloto."},{status:500})}}
