import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";

const STATE_ACTION = "estado_campo_v2";
const FINALIZED_ACTION = "operacao_finalizada";
const CONFIG_ACTION = "configuracao_empresa_v1";
const OS_ACTION = "ordem_servico";
const OS_EVENT_ACTION = "ordem_servico_evento";
const MAX_STATE_BYTES = 180_000;

type StoredState = Record<string, unknown>;
type ApiContext = { usuario:{ id:string; tipo:string; nome?:string|null }; empresaId:string|null };
type Settings = { insightsObrigatorios:boolean; margemPreventiva:number; bloquearMargemPreventiva:boolean; exigirConfirmacao:boolean; protocoloBordaduraCigarrinha:boolean };

const defaultSettings:Settings = { insightsObrigatorios:true, margemPreventiva:90, bloquearMargemPreventiva:true, exigirConfirmacao:true, protocoloBordaduraCigarrinha:false };
function normalizeType(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function objectValue(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>: {}}
function numberValue(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
function textValue(value:unknown){return typeof value==="string"?value.trim():""}
function booleanRecordComplete(value:unknown){const record=objectValue(value);const values=Object.values(record);return values.length>0&&values.every(item=>item===true)}
function validateState(value:unknown):StoredState{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Estado da operação inválido.");const serialized=JSON.stringify(value);if(Buffer.byteLength(serialized,"utf8")>MAX_STATE_BYTES)throw new Error("Estado da operação excedeu o limite de sincronização.");return value as StoredState}
function storedRevision(row:any){if(!row)return 0;const parsed=Number(row?.detalhes?.revision);return Number.isFinite(parsed)&&parsed>0?Math.trunc(parsed):1}

async function getContext():Promise<{current:ApiContext|null;response:NextResponse|null}>{const context=await getSessionProfile();if(!context.user||!context.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const admin=["super_admin","admin_master"].includes(context.profile.tipo);const allowed=(context.appsLiberados??[]).some(app=>app.slug==="dronegestor"&&app.canAccess);if(!admin&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{usuario:{id:context.profile.id,tipo:context.profile.tipo,nome:context.profile.nome},empresaId:context.profile.empresa_id},response:null}}
function scopeQuery(query:any,current:ApiContext){return current.empresaId?query.eq("empresa_id",current.empresaId):query.eq("usuario_id",current.usuario.id)}
function companyHistoryRole(current:ApiContext){return ["admin_empresa","responsavel_tecnico","rt","super_admin","admin_master"].includes(normalizeType(current.usuario.tipo))}

async function loadSettings(admin:any,current:ApiContext):Promise<Settings>{let query=admin.from("core_logs").select("detalhes,created_at").eq("app_slug","dronegestor").eq("acao",CONFIG_ACTION).order("created_at",{ascending:false}).limit(1);query=scopeQuery(query,current);const {data,error}=await query.maybeSingle();if(error)throw error;const raw=data?.detalhes?.settings??{};const margin=Number(raw.margemPreventiva);return{insightsObrigatorios:raw.insightsObrigatorios!==false,margemPreventiva:Number.isFinite(margin)?Math.max(0,Math.min(5000,margin)):defaultSettings.margemPreventiva,bloquearMargemPreventiva:raw.bloquearMargemPreventiva!==false,exigirConfirmacao:raw.exigirConfirmacao!==false,protocoloBordaduraCigarrinha:raw.protocoloBordaduraCigarrinha===true}}

function buildOperationSummary(state:StoredState,pilotName:string){const mission=objectValue(state.mission),weather=objectValue(state.weather);const products=Array.isArray(mission.produtos)?mission.produtos:[];const occurrences=Array.isArray(state.occurrences)?state.occurrences:[];const areaHa=numberValue(mission.area),volumeLHa=numberValue(mission.volume),progressHa=Math.max(0,numberValue(state.progressHa));return{
  piloto:pilotName,ordemServicoId:textValue(mission.ordemServicoId),ordemServicoNumero:textValue(mission.ordemServicoNumero),clienteId:textValue(mission.clienteId),clienteNome:textValue(mission.clienteNome),fazendaId:textValue(mission.fazendaId),fazendaNome:textValue(mission.fazendaNome),municipio:textValue(mission.municipio),uf:textValue(mission.uf),talhaoId:textValue(mission.talhaoId),talhaoNome:textValue(mission.talhaoNome),
  cultura:textValue(mission.cultura),alvo:textValue(mission.alvo),tipoAtividade:textValue(mission.tipoAtividade),areaHa,areaConcluidaHa:Math.min(areaHa,progressHa),progressSource:textValue(state.progressSource)||"manual_campo",drone:textValue(mission.drone),identificacaoAnac:textValue(mission.identificacaoAnac),pontaPulverizacao:textValue(mission.pontaPulverizacao),documentoTecnicoReferencia:textValue(mission.documentoTecnicoReferencia),volumeLHa,totalCaldaL:areaHa*volumeLHa,faixaM:numberValue(mission.faixa),velocidadeKmh:numberValue(mission.velocidadeKmh),alturaM:numberValue(mission.alturaM),
  sarpasNumero:textValue(mission.sarpasNumero),sarpasSituacao:textValue(mission.sarpasSituacao),sarpasConfirmado:mission.sarpasConfirmado===true,climaCampoConfirmado:mission.climaCampoConfirmado===true,ventoCampoMedido:mission.ventoCampoMedido===true,semAreaSensivel:mission.semAreaSensivel===true,distanciaSensivelM:numberValue(mission.distanciaSensivel),
  climaCampo:{ventoKmh:numberValue(mission.ventoCampoKmh),direcaoVento:textValue(mission.direcaoVentoCampo),temperaturaC:numberValue(mission.temperaturaCampo),umidadePct:numberValue(mission.umidadeCampo),medidoEm:textValue(mission.climaCampoMedidoEm)},
  gps:{latitude:numberValue(weather.latitude),longitude:numberValue(weather.longitude),capturadoEm:textValue(weather.capturedAt)},produtos:products.map(item=>{const p=objectValue(item);return{nome:textValue(p.nome),dose:numberValue(p.dose),unidade:textValue(p.unidade)}}),calibracaoConcluida:booleanRecordComplete(state.calibration),checklistConcluido:booleanRecordComplete(state.checklist),insightAceito:state.insightAccepted===true,riscoAceito:state.riskAccepted===true,ocorrencias:occurrences,totalOcorrencias:occurrences.length,iniciadaEm:textValue(state.startedAt),finalizadaEm:textValue(state.finalizedAt)||textValue(state.concluidaNoDispositivoEm)
}}

function validateFinalization(summary:ReturnType<typeof buildOperationSummary>,state:StoredState,settings:Settings){if(summary.areaHa<=0)throw new Error("Área planejada inválida.");if(summary.areaConcluidaHa<summary.areaHa-0.01)throw new Error(`A operação não pode ser concluída: ${summary.areaConcluidaHa.toFixed(2)} ha registrados de ${summary.areaHa.toFixed(2)} ha planejados.`);if(!summary.cultura||!summary.alvo||!summary.tipoAtividade||!summary.drone||!summary.identificacaoAnac||!summary.pontaPulverizacao||!summary.documentoTecnicoReferencia)throw new Error("Cultura, alvo, atividade, drone, identificação ANAC, ponta/atomizador e referência técnica são obrigatórios.");if(summary.volumeLHa<=0||summary.faixaM<=0||summary.velocidadeKmh<=0||summary.alturaM<=0)throw new Error("Volume, faixa, velocidade e altura precisam ser válidos.");if(!summary.produtos.length||!summary.produtos.every(product=>product.nome&&product.dose>0&&product.unidade))throw new Error("Todos os produtos adicionados precisam ter nome, dose e unidade válidos.");if(!summary.ventoCampoMedido||!summary.climaCampoConfirmado||!summary.climaCampo.direcaoVento)throw new Error("A medição climática de campo precisa estar confirmada.");if(summary.climaCampo.ventoKmh<0||summary.climaCampo.ventoKmh>100||summary.climaCampo.temperaturaC< -20||summary.climaCampo.temperaturaC>60||summary.climaCampo.umidadePct<=0||summary.climaCampo.umidadePct>100)throw new Error("Há valor climático de campo ausente ou fora da faixa plausível.");if(!summary.semAreaSensivel&&summary.distanciaSensivelM<=0)throw new Error("Informe a distância da área sensível ou confirme que não há área sensível aplicável.");if(settings.bloquearMargemPreventiva&&!summary.semAreaSensivel&&summary.distanciaSensivelM<settings.margemPreventiva)throw new Error(`A distância informada está abaixo da margem preventiva interna de ${settings.margemPreventiva} m.`);if(settings.insightsObrigatorios&&!summary.insightAceito)throw new Error("O insight obrigatório da empresa não foi confirmado.");if(settings.exigirConfirmacao&&!summary.riscoAceito)throw new Error("A análise de risco obrigatória não foi confirmada.");if(!summary.calibracaoConcluida)throw new Error("Calibração incompleta.");if(!summary.checklistConcluido)throw new Error("Checklist pré-voo incompleto.");if(!summary.sarpasConfirmado||!summary.sarpasSituacao)throw new Error("A situação SARPAS precisa estar conferida.");if(summary.sarpasSituacao==="autorizado"&&!summary.sarpasNumero)throw new Error("Informe a referência SARPAS da operação autorizada.");if(!summary.iniciadaEm||!summary.finalizadaEm)throw new Error("Horários reais de início e término precisam estar registrados.");const ini=Date.parse(summary.iniciadaEm),fim=Date.parse(summary.finalizadaEm);if(!Number.isFinite(ini)||!Number.isFinite(fim)||fim<ini)throw new Error("Horários de início/término inválidos.");if(state.concluida!==true)throw new Error("A operação não foi marcada como concluída no dispositivo.")}

async function findOs(admin:any,current:ApiContext,osId:string){let query=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",OS_ACTION).contains("detalhes",{entityId:osId}).limit(1);query=scopeQuery(query,current);const {data,error}=await query.maybeSingle();if(error)throw error;return data&&data.detalhes?.ativo!==false?data:null}
async function ensureOsBelongsToPilot(admin:any,current:ApiContext,osId:string){if(!osId)return null;const os=await findOs(admin,current,osId);if(!os)throw new Error("A ordem de serviço vinculada não existe ou está inativa.");const data=os.detalhes?.data??{};const assigned=textValue(data.pilotoResponsavelId);if(assigned&&assigned!==current.usuario.id)throw new Error("Esta OS está atribuída a outro piloto.");if(["concluida","cancelada"].includes(textValue(data.status)))throw new Error("Esta OS já está concluída ou cancelada.");return os}
async function concludeOs(admin:any,current:ApiContext,osId:string){if(!osId)return;const os=await findOs(admin,current,osId);if(!os)throw new Error("Operação salva, mas a OS vinculada não foi encontrada para conclusão.");const details=os.detalhes??{},data=details.data??{};const assigned=textValue(data.pilotoResponsavelId);if(assigned&&assigned!==current.usuario.id)throw new Error("Operação salva, mas a OS está atribuída a outro piloto.");if(data.status==="concluida")return;const now=new Date().toISOString();const nextData={...data,status:"concluida",pilotoResponsavelId:assigned||current.usuario.id,pilotoResponsavelNome:data.pilotoResponsavelNome||current.usuario.nome||"Piloto",finalizadaEm:now};const nextDetails={...details,updatedAt:now,data:nextData};const {error}=await admin.from("core_logs").update({detalhes:nextDetails}).eq("id",os.id);if(error)throw error;await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuario.id,app_slug:"dronegestor",acao:OS_EVENT_ACTION,detalhes:{osId,evento:"concluida",at:now,pilotoId:current.usuario.id,pilotoNome:current.usuario.nome||"Piloto"}})}

export async function GET(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!,admin=createSupabaseAdminClient() as any;const history=request.nextUrl.searchParams.get("history")==="1";if(history){const requestedLimit=Number(request.nextUrl.searchParams.get("limit")||200),limit=Math.max(1,Math.min(500,Number.isFinite(requestedLimit)?requestedLimit:200));const requestedOffset=Number(request.nextUrl.searchParams.get("offset")||0),offset=Math.max(0,Number.isFinite(requestedOffset)?requestedOffset:0);let query=admin.from("core_logs").select("id,usuario_id,empresa_id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",FINALIZED_ACTION).order("created_at",{ascending:false}).range(offset,offset+limit);if(companyHistoryRole(current)&&current.empresaId)query=query.eq("empresa_id",current.empresaId);else query=query.eq("usuario_id",current.usuario.id);const {data,error}=await query;if(error)throw error;const items=data??[];return NextResponse.json({ok:true,items:items.slice(0,limit),hasMore:items.length>limit,nextOffset:items.length>limit?offset+limit:null})}
  const {data,error}=await admin.from("core_logs").select("id,detalhes,created_at").eq("usuario_id",current.usuario.id).eq("app_slug","dronegestor").eq("acao",STATE_ACTION).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;const details=data?.detalhes&&typeof data.detalhes==="object"?data.detalhes:null;return NextResponse.json({ok:true,state:details&&"state" in details?(details as any).state:null,revision:storedRevision(data),updatedAt:(details as any)?.updatedAt??data?.created_at??null})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao carregar os dados do DroneGestor."},{status:500})}}

export async function PUT(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!,body=await request.json(),state=validateState(body?.state),baseRevision=Math.max(0,Number(body?.baseRevision)||0),admin=createSupabaseAdminClient() as any;const {data:existing,error:findError}=await admin.from("core_logs").select("id,detalhes,created_at").eq("usuario_id",current.usuario.id).eq("app_slug","dronegestor").eq("acao",STATE_ACTION).order("created_at",{ascending:false}).limit(1).maybeSingle();if(findError)throw findError;const serverRevision=storedRevision(existing);if(serverRevision!==baseRevision){return NextResponse.json({ok:false,conflict:true,error:"Existe uma versão mais nova no servidor.",state:existing?.detalhes?.state??null,revision:serverRevision,updatedAt:existing?.detalhes?.updatedAt??existing?.created_at??null},{status:409})}const revision=serverRevision+1,updatedAt=new Date().toISOString(),detalhes={state,revision,updatedAt,version:4};if(existing?.id){const {error}=await admin.from("core_logs").update({detalhes}).eq("id",existing.id);if(error)throw error}else{const {error}=await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuario.id,app_slug:"dronegestor",acao:STATE_ACTION,detalhes});if(error)throw error}return NextResponse.json({ok:true,revision,updatedAt})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao salvar os dados do DroneGestor."},{status:500})}}

export async function POST(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!,body=await request.json(),state=validateState(body?.state),operationId=textValue(body?.operationId)||textValue(state.operationId),pilotName=current.usuario.nome||"Piloto",admin=createSupabaseAdminClient() as any,finalizedAt=new Date().toISOString();const settings=await loadSettings(admin,current),summary=buildOperationSummary(state,pilotName);validateFinalization(summary,state,settings);if(summary.ordemServicoId)await ensureOsBelongsToPilot(admin,current,summary.ordemServicoId);
  if(operationId){const {data:existing,error:existingError}=await admin.from("core_logs").select("id,detalhes,created_at").eq("usuario_id",current.usuario.id).eq("app_slug","dronegestor").eq("acao",FINALIZED_ACTION).contains("detalhes",{operationId}).limit(1).maybeSingle();if(existingError)throw existingError;if(existing){await concludeOs(admin,current,summary.ordemServicoId);return NextResponse.json({ok:true,duplicate:true,id:existing.id,finalizedAt:(existing.detalhes as any)?.finalizedAt??existing.created_at})}}
  const detalhes={operationId:operationId||crypto.randomUUID(),finalizedAt,version:6,summary,state};const {data,error}=await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuario.id,app_slug:"dronegestor",acao:FINALIZED_ACTION,detalhes}).select("id").single();if(error)throw error;await concludeOs(admin,current,summary.ordemServicoId);return NextResponse.json({ok:true,id:data.id,operationId:detalhes.operationId,finalizedAt})}catch(error){const message=error instanceof Error?error.message:"Falha ao finalizar a operação no Supabase.";const status=/não pode|obrigat|incomplet|precisa|Informe|abaixo|atribuída|concluída|cancelada|inválid|fora da faixa/i.test(message)?400:500;return NextResponse.json({ok:false,error:message},{status})}}
