import type {
  AuditLog,
  Distributor,
  Laboratory,
  MonthlySubscription,
  Pharmacy,
  Product,
  Quotation,
  QuotationItem,
  SubscriptionPlan,
  Supplier,
  SupplierQuoteResponse,
  SupplierQuoteResponseItem,
  SupplierQuoteSession,
  Tenant,
} from "./types";

export const tenants: Tenant[] = [
  {
    id: "tenant-pharmacy",
    nomeFantasia: "Farmácia Exemplo",
    razaoSocial: "Farmácia Exemplo Ltda",
    cnpj: "12.345.678/0001-90",
    tipoCliente: "pharmacy",
    responsavelNome: "Marina Costa",
    responsavelEmail: "marina@farmaciaexemplo.com.br",
    responsavelWhatsapp: "(62) 99999-0001",
    planoId: "plan-pro",
    status: "ativo",
    dataInicio: "2026-01-05",
    dataVencimento: "2026-06-05",
    valorMensal: 349,
  },
  {
    id: "tenant-bidding",
    nomeFantasia: "Distribuidora Licitação Exemplo",
    razaoSocial: "Distribuidora Licitação Exemplo S.A.",
    cnpj: "98.765.432/0001-10",
    tipoCliente: "distributor_bidding",
    responsavelNome: "Renato Lima",
    responsavelEmail: "compras@licitacaoexemplo.com.br",
    responsavelWhatsapp: "(61) 98888-0101",
    planoId: "plan-enterprise",
    status: "teste",
    dataInicio: "2026-05-01",
    dataVencimento: "2026-06-01",
    valorMensal: 899,
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "plan-start",
    name: "Start",
    monthlyPrice: 199,
    maxUsers: 3,
    maxQuotationsMonth: 30,
    maxPharmacies: 1,
    modules: "pharmacy",
    status: "ativo",
    observation: "Plano inicial para farmácias.",
  },
  {
    id: "plan-pro",
    name: "Profissional",
    monthlyPrice: 349,
    maxUsers: 8,
    maxQuotationsMonth: 120,
    maxPharmacies: 3,
    modules: "both",
    status: "ativo",
    observation: "Plano com módulos de farmácia e licitação.",
  },
  {
    id: "plan-enterprise",
    name: "Licitações Enterprise",
    monthlyPrice: 899,
    maxUsers: 25,
    maxQuotationsMonth: 500,
    maxPharmacies: 10,
    modules: "distributor_bidding",
    status: "ativo",
    observation: "Plano para operação de licitações.",
  },
];

export const monthlySubscriptions: MonthlySubscription[] = [
  {
    id: "sub-2026-05-pharmacy",
    tenantId: "tenant-pharmacy",
    planId: "plan-pro",
    referenceMonth: "2026-05",
    dueDate: "2026-05-05",
    amount: 349,
    status: "paid",
    paymentMethod: "Pix",
    paidAt: "2026-05-05",
  },
  {
    id: "sub-2026-05-bidding",
    tenantId: "tenant-bidding",
    planId: "plan-enterprise",
    referenceMonth: "2026-05",
    dueDate: "2026-05-10",
    amount: 899,
    status: "pending",
    paymentMethod: "Pix",
  },
];

export const pharmacies: Pharmacy[] = [
  {
    id: "pharmacy-main",
    tenantId: "tenant-pharmacy",
    nomeFantasia: "Farmácia Exemplo",
    razaoSocial: "Farmácia Exemplo Ltda",
    cnpj: "12.345.678/0001-90",
    cidade: "Goiânia",
    uf: "GO",
    responsavel: "Marina Costa",
    whatsapp: "(62) 99999-0001",
    email: "compras@farmaciaexemplo.com.br",
    status: "ativo",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "supplier-joao",
    tenantId: "tenant-bidding",
    nome: "João Medicamentos",
    empresa: "João Medicamentos",
    whatsapp: "(62) 99911-1111",
    email: "joao@medicamentos.com.br",
    tipoFornecedor: "vendedor",
    status: "ativo",
  },
  {
    id: "supplier-ana",
    tenantId: "tenant-bidding",
    nome: "Ana Distribuidora",
    empresa: "Ana Distribuidora",
    whatsapp: "(61) 99922-2222",
    email: "ana@distribuidora.com.br",
    tipoFornecedor: "distribuidora",
    status: "ativo",
  },
  {
    id: "supplier-carlos",
    tenantId: "tenant-bidding",
    nome: "Carlos Farma",
    empresa: "Carlos Farma",
    whatsapp: "(63) 99933-3333",
    email: "carlos@farma.com.br",
    tipoFornecedor: "vendedor",
    status: "ativo",
  },
  {
    id: "supplier-luiza",
    tenantId: "tenant-pharmacy",
    nome: "Luiza Farma",
    empresa: "Rede Farma Luiza",
    whatsapp: "(62) 99944-4444",
    email: "luiza@rede.com.br",
    tipoFornecedor: "vendedor",
    status: "ativo",
  },
  {
    id: "supplier-marta",
    tenantId: "tenant-pharmacy",
    nome: "Marta Oliveira",
    empresa: "Marta Distribuidora",
    whatsapp: "(62) 98877-1212",
    email: "marta@distribuidora.com.br",
    tipoFornecedor: "vendedor",
    status: "ativo",
  },
];

export const distributors: Distributor[] = [
  {
    id: "dist-panpharma",
    tenantId: "tenant-pharmacy",
    nome: "Panpharma",
    unidadeCd: "GO",
    uf: "GO",
    pedidoMinimo: 50,
    prazoMedio: "1 dia",
    portal: "https://portal.panpharma.com.br",
    status: "ativo",
  },
  {
    id: "dist-profarma",
    tenantId: "tenant-pharmacy",
    nome: "Profarma",
    unidadeCd: "DF",
    uf: "DF",
    pedidoMinimo: 200,
    prazoMedio: "2 dias",
    status: "ativo",
  },
  {
    id: "dist-nazaria",
    tenantId: "tenant-pharmacy",
    nome: "Nazária Imperatriz",
    unidadeCd: "Imperatriz",
    uf: "MA",
    pedidoMinimo: 200,
    prazoMedio: "3 dias",
    status: "ativo",
  },
  {
    id: "dist-total",
    tenantId: "tenant-pharmacy",
    nome: "Total",
    unidadeCd: "TO",
    uf: "TO",
    pedidoMinimo: 300,
    prazoMedio: "4 dias",
    status: "ativo",
  },
];

export const laboratories: Laboratory[] = [
  { id: "lab-ems", tenantId: "tenant-bidding", nome: "EMS", tipo: "laboratorio", status: "ativo" },
  {
    id: "lab-eurofarma",
    tenantId: "tenant-bidding",
    nome: "Eurofarma",
    tipo: "laboratorio",
    status: "ativo",
  },
  {
    id: "lab-medley",
    tenantId: "tenant-bidding",
    nome: "Medley",
    tipo: "laboratorio",
    status: "ativo",
  },
  {
    id: "lab-generico",
    tenantId: "tenant-pharmacy",
    nome: "Genérico Farma",
    tipo: "marca",
    status: "ativo",
  },
];

export const products: Product[] = [
  {
    id: "product-losartana",
    tenantId: "tenant-pharmacy",
    nome: "Losartana 50mg c/30",
    principioAtivo: "Losartana Potássica",
    dosagem: "50mg",
    forma: "Comprimido",
    tipoProduto: "generico",
    ean: "7890000000011",
    unidadeBase: "CP",
    apresentacao: "Caixa com 30 comprimidos",
    quantidadePorEmbalagem: 30,
    status: "ativo",
  },
  {
    id: "product-dipirona",
    tenantId: "tenant-pharmacy",
    nome: "Dipirona 500mg c/20",
    principioAtivo: "Dipirona",
    dosagem: "500mg",
    forma: "Comprimido",
    tipoProduto: "mip",
    ean: "7890000000028",
    unidadeBase: "CP",
    apresentacao: "Caixa com 20 comprimidos",
    quantidadePorEmbalagem: 20,
    status: "ativo",
  },
  {
    id: "product-duloxetina",
    tenantId: "tenant-bidding",
    nome: "Duloxetina 30mg",
    principioAtivo: "Cloridrato de Duloxetina",
    dosagem: "30mg",
    forma: "Cápsula",
    tipoProduto: "generico_similar",
    unidadeBase: "CAP",
    apresentacao: "Cápsula",
    quantidadePorEmbalagem: 30,
    status: "ativo",
  },
  {
    id: "product-azitromicina",
    tenantId: "tenant-bidding",
    nome: "Azitromicina 500mg",
    principioAtivo: "Azitromicina",
    dosagem: "500mg",
    forma: "Comprimido",
    tipoProduto: "generico",
    unidadeBase: "CP",
    apresentacao: "Comprimido",
    quantidadePorEmbalagem: 3,
    status: "ativo",
  },
  {
    id: "product-ceftriaxona",
    tenantId: "tenant-bidding",
    nome: "Ceftriaxona 1g",
    principioAtivo: "Ceftriaxona Sódica",
    dosagem: "1g",
    forma: "Ampola",
    tipoProduto: "hospitalar",
    unidadeBase: "AMP",
    apresentacao: "Ampola",
    quantidadePorEmbalagem: 1,
    status: "ativo",
  },
];

export const quotations: Quotation[] = [
  {
    id: "quote-pharmacy-001",
    tenantId: "tenant-pharmacy",
    moduleType: "pharmacy",
    name: "Falteiro loja matriz - maio",
    pharmacyId: "pharmacy-main",
    quotationType: "generico_similar",
    deadlineAt: "2026-06-20T18:00:00-03:00",
    allowPartialSupply: true,
    allowEquivalent: true,
    considerMinimumOrder: true,
    notes: "Priorizar faturamento com entrega em até 48 horas.",
    status: "waiting_responses",
    createdBy: "user-compras",
    createdAt: "2026-05-12T10:00:00-03:00",
    updatedAt: "2026-05-14T09:00:00-03:00",
  },
  {
    id: "quote-bidding-001",
    tenantId: "tenant-bidding",
    moduleType: "bidding",
    name: "Pregão Duloxetina 30mg",
    buyerCompanyName: "Distribuidora Licitação Exemplo",
    destinationClient: "Município de Goiânia",
    processNumber: "2026.000145",
    bidNumber: "PE 041/2026",
    judgmentType: "by_item",
    deadlineAt: "2026-05-21T17:00:00-03:00",
    allowPartialSupply: true,
    allowEquivalent: true,
    considerMinimumOrder: false,
    notes: "Responder apenas itens com entrega confirmada. Sistema calcula preço por unidade automaticamente.",
    status: "analyzing",
    createdBy: "user-compras",
    createdAt: "2026-05-10T11:00:00-03:00",
    updatedAt: "2026-05-14T08:30:00-03:00",
  },
];

export const quotationItems: QuotationItem[] = [
  {
    id: "quote-item-losartana",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    moduleType: "pharmacy",
    itemNumber: 1,
    productId: "product-losartana",
    productName: "Losartana 50mg c/30",
    ean: "7890000000011",
    requestedQuantity: 120,
    requestedUnit: "CX",
    requestedLaboratory: "Qualquer",
    laboratoryRequired: false,
    productType: "generico",
    acceptEquivalent: true,
    allowPartialSupply: true,
    msRegistrationRequired: false,
    buyerObservation: "Aceita similar com mesmo princípio ativo.",
    lastPurchasePrice: 7.85,
    lastPurchaseDate: "2026-04-18",
    status: "aguardando_respostas",
  },
  {
    id: "quote-item-dipirona",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    moduleType: "pharmacy",
    itemNumber: 2,
    productId: "product-dipirona",
    productName: "Dipirona 500mg c/20",
    ean: "7890000000028",
    requestedQuantity: 80,
    requestedUnit: "CX",
    requestedLaboratory: "Qualquer",
    laboratoryRequired: false,
    productType: "mip",
    acceptEquivalent: true,
    allowPartialSupply: true,
    msRegistrationRequired: false,
    lastPurchasePrice: 5.2,
    lastPurchaseDate: "2026-04-22",
    status: "aguardando_respostas",
  },
  {
    id: "quote-item-duloxetina",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    moduleType: "bidding",
    itemNumber: 1,
    productId: "product-duloxetina",
    productName: "Duloxetina 30mg",
    activeIngredient: "Cloridrato de Duloxetina",
    dosage: "30mg",
    requestedQuantity: 100000,
    requestedUnit: "CAP",
    requestedLaboratory: "QUALQUER",
    laboratoryRequired: false,
    productType: "generico_similar",
    acceptEquivalent: true,
    allowPartialSupply: true,
    msRegistrationRequired: false,
    buyerObservation: "Produto solicitado em cápsulas. Cotar caixa e o sistema converterá para unidade.",
    status: "aguardando_respostas",
  },
];

export const supplierQuoteSessions: SupplierQuoteSession[] = [
  {
    id: "session-pharmacy-luiza",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    supplierId: "supplier-luiza",
    publicToken: "farmacia-demo-token",
    sellerName: "Luiza",
    sellerCompany: "Rede Farma Luiza",
    sellerWhatsapp: "(62) 99944-4444",
    sellerEmail: "luiza@rede.com.br",
    expiresAt: "2026-06-20T18:00:00-03:00",
    status: "opened",
  },
  {
    id: "session-pharmacy-marta",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    supplierId: "supplier-marta",
    publicToken: "farmacia-marta-demo-token",
    sellerName: "Marta",
    sellerCompany: "Marta Distribuidora",
    sellerWhatsapp: "(62) 98877-1212",
    sellerEmail: "marta@distribuidora.com.br",
    expiresAt: "2026-06-20T18:00:00-03:00",
    status: "submitted",
  },
  {
    id: "session-bidding-joao",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    supplierId: "supplier-joao",
    publicToken: "licitacao-demo-token",
    sellerName: "João",
    sellerCompany: "João Medicamentos",
    sellerWhatsapp: "(62) 99911-1111",
    sellerEmail: "joao@medicamentos.com.br",
    expiresAt: "2026-05-21T17:00:00-03:00",
    submittedAt: "2026-05-13T15:00:00-03:00",
    status: "submitted",
  },
];

export const supplierQuoteResponses: SupplierQuoteResponse[] = [
  {
    id: "response-pharmacy-luiza",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    sessionId: "session-pharmacy-luiza",
    supplierId: "supplier-luiza",
    sellerName: "Luiza",
    sellerCompany: "Rede Farma Luiza",
    sellerWhatsapp: "(62) 99944-4444",
    sellerEmail: "luiza@rede.com.br",
    billingCompany: "Panpharma GO",
    paymentTerms: "28 dias",
    deliveryTerms: "Até 48 horas",
    status: "submitted",
    submittedAt: "2026-05-14T08:15:00-03:00",
  },
  {
    id: "response-pharmacy-marta",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    sessionId: "session-pharmacy-marta",
    supplierId: "supplier-marta",
    sellerName: "Marta",
    sellerCompany: "Marta Distribuidora",
    sellerWhatsapp: "(62) 98877-1212",
    sellerEmail: "marta@distribuidora.com.br",
    billingCompany: "Marta Distribuidora",
    paymentTerms: "21 dias",
    deliveryTerms: "Ate 72 horas",
    status: "submitted",
    submittedAt: "2026-05-14T08:40:00-03:00",
  },
  {
    id: "response-bidding-joao",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    sessionId: "session-bidding-joao",
    supplierId: "supplier-joao",
    sellerName: "João",
    sellerCompany: "João Medicamentos",
    sellerWhatsapp: "(62) 99911-1111",
    sellerEmail: "joao@medicamentos.com.br",
    status: "submitted",
    submittedAt: "2026-05-13T15:00:00-03:00",
  },
  {
    id: "response-bidding-ana",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    sessionId: "session-bidding-ana",
    supplierId: "supplier-ana",
    sellerName: "Ana",
    sellerCompany: "Ana Distribuidora",
    sellerWhatsapp: "(61) 99922-2222",
    sellerEmail: "ana@distribuidora.com.br",
    status: "submitted",
    submittedAt: "2026-05-13T15:10:00-03:00",
  },
  {
    id: "response-bidding-carlos",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    sessionId: "session-bidding-carlos",
    supplierId: "supplier-carlos",
    sellerName: "Carlos",
    sellerCompany: "Carlos Farma",
    sellerWhatsapp: "(63) 99933-3333",
    sellerEmail: "carlos@farma.com.br",
    status: "submitted",
    submittedAt: "2026-05-13T15:20:00-03:00",
  },
];

export const supplierQuoteResponseItems: SupplierQuoteResponseItem[] = [
  {
    id: "response-item-losartana-luiza",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    quotationItemId: "quote-item-losartana",
    responseId: "response-pharmacy-luiza",
    supplierId: "supplier-luiza",
    unitPrice: 7.42,
    hasStock: true,
    availableQuantity: 120,
    distributorId: "dist-panpharma",
    sellerObservation: "Entrega em 24 horas.",
  },
  {
    id: "response-item-dipirona-luiza",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    quotationItemId: "quote-item-dipirona",
    responseId: "response-pharmacy-luiza",
    supplierId: "supplier-luiza",
    unitPrice: 4.98,
    hasStock: true,
    availableQuantity: 80,
    distributorId: "dist-panpharma",
  },
  {
    id: "response-item-losartana-marta",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    quotationItemId: "quote-item-losartana",
    responseId: "response-pharmacy-marta",
    supplierId: "supplier-marta",
    unitPrice: 7.8,
    hasStock: true,
    availableQuantity: 120,
    distributorId: "dist-profarma",
    sellerObservation: "Entrega em ate 72 horas.",
  },
  {
    id: "response-item-dipirona-marta",
    tenantId: "tenant-pharmacy",
    quotationId: "quote-pharmacy-001",
    quotationItemId: "quote-item-dipirona",
    responseId: "response-pharmacy-marta",
    supplierId: "supplier-marta",
    unitPrice: 5.1,
    hasStock: true,
    availableQuantity: 80,
    distributorId: "dist-profarma",
  },
  {
    id: "response-item-duloxetina-joao",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    quotationItemId: "quote-item-duloxetina",
    responseId: "response-bidding-joao",
    supplierId: "supplier-joao",
    offeredProductName: "Duloxetina 30mg c/30",
    offeredLaboratory: "EMS",
    offeredUnit: "CAP",
    packageQuantity: 30,
    packagePrice: 39.9,
    hasFullQuantity: false,
    availableQuantity: 60000,
    deliveryDays: 3,
  },
  {
    id: "response-item-duloxetina-ana",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    quotationItemId: "quote-item-duloxetina",
    responseId: "response-bidding-ana",
    supplierId: "supplier-ana",
    offeredProductName: "Duloxetina 30mg c/60",
    offeredLaboratory: "Eurofarma",
    offeredUnit: "CAP",
    packageQuantity: 60,
    packagePrice: 82.8,
    hasFullQuantity: false,
    availableQuantity: 30000,
    deliveryDays: 5,
  },
  {
    id: "response-item-duloxetina-carlos",
    tenantId: "tenant-bidding",
    quotationId: "quote-bidding-001",
    quotationItemId: "quote-item-duloxetina",
    responseId: "response-bidding-carlos",
    supplierId: "supplier-carlos",
    offeredProductName: "Duloxetina 30mg c/30",
    offeredLaboratory: "Medley",
    offeredUnit: "CAP",
    packageQuantity: 30,
    packagePrice: 43.5,
    hasFullQuantity: true,
    availableQuantity: 50000,
    deliveryDays: 7,
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "log-1",
    tenantId: "tenant-bidding",
    actor: "Renato Lima",
    action: "Gerou análise por unidade convertida",
    entity: "quote-bidding-001",
    severity: "info",
    createdAt: "2026-05-14T08:30:00-03:00",
  },
  {
    id: "log-2",
    tenantId: "tenant-pharmacy",
    actor: "Marina Costa",
    action: "Abriu cotação para fornecedores",
    entity: "quote-pharmacy-001",
    severity: "info",
    createdAt: "2026-05-12T10:30:00-03:00",
  },
  {
    id: "log-3",
    actor: "Sistema",
    action: "Webhook Efí aguardando configuração",
    entity: "payments",
    severity: "warning",
    createdAt: "2026-05-14T07:45:00-03:00",
  },
];
