import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";

const ACTIONS = { cliente:"cadastro_cliente", fazenda:"cadastro_fazenda", talhao:"cadastro_talhao", os:"ordem_servico" } as const;
const OS_EVENT_ACTION = "ordem_servico_evento";
type ResourceType = keyof typeof ACTIONS;
type ApiContext = { usuarioId:string; usuarioNome:string; usuarioTipo:string; empresaId:string|null; canManage:boolean };
const OS_STATUSES = ["aberta","em_preparacao","em_execucao","suspensa","concluida","cancelada"] as const;

function normalizeType(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function isResourceType(value:string|null):value is ResourceType{return value==="cliente"||value==="fazenda"||value==="talhao"||value==="os"}
function cleanText(value:unknown,max=180){return typeof value==="string"?value.trim().slice(0,max):""}
function cleanNumber(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
function cleanData(type:ResourceType,value:unknown){const s=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
  if(type==="cliente")return{nome:cleanText(s.nome),cpfCnpj:cleanText(s.cpfCnpj,30),telefone:cleanText(s.telefone,40),email:cleanText(s.email,120),observacoes:cleanText(s.observacoes,500)};
  if(type==="fazenda")return{clienteId:cleanText(s.clienteId,80),nome:cleanText(s.nome),municipio:cleanText(s.municipio,120),uf:cleanText(s.uf,2).toUpperCase(),endereco:cleanText(s.endereco,240),latitude:cleanNumber(s.latitude),longitude:cleanNumber(s.longitude),observacoes:cleanText(s.observacoes,500)};
  if(type==="talhao")return{fazendaId:cleanText(s.fazendaId,80),nome:cleanText(s.nome),areaHa:cleanNumber(s.areaHa),culturaPadrao:cleanText(s.culturaPadrao,120),latitude:cleanNumber(s.latitude),longitude:cleanNumber(s.longitude),observacoes:cleanText(s.observacoes,500)};
  const status=cleanText(s.status,30);return{numero:cleanText(s.numero,60),clienteId:cleanText(s.clienteId,80),fazendaId:cleanText(s.fazendaId,80),talhaoId:cleanText(s.talhaoId,80),cultura:cleanText(s.cultura,120),alvo:cleanText(s.alvo,160),areaHa:cleanNumber(s.areaHa),dataPrevista:cleanText(s.dataPrevista,30),status:OS_STATUSES.includes(status as any)?status:"aberta",observacoes:cleanText(s.observacoes,800),pilotoResponsavelId:cleanText(s.pilotoResponsavelId,80),pilotoResponsavelNome:cleanText(s.pilotoResponsavelNome,180),preparadaEm:cleanText(s.preparadaEm,40),iniciadaEm:cleanText(s.iniciadaEm,40),suspensaEm:cleanText(s.suspensaEm,40),finalizadaEm:cleanText(s.finalizadaEm,40)};
}
function validateRequired(type:ResourceType,data:Record<string,unknown>){if(type==="cliente"&&!data.nome)throw new Error("Informe o nome do cliente.");if(type==="fazenda"&&(!data.clienteId||!data.nome||!data.municipio||!data.uf))throw new Error("Informe cliente, fazenda, município e UF.");if(type==="talhao"&&(!data.fazendaId||!data.nome||cleanNumber(data.areaHa)<=0))throw new Error("Informe fazenda, nome do talhão e área maior que zero.");if(type==="os"&&(!data.clienteId||!data.fazendaId||!data.talhaoId||cleanNumber(data.areaHa)<=0))throw new Error("Informe cliente, fazenda, talhão e área da ordem de serviço.")}
async function getContext():Promise<{current:ApiContext|null;response:NextResponse|null}>{const context=await getSessionProfile();if(!context.user||!context.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const admin=["super_admin","admin_master"].includes(context.profile.tipo);const allowed=(context.appsLiberados??[]).some(app=>app.slug==="dronegestor"&&app.canAccess);if(!admin&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};const normalized=normalizeType(context.profile.tipo);return{current:{usuarioId:context.profile.id,usuarioNome:context.profile.nome||"Piloto",usuarioTipo:context.profile.tipo,empresaId:context.profile.empresa_id,canManage:admin||["admin_empresa","responsavel_tecnico","rt"].includes(normalized)},response:null}}
function scopeQuery(query:any,current:ApiContext){return current.empresaId?query.eq("empresa_id",current.empresaId):query.eq("usuario_id",current.usuarioId)}
async function findEntity(admin:any,current:ApiContext,type:ResourceType,entityId:string){let query=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTIONS[type]).contains("detalhes",{entityId}).limit(1);query=scopeQuery(query,current);const {data,error}=await query.maybeSingle();if(error)throw error;if(!data||data.detalhes?.ativo===false)return null;return data}
async function requireRelations(admin:any,current:ApiContext,type:ResourceType,data:Record<string,unknown>){if(type==="fazenda"){if(!await findEntity(admin,current,"cliente",cleanText(data.clienteId,80)))throw new Error("O cliente selecionado não existe ou está inativo.");return}if(type==="talhao"){if(!await findEntity(admin,current,"fazenda",cleanText(data.fazendaId,80)))throw new Error("A fazenda selecionada não existe ou está inativa.");return}if(type==="os"){const cliente=await findEntity(admin,current,"cliente",cleanText(data.clienteId,80)),fazenda=await findEntity(admin,current,"fazenda",cleanText(data.fazendaId,80)),talhao=await findEntity(admin,current,"talhao",cleanText(data.talhaoId,80));if(!cliente||!fazenda||!talhao)throw new Error("Cliente, fazenda e talhão precisam estar ativos.");if(fazenda.detalhes?.data?.clienteId!==data.clienteId)throw new Error("A fazenda não pertence ao cliente informado.");if(talhao.detalhes?.data?.fazendaId!==data.fazendaId)throw new Error("O talhão não pertence à fazenda informada.")}}
async function hasDependency(admin:any,current:ApiContext,action:string,dataPatch:Record<string,unknown>){let query=admin.from("core_logs").select("id,detalhes").eq("app_slug","dronegestor").eq("acao",action).contains("detalhes",{ativo:true,data:dataPatch}).limit(1);query=scopeQuery(query,current);const {data,error}=await query.maybeSingle();if(error)throw error;return Boolean(data)}
async function hasActiveOsForTalhao(admin:any,current:ApiContext,talhaoId:string){let query=admin.from("core_logs").select("id,detalhes").eq("app_slug","dronegestor").eq("acao",ACTIONS.os).contains("detalhes",{ativo:true,data:{talhaoId}}).limit(500);query=scopeQuery(query,current);const {data,error}=await query;if(error)throw error;return (data??[]).some((row:any)=>["aberta","em_preparacao","em_execucao","suspensa"].includes(row.detalhes?.data?.status||"aberta"))}
function onlyStatusPatch(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return false;const keys=Object.keys(value as Record<string,unknown>);return keys.length===1&&keys[0]==="status"}
async function logOsEvent(admin:any,current:ApiContext,osId:string,evento:string,extra:Record<string,unknown>={}){await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuarioId,app_slug:"dronegestor",acao:OS_EVENT_ACTION,detalhes:{osId,evento,at:new Date().toISOString(),usuarioId:current.usuarioId,usuarioNome:current.usuarioNome,...extra}})}
function pilotSafeData(type:ResourceType,data:Record<string,unknown>){if(type==="cliente")return{nome:data.nome};if(type==="fazenda")return{clienteId:data.clienteId,nome:data.nome,municipio:data.municipio,uf:data.uf};if(type==="talhao")return{fazendaId:data.fazendaId,nome:data.nome,areaHa:data.areaHa,culturaPadrao:data.culturaPadrao};return{numero:data.numero,clienteId:data.clienteId,fazendaId:data.fazendaId,talhaoId:data.talhaoId,cultura:data.cultura,alvo:data.alvo,areaHa:data.areaHa,dataPrevista:data.dataPrevista,status:data.status,pilotoResponsavelId:data.pilotoResponsavelId,pilotoResponsavelNome:data.pilotoResponsavelNome,preparadaEm:data.preparadaEm,iniciadaEm:data.iniciadaEm,suspensaEm:data.suspensaEm,finalizadaEm:data.finalizadaEm}}
function transitionAllowed(current:string,next:string,canManage:boolean){if(current===next)return true;if(current==="aberta")return next==="em_preparacao"||(canManage&&next==="cancelada");if(current==="em_preparacao")return next==="em_execucao"||next==="aberta"||(canManage&&next==="cancelada");if(current==="em_execucao")return next==="suspensa";if(current==="suspensa")return next==="em_execucao"||(canManage&&next==="cancelada");return false}

export async function GET(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!,type=request.nextUrl.searchParams.get("type");if(!isResourceType(type))return NextResponse.json({ok:false,error:"Tipo de cadastro inválido."},{status:400});const admin=createSupabaseAdminClient() as any;let query=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTIONS[type]).order("created_at",{ascending:false}).limit(500);query=scopeQuery(query,current);const {data,error}=await query;if(error)throw error;const items=(data??[]).map((row:any)=>{const details=row.detalhes??{},rawData=details.data??{};return{id:row.id,dbCreatedAt:row.created_at,...details,data:current.canManage?rawData:pilotSafeData(type,rawData)}}).filter((item:any)=>item.ativo!==false);return NextResponse.json({ok:true,items,canManage:current.canManage})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao carregar cadastros."},{status:500})}}

export async function POST(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!;if(!current.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode criar cadastros e ordens de serviço."},{status:403});const body=await request.json(),type=cleanText(body?.type,20);if(!isResourceType(type))return NextResponse.json({ok:false,error:"Tipo de cadastro inválido."},{status:400});const data=cleanData(type,body?.data) as Record<string,unknown>;validateRequired(type,data);const admin=createSupabaseAdminClient() as any;await requireRelations(admin,current,type,data);const entityId=crypto.randomUUID(),now=new Date().toISOString();if(type==="os"){if(!data.numero){const stamp=now.slice(0,10).replaceAll("-","");data.numero=`OS-${stamp}-${entityId.slice(0,5).toUpperCase()}`}data.status="aberta";data.pilotoResponsavelId="";data.pilotoResponsavelNome=""}const detalhes={entityId,type,ativo:true,createdAt:now,updatedAt:now,data};const {data:inserted,error}=await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuarioId,app_slug:"dronegestor",acao:ACTIONS[type],detalhes}).select("id").single();if(error)throw error;if(type==="os")await logOsEvent(admin,current,entityId,"criada");return NextResponse.json({ok:true,item:{id:inserted.id,...detalhes}})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao salvar cadastro."},{status:500})}}

export async function PATCH(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!,body=await request.json(),type=cleanText(body?.type,20),entityId=cleanText(body?.entityId,80);if(!isResourceType(type)||!entityId)return NextResponse.json({ok:false,error:"Cadastro inválido."},{status:400});const statusPatch=type==="os"&&onlyStatusPatch(body?.data),requestedStatus=statusPatch?cleanText(body?.data?.status,30):"";const operational=statusPatch&&["em_preparacao","em_execucao","suspensa","aberta"].includes(requestedStatus);if(!current.canManage&&!operational)return NextResponse.json({ok:false,error:"Seu perfil não pode editar cadastros administrativos."},{status:403});const admin=createSupabaseAdminClient() as any,existing=await findEntity(admin,current,type,entityId);if(!existing)return NextResponse.json({ok:false,error:"Registro não encontrado ou inativo."},{status:404});const currentDetails=existing.detalhes??{},currentData={...(currentDetails.data??{})};let patchData=body?.data??{};
  if(type==="os"&&statusPatch){const currentStatus=cleanText(currentData.status,30)||"aberta";let effectiveStatus=requestedStatus;if(requestedStatus==="em_preparacao"&&["em_execucao","suspensa"].includes(currentStatus))effectiveStatus=currentStatus;if(!transitionAllowed(currentStatus,effectiveStatus,current.canManage))return NextResponse.json({ok:false,error:`Transição de ${currentStatus} para ${requestedStatus} não permitida.`},{status:409});const assigned=cleanText(currentData.pilotoResponsavelId,80);if(["em_preparacao","em_execucao","suspensa"].includes(effectiveStatus)){if(assigned&&assigned!==current.usuarioId)return NextResponse.json({ok:false,error:`Esta OS já está atribuída a ${currentData.pilotoResponsavelNome||"outro piloto"}.`},{status:409});currentData.pilotoResponsavelId=current.usuarioId;currentData.pilotoResponsavelNome=current.usuarioNome;if(effectiveStatus==="em_preparacao"&&!currentData.preparadaEm)currentData.preparadaEm=new Date().toISOString();if(effectiveStatus==="em_execucao"&&!currentData.iniciadaEm)currentData.iniciadaEm=new Date().toISOString();if(effectiveStatus==="suspensa")currentData.suspensaEm=new Date().toISOString()}if(effectiveStatus==="aberta"){if(!current.canManage&&assigned&&assigned!==current.usuarioId)return NextResponse.json({ok:false,error:"Somente o piloto responsável pode liberar esta OS."},{status:409});currentData.pilotoResponsavelId="";currentData.pilotoResponsavelNome="";currentData.preparadaEm="";currentData.suspensaEm=""}patchData={status:effectiveStatus};}
  const data=cleanData(type,{...currentData,...patchData}) as Record<string,unknown>;validateRequired(type,data);await requireRelations(admin,current,type,data);const detalhes={...currentDetails,entityId,type,ativo:true,updatedAt:new Date().toISOString(),data};const {error}=await admin.from("core_logs").update({detalhes}).eq("id",existing.id);if(error)throw error;if(type==="os"&&statusPatch&&data.status!==currentDetails.data?.status)await logOsEvent(admin,current,entityId,String(data.status),{statusAnterior:currentDetails.data?.status||"aberta"});return NextResponse.json({ok:true,item:{id:existing.id,...detalhes}})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao atualizar cadastro."},{status:500})}}

export async function DELETE(request:NextRequest){try{const access=await getContext();if(access.response)return access.response;const current=access.current!;if(!current.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode inativar cadastros."},{status:403});const body=await request.json(),type=cleanText(body?.type,20),entityId=cleanText(body?.entityId,80);if(!isResourceType(type)||!entityId)return NextResponse.json({ok:false,error:"Cadastro inválido."},{status:400});const admin=createSupabaseAdminClient() as any,existing=await findEntity(admin,current,type,entityId);if(!existing)return NextResponse.json({ok:false,error:"Registro não encontrado ou inativo."},{status:404});if(type==="cliente"&&await hasDependency(admin,current,ACTIONS.fazenda,{clienteId:entityId}))return NextResponse.json({ok:false,error:"Este cliente possui fazenda ativa."},{status:409});if(type==="fazenda"&&await hasDependency(admin,current,ACTIONS.talhao,{fazendaId:entityId}))return NextResponse.json({ok:false,error:"Esta fazenda possui talhão ativo."},{status:409});if(type==="talhao"&&await hasActiveOsForTalhao(admin,current,entityId))return NextResponse.json({ok:false,error:"Este talhão possui OS aberta/em preparação/em execução/suspensa."},{status:409});if(type==="os"){const status=existing.detalhes?.data?.status;if(["em_preparacao","em_execucao","suspensa","concluida"].includes(status))return NextResponse.json({ok:false,error:"OS em preparação, execução, suspensa ou concluída não pode ser inativada."},{status:409})}const detalhes={...(existing.detalhes??{}),ativo:false,updatedAt:new Date().toISOString()};const {error}=await admin.from("core_logs").update({detalhes}).eq("id",existing.id);if(error)throw error;return NextResponse.json({ok:true})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao remover cadastro."},{status:500})}}
