import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";
const ACTION="piloto_operacional_v1";
type Permissions={executarOs:boolean;editarParametros:boolean;editarSeguranca:boolean;registrarSarpas:boolean;anexarEvidencias:boolean;finalizarOperacao:boolean;verRelatorios:boolean};
type Pilot={id:string;nome:string;cpf:string;telefone:string;email:string;observacoes:string;ativo:boolean;usuarioId:string;permissoes:Permissions;createdAt?:string;updatedAt?:string};
type Context={usuarioId:string;usuarioNome:string;empresaId:string|null;canManage:boolean};
const defaultPermissions:Permissions={executarOs:true,editarParametros:false,editarSeguranca:true,registrarSarpas:false,anexarEvidencias:true,finalizarOperacao:true,verRelatorios:false};
function normalize(value:string){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function text(value:unknown,max=180){return typeof value==="string"?value.trim().slice(0,max):""}
function permissions(value:unknown):Permissions{const source=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return{executarOs:source.executarOs!==false,editarParametros:source.editarParametros===true,editarSeguranca:source.editarSeguranca!==false,registrarSarpas:source.registrarSarpas===true,anexarEvidencias:source.anexarEvidencias!==false,finalizarOperacao:source.finalizarOperacao!==false,verRelatorios:source.verRelatorios===true}}
function sanitize(value:unknown,id:string):Pilot{const source=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return{id,nome:text(source.nome,180),cpf:text(source.cpf,32),telefone:text(source.telefone,40),email:text(source.email,180).toLowerCase(),observacoes:text(source.observacoes,500),ativo:source.ativo!==false,usuarioId:text(source.usuarioId,80),permissoes:permissions(source.permissoes??defaultPermissions),createdAt:text(source.createdAt,40),updatedAt:text(source.updatedAt,40)}}
async function context():Promise<{current:Context|null;response:NextResponse|null}>{const data=await getSessionProfile();if(!data.user||!data.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const type=normalize(data.profile.tipo),master=["super_admin","admin_master"].includes(type),allowed=(data.appsLiberados??[]).some(app=>app.slug==="dronegestor"&&app.canAccess);if(!master&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{usuarioId:data.profile.id,usuarioNome:data.profile.nome||"Gestor",empresaId:data.profile.empresa_id,canManage:master||["admin_empresa","responsavel_tecnico","rt"].includes(type)},response:null}}
function scope(query:any,current:Context){return current.empresaId?query.eq("empresa_id",current.empresaId):query.eq("usuario_id",current.usuarioId)}
async function findRow(admin:any,current:Context,id:string){let query=admin.from("core_logs").select("id,detalhes").eq("app_slug","dronegestor").eq("acao",ACTION).contains("detalhes",{id}).limit(1);query=scope(query,current);const{data,error}=await query.maybeSingle();if(error)throw error;return data}
async function linkUser(admin:any,current:Context,pilot:Pilot){if(!pilot.email)return pilot;let query=admin.from("core_usuarios").select("id,email,status,empresa_id").ilike("email",pilot.email).limit(1);if(current.empresaId)query=query.eq("empresa_id",current.empresaId);const{data,error}=await query.maybeSingle();if(error)return pilot;return{...pilot,usuarioId:data?.status==="ativo"?String(data.id||""):""}}
export async function GET(){try{const access=await context();if(access.response)return access.response;const current=access.current!,admin=createSupabaseAdminClient() as any;let query=admin.from("core_logs").select("detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTION).order("created_at",{ascending:true}).limit(300);query=scope(query,current);const{data,error}=await query;if(error)throw error;const raw=(data??[]).map((row:any)=>sanitize(row.detalhes,row.detalhes?.id||"")).filter((item:Pilot)=>item.id&&item.ativo);const linked=await Promise.all(raw.map((item:Pilot)=>linkUser(admin,current,item)));const items=current.canManage?linked:linked.filter((item:Pilot)=>item.usuarioId===current.usuarioId);return NextResponse.json({ok:true,items,canManage:current.canManage,defaultPermissions,currentUserId:current.usuarioId,currentUserName:current.usuarioNome})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao carregar pilotos."},{status:500})}}
export async function POST(request:NextRequest){try{const access=await context();if(access.response)return access.response;const current=access.current!;if(!current.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode cadastrar pilotos."},{status:403});const body=await request.json(),id=crypto.randomUUID(),now=new Date().toISOString(),admin=createSupabaseAdminClient() as any;let pilot=sanitize({...body,ativo:true,createdAt:now,updatedAt:now,permissoes:body?.permissoes??defaultPermissions},id);if(!pilot.nome)return NextResponse.json({ok:false,error:"Informe o nome do piloto."},{status:400});pilot=await linkUser(admin,current,pilot);const{error}=await admin.from("core_logs").insert({empresa_id:current.empresaId,usuario_id:current.usuarioId,app_slug:"dronegestor",acao:ACTION,detalhes:pilot});if(error)throw error;return NextResponse.json({ok:true,item:pilot})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao cadastrar piloto."},{status:500})}}
export async function PATCH(request:NextRequest){try{const access=await context();if(access.response)return access.response;const current=access.current!;if(!current.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode alterar pilotos."},{status:403});const body=await request.json(),id=text(body?.id,80);if(!id)return NextResponse.json({ok:false,error:"Piloto inválido."},{status:400});const admin=createSupabaseAdminClient() as any,row=await findRow(admin,current,id);if(!row)return NextResponse.json({ok:false,error:"Piloto não encontrado."},{status:404});let next=sanitize({...row.detalhes,...body,id,updatedAt:new Date().toISOString()},id);if(!next.nome)return NextResponse.json({ok:false,error:"Informe o nome do piloto."},{status:400});next=await linkUser(admin,current,next);const{error}=await admin.from("core_logs").update({detalhes:next}).eq("id",row.id);if(error)throw error;return NextResponse.json({ok:true,item:next})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao atualizar piloto."},{status:500})}}
export async function DELETE(request:NextRequest){try{const access=await context();if(access.response)return access.response;const current=access.current!;if(!current.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode inativar pilotos."},{status:403});const body=await request.json(),id=text(body?.id,80);if(!id)return NextResponse.json({ok:false,error:"Piloto inválido."},{status:400});const admin=createSupabaseAdminClient() as any,row=await findRow(admin,current,id);if(!row)return NextResponse.json({ok:false,error:"Piloto não encontrado."},{status:404});const next=sanitize({...row.detalhes,id,ativo:false,updatedAt:new Date().toISOString()},id);const{error}=await admin.from("core_logs").update({detalhes:next}).eq("id",row.id);if(error)throw error;return NextResponse.json({ok:true})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao inativar piloto."},{status:500})}}
