import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic="force-dynamic";
const BUCKET="dronegestor-documentos";
const ACTION="modelo_relatorio_mapa_2026_v1";
const MAX=10*1024*1024;
type Context={userId:string;empresaId:string|null;canManage:boolean;userName:string};
function normalize(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function safe(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"-").slice(0,80)||"geral"}
async function context():Promise<{current:Context|null;response:NextResponse|null}>{const s=await getSessionProfile();if(!s.user||!s.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const t=normalize(s.profile.tipo||""),master=["super_admin","admin_master"].includes(t),allowed=(s.appsLiberados??[]).some(a=>a.slug==="dronegestor"&&a.canAccess);if(!master&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{userId:s.profile.id,empresaId:s.profile.empresa_id,canManage:master||["admin_empresa","responsavel_tecnico","rt"].includes(t),userName:s.profile.nome||"Usuário"},response:null}}
function scope(q:any,c:Context){return c.empresaId?q.eq("empresa_id",c.empresaId):q.eq("usuario_id",c.userId)}
async function latest(admin:any,c:Context){let q=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTION).order("created_at",{ascending:false}).limit(1);q=scope(q,c);const{data,error}=await q.maybeSingle();if(error)throw error;return data}

export async function GET(){try{const a=await context();if(a.response)return a.response;const c=a.current!,admin=createSupabaseAdminClient() as any,row=await latest(admin,c);if(!row)return NextResponse.json({ok:true,model:null,canManage:c.canManage});return NextResponse.json({ok:true,canManage:c.canManage,model:{fileName:row.detalhes?.fileName||"modelo-oficial.xlsx",version:row.detalhes?.version||"01-01-2026",uploadedAt:row.detalhes?.uploadedAt||row.created_at,uploadedBy:row.detalhes?.uploadedBy||""}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao consultar modelo oficial."},{status:500})}}

export async function POST(request:NextRequest){try{const a=await context();if(a.response)return a.response;const c=a.current!;if(!c.canManage)return NextResponse.json({ok:false,error:"Somente ADMIN/RT pode cadastrar o modelo oficial."},{status:403});const form=await request.formData(),file=form.get("arquivo");if(!(file instanceof File)||file.size<=0)return NextResponse.json({ok:false,error:"Escolha a planilha oficial .xlsx."},{status:400});if(file.size>MAX)return NextResponse.json({ok:false,error:"Planilha maior que 10 MB."},{status:400});const bytes=Buffer.from(await file.arrayBuffer());if(bytes.length<4||bytes[0]!==0x50||bytes[1]!==0x4b||bytes[2]!==0x03||bytes[3]!==0x04)return NextResponse.json({ok:false,error:"Arquivo inválido. Envie o XLSX oficial do MAPA."},{status:400});const admin=createSupabaseAdminClient() as any,owner=c.empresaId?`empresa-${safe(c.empresaId)}`:`usuario-${safe(c.userId)}`,storagePath=`${owner}/modelos-mapa/${Date.now()}-relatorio-mensal-2026.xlsx`;const up=await admin.storage.from(BUCKET).upload(storagePath,bytes,{contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",upsert:false});if(up.error)throw up.error;const details={storagePath,fileName:file.name.slice(0,240),version:"01-01-2026",uploadedAt:new Date().toISOString(),uploadedBy:c.userName,bytes:bytes.length};const ins=await admin.from("core_logs").insert({empresa_id:c.empresaId,usuario_id:c.userId,app_slug:"dronegestor",acao:ACTION,detalhes:details});if(ins.error){await admin.storage.from(BUCKET).remove([storagePath]);throw ins.error}return NextResponse.json({ok:true,model:details});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao cadastrar modelo oficial."},{status:500})}}
