"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ClipboardList, Download, FileSpreadsheet, History, LoaderCircle, RefreshCcw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Product={nome?:string;dose?:number;unidade?:string};
type Summary={piloto?:string;ordemServicoNumero?:string;clienteNome?:string;fazendaNome?:string;talhaoNome?:string;municipio?:string;uf?:string;cultura?:string;alvo?:string;tipoAtividade?:string;areaHa?:number;areaConcluidaHa?:number;progressSource?:string;drone?:string;identificacaoAnac?:string;pontaPulverizacao?:string;documentoTecnicoReferencia?:string;volumeLHa?:number;totalCaldaL?:number;faixaM?:number;velocidadeKmh?:number;alturaM?:number;sarpasNumero?:string;sarpasSituacao?:string;sarpasConfirmado?:boolean;climaCampo?:{ventoKmh?:number;direcaoVento?:string;temperaturaC?:number;umidadePct?:number;medidoEm?:string};gps?:{latitude?:number;longitude?:number;capturadoEm?:string};produtos?:Product[];calibracaoConcluida?:boolean;checklistConcluido?:boolean;totalOcorrencias?:number;iniciadaEm?:string;finalizadaEm?:string};
type HistoryItem={id:string;created_at:string;detalhes?:{operationId?:string;finalizedAt?:string;summary?:Summary}};
function number(v:unknown,d=1){return new Intl.NumberFormat("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v)||0)}
function dateTime(v?:string){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}
function csvCell(v:unknown){return `"${String(v??"").replaceAll('"','""')}"`}

export function DroneHistoricoClientV2({userName,companyMode}:{userName:string;companyMode:boolean}){
  const [items,setItems]=useState<HistoryItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("");
  async function load(){setLoading(true);setError("");try{const all:HistoryItem[]=[];let offset=0,hasMore=true,pages=0;while(hasMore&&pages<30){const response=await fetch(`/api/dronegestor/state?history=1&limit=500&offset=${offset}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||"Falha ao carregar histórico.");const page=Array.isArray(payload?.items)?payload.items:[];all.push(...page);hasMore=Boolean(payload?.hasMore);offset=Number(payload?.nextOffset||0);pages+=1;if(!hasMore)break}setItems(all)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar histórico.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const visible=useMemo(()=>{const q=filter.trim().toLowerCase();if(!q)return items;return items.filter(item=>{const s=item.detalhes?.summary??{};return [s.ordemServicoNumero,s.clienteNome,s.fazendaNome,s.talhaoNome,s.piloto,s.cultura,s.alvo,s.uf].some(v=>String(v??"").toLowerCase().includes(q))})},[items,filter]);
  const totals=useMemo(()=>visible.reduce((a,item)=>{const s=item.detalhes?.summary;a.area+=Number(s?.areaConcluidaHa??s?.areaHa??0)||0;a.calda+=Number(s?.totalCaldaL??0)||0;a.oc+=Number(s?.totalOcorrencias??0)||0;return a},{area:0,calda:0,oc:0}),[visible]);
  function exportCsv(){const header=["data_conclusao","inicio","termino","os_numero","cliente","fazenda","talhao","municipio","uf","piloto","atividade","cultura","alvo","area_real_ha","fonte_area","drone","identificacao_anac","ponta_atomizador","documento_tecnico","volume_l_ha","calda_total_l","faixa_m","velocidade_kmh","altura_m","sarpas_situacao","sarpas_referencia","vento_kmh","direcao_vento","temperatura_c","umidade_pct","latitude","longitude","produtos","ocorrencias"];const rows=visible.map(item=>{const s=item.detalhes?.summary??{},products=(s.produtos??[]).map(p=>`${p.nome||"Produto"} | ${p.dose??0} ${p.unidade||""}`.trim()).join("; ");return[item.detalhes?.finalizedAt||item.created_at,s.iniciadaEm,s.finalizadaEm,s.ordemServicoNumero,s.clienteNome,s.fazendaNome,s.talhaoNome,s.municipio,s.uf,s.piloto,s.tipoAtividade,s.cultura,s.alvo,s.areaConcluidaHa??s.areaHa,s.progressSource,s.drone,s.identificacaoAnac,s.pontaPulverizacao,s.documentoTecnicoReferencia,s.volumeLHa,s.totalCaldaL,s.faixaM,s.velocidadeKmh,s.alturaM,s.sarpasSituacao,s.sarpasNumero,s.climaCampo?.ventoKmh,s.climaCampo?.direcaoVento,s.climaCampo?.temperaturaC,s.climaCampo?.umidadePct,s.gps?.latitude,s.gps?.longitude,products,s.totalOcorrencias??0].map(csvCell).join(";")});const blob=new Blob(["\ufeff",header.join(";"),"\n",rows.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`dronegestor-historico-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
  return <main className="min-h-screen bg-[#07110d] px-3 py-6 text-emerald-50"><div className="mx-auto grid w-full max-w-6xl gap-4"><header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Link href="/apps/dronegestor" className="grid size-11 place-items-center rounded-xl border border-emerald-800"><ArrowLeft size={20}/></Link><div><small className="font-black uppercase text-emerald-300">DroneGestor Agro</small><h1 className="text-3xl font-black">Histórico de operações</h1><p className="text-sm text-emerald-200/70">{companyMode?"Visão consolidada da empresa/RT":`Operações de ${userName}`}</p></div></div><div className="flex gap-2"><Link href="/apps/dronegestor/gestao" className="rounded-xl border border-emerald-800 px-3 py-2 font-bold"><ClipboardList className="mr-2 inline" size={16}/>OS</Link><button onClick={()=>void load()} className="rounded-xl border border-emerald-800 px-3 py-2 font-bold"><RefreshCcw className="mr-2 inline" size={16}/>Atualizar</button><button disabled={!visible.length} onClick={exportCsv} className="rounded-xl bg-emerald-500 px-3 py-2 font-black text-slate-950 disabled:bg-slate-700"><Download className="mr-2 inline" size={16}/>CSV</button></div></header><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filtrar por OS, cliente, fazenda, talhão, piloto, cultura ou UF..." className="min-h-12 rounded-xl border border-emerald-900 bg-slate-950 px-4 text-white"/><section className="grid grid-cols-2 gap-2 md:grid-cols-4"><Metric label="Operações" value={String(visible.length)}/><Metric label="Área real" value={`${number(totals.area,1)} ha`}/><Metric label="Calda planejada" value={`${number(totals.calda,0)} L`}/><Metric label="Ocorrências" value={String(totals.oc)}/></section><div className="rounded-2xl border border-emerald-900 bg-emerald-950/40 p-4 text-sm"><FileSpreadsheet className="mr-2 inline" size={18}/><strong>Histórico completo carregado por páginas.</strong> O CSV continua sendo base de conferência, não o relatório mensal oficial.</div>{loading?<div className="grid min-h-52 place-items-center"><LoaderCircle className="animate-spin"/></div>:error?<div className="rounded-xl bg-red-950 p-4 text-red-200">{error}</div>:!visible.length?<div className="grid min-h-52 place-items-center"><History size={34}/><span>Nenhuma operação encontrada.</span></div>:<section className="grid gap-3">{visible.map(item=><OperationCard key={item.id} item={item}/>)}</section>}</div></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-emerald-900 bg-slate-950/60 p-4"><small className="text-slate-400">{label}</small><strong className="block text-xl">{value}</strong></div>}
function OperationCard({item}:{item:HistoryItem}){const s=item.detalhes?.summary??{},products=s.produtos??[];return <article className="rounded-2xl border border-emerald-900 bg-slate-950/70 p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="text-xs font-black text-emerald-300"><CheckCircle2 className="mr-1 inline" size={15}/>OPERAÇÃO CONCLUÍDA {s.ordemServicoNumero?`• ${s.ordemServicoNumero}`:""}</div><h2 className="mt-2 text-xl font-black">{s.cultura||"Cultura"} {s.alvo?`• ${s.alvo}`:""}</h2><small className="text-slate-400">{dateTime(s.finalizadaEm||item.detalhes?.finalizedAt||item.created_at)} • {s.piloto||"Piloto"}</small></div><div className="text-right"><strong className="text-2xl text-emerald-200">{number(s.areaConcluidaHa??s.areaHa,2)} ha</strong><small className="block text-slate-400">Fonte: {s.progressSource||"registro"}</small></div></div><div className="mt-3 grid gap-2 text-sm md:grid-cols-3"><Mini label="Cliente/área" value={[s.clienteNome,s.fazendaNome,s.talhaoNome].filter(Boolean).join(" → ")||"—"}/><Mini label="Drone / ANAC" value={`${s.drone||"—"} • ${s.identificacaoAnac||"—"}`}/><Mini label="Ponta/atomizador" value={s.pontaPulverizacao||"—"}/><Mini label="Início / término" value={`${dateTime(s.iniciadaEm)} → ${dateTime(s.finalizadaEm)}`}/><Mini label="SARPAS" value={`${s.sarpasSituacao||"—"} ${s.sarpasNumero||""}`.trim()}/><Mini label="Clima campo" value={`${number(s.climaCampo?.ventoKmh,1)} km/h • ${number(s.climaCampo?.temperaturaC,1)}°C • UR ${number(s.climaCampo?.umidadePct,0)}%`}/></div>{products.length>0&&<p className="mt-3 text-xs text-slate-300">Produtos: {products.map(p=>`${p.nome} ${p.dose} ${p.unidade}`).join(" • ")}</p>}</article>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/5 p-3"><small className="text-slate-400">{label}</small><strong className="block text-sm">{value}</strong></div>}
