"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileArchive, FileText, FolderCheck, MapPinned, PlaneTakeoff, Printer, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Mission={ordemServicoId?:string;ordemServicoNumero?:string;clienteNome?:string;fazendaNome?:string;talhaoNome?:string;municipio?:string;uf?:string;cultura?:string;alvo?:string;area?:number;drone?:string;registroAnac?:string;pontaModelo?:string;produtos?:Array<{nome?:string;dose?:number;unidade?:string}>;sarpasSituacao?:string;sarpasNumero?:string};
type Doc={id:string;tipo:string;nome:string;url:string;validade:string};
type MapEvidence={url?:string;uploadedAt?:string}|null;
type Sarpas={status?:string;numero?:string}|null;
type PackageState={mission:Mission;calibration?:Record<string,boolean>;checklist?:Record<string,boolean>;weather?:Record<string,unknown>;tankRecords?:unknown[];occurrences?:unknown[];progressHa?:number;startedAt?:string;endedAt?:string;insightAccepted?:boolean;riskAccepted?:boolean};
const DOC_LABELS:Record<string,string>={sarpas_autorizacao:"Autorização SARPAS",sisant_certidao:"Certidão SISANT/ANAC",avaliacao_risco:"Avaliação de risco",receituario:"Receituário agronômico",mapa_aplicacao:"Mapa da aplicação",seguro:"Seguro",exame_piloto_anac:"Comprovante/exame do piloto",registro_mapa:"Registro MAPA/SIPEAGRO",relatorio_mapa:"Relatório mensal MAPA",outro:"Outro documento"};
function json<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function allTrue(value?:Record<string,boolean>){return Boolean(value&&Object.keys(value).length&&Object.values(value).every(Boolean))}
function fmt(value:unknown,d=1){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}).format(n):"—"}

export function DroneOperationPackage(){
 const[state,setState]=useState<PackageState>({mission:{}});const[docs,setDocs]=useState<Doc[]>([]);const[map,setMap]=useState<MapEvidence>(null);const[sarpas,setSarpas]=useState<Sarpas>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{const local:PackageState={mission:json<Mission>("dronegestor:mission:v2",{}),calibration:json("dronegestor:calibration:v2",{}),checklist:json("dronegestor:checklist:v2",{}),weather:json("dronegestor:weather",{}),tankRecords:json("dronegestor:tankRecords:v4",[]),occurrences:json("dronegestor:occurrences:v2",[]),progressHa:json("dronegestor:progress:v2",0),startedAt:json("dronegestor:startedAt:v4",""),endedAt:json("dronegestor:endedAt:v4",""),insightAccepted:json("dronegestor:insightAccepted:v2",false),riskAccepted:json("dronegestor:riskAccepted:v2",false)};setState(local);const osId=local.mission.ordemServicoId;if(!osId){setLoading(false);return;}void Promise.all([fetch(`/api/dronegestor/documentos?osId=${encodeURIComponent(osId)}`,{cache:"no-store"}),fetch(`/api/dronegestor/mapa?osId=${encodeURIComponent(osId)}`,{cache:"no-store"}),fetch(`/api/dronegestor/sarpas?osId=${encodeURIComponent(osId)}`,{cache:"no-store"})]).then(async([dr,mr,sr])=>{const[d,m,s]=await Promise.all([dr.json().catch(()=>null),mr.json().catch(()=>null),sr.json().catch(()=>null)]);if(dr.ok)setDocs(d?.items||[]);if(mr.ok)setMap(m?.evidence||null);if(sr.ok)setSarpas(s?.sarpas||null)}).finally(()=>setLoading(false));},[]);
 const mission=state.mission; const has=(type:string)=>docs.some(d=>d.tipo===type); const sarpasFinal=["autorizado","dispensado","nao_aplicavel"].includes(sarpas?.status||mission.sarpasSituacao||"");
 const sections=useMemo(()=>[
  {title:"Identificação da operação",icon:<FolderCheck size={19}/>,items:[{ok:Boolean(mission.ordemServicoId),label:`OS ${mission.ordemServicoNumero||"não selecionada"}`},{ok:Boolean(mission.clienteNome&&mission.fazendaNome&&mission.talhaoNome),label:"Cliente, fazenda e talhão identificados"},{ok:Boolean(mission.municipio&&mission.uf),label:"Município/UF da operação"},{ok:Boolean(mission.drone&&mission.registroAnac),label:"Drone e identificação ANAC"}]},
  {title:"Parte técnica",icon:<ShieldCheck size={19}/>,items:[{ok:Boolean(mission.cultura&&mission.alvo),label:"Cultura e alvo"},{ok:Boolean(mission.produtos?.length&&mission.produtos.every(p=>p.nome&&Number(p.dose)>0&&p.unidade)),label:"Produtos e doses registrados"},{ok:allTrue(state.calibration),label:"Calibração concluída"},{ok:allTrue(state.checklist),label:"Checklist concluído"},{ok:Boolean(state.riskAccepted),label:"Risco confirmado no campo"},{ok:Boolean(state.weather&&Object.keys(state.weather).length),label:"Registro meteorológico/GPS"}]},
  {title:"Aeronáutica / espaço aéreo",icon:<PlaneTakeoff size={19}/>,items:[{ok:Boolean(mission.registroAnac),label:"Registro/identificação da aeronave"},{ok:has("sisant_certidao"),label:"Certidão SISANT anexada"},{ok:sarpasFinal,label:"Situação SARPAS concluída ou conferida"},{ok:(sarpas?.status||mission.sarpasSituacao)!=="autorizado"||has("sarpas_autorizacao"),label:"Comprovante SARPAS anexado quando autorizado"},{ok:has("exame_piloto_anac"),label:"Comprovante documental do piloto anexado"}]},
  {title:"Agronômica e evidências",icon:<MapPinned size={19}/>,items:[{ok:has("receituario"),label:"Receituário anexado quando aplicável"},{ok:Boolean(map?.url)||has("mapa_aplicacao"),label:"Mapa/evidência da aplicação"},{ok:has("registro_mapa"),label:"Registro MAPA/SIPEAGRO disponível no pacote"},{ok:Boolean(state.tankRecords?.length),label:"Cargas/abastecimentos reais registrados"},{ok:true,label:`Ocorrências registradas: ${state.occurrences?.length||0}`}]}
 ],[mission,state,docs,map,sarpas,sarpasFinal]);
 const checks=sections.flatMap(s=>s.items);const percent=Math.round(checks.filter(i=>i.ok).length/checks.length*100);
 return <main className="min-h-screen bg-[#f4f8f1] px-3 pb-28 pt-4 text-[#143d31] sm:px-6 sm:py-8"><style>{`@media print{.no-print{display:none!important}body{background:white!important}.package-card{box-shadow:none!important;break-inside:avoid}}`}</style><div className="mx-auto w-full max-w-5xl">
  <div className="no-print flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/apps/dronegestor" className="grid size-11 place-items-center rounded-2xl border border-[#d6e5dc] bg-white text-[#276650]"><ArrowLeft size={20}/></Link><div><h1 className="text-2xl font-black">Pacote da operação</h1><p className="text-sm text-[#6b7c73]">Dossiê lógico da OS para conferência e arquivo.</p></div></div><button onClick={()=>window.print()} className="grid size-11 place-items-center rounded-2xl bg-[#087a55] text-white" aria-label="Imprimir índice do pacote"><Printer size={19}/></button></div>
  {!mission.ordemServicoId?<div className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-5"><TriangleAlert className="mr-2 inline" size={18}/><strong>Selecione uma OS para montar o pacote.</strong><p className="mt-2 text-sm">O pacote pertence à operação, não ao aparelho.</p></div>:<>
   <section className="mt-5 rounded-[30px] bg-[linear-gradient(145deg,#064e3b,#023b2b)] p-5 text-white sm:p-7"><div className="flex items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-white/10"><FileArchive size={27}/></span><div className="min-w-0 flex-1"><span className="text-xs font-black uppercase tracking-[.16em] text-[#86d7aa]">{mission.ordemServicoNumero||"OS"}</span><h2 className="mt-2 text-2xl font-black">{[mission.fazendaNome,mission.talhaoNome].filter(Boolean).join(" • ")||"Operação"}</h2><p className="mt-2 text-sm text-[#c8ddd2]">{mission.cultura||"—"} • {fmt(mission.area)} ha • {mission.drone||"—"}</p></div><div className="grid size-16 shrink-0 place-items-center rounded-full bg-white/10 text-xl font-black">{percent}%</div></div></section>
   <div className="mt-4 grid gap-4 lg:grid-cols-2">{sections.map(section=><section key={section.title} className="package-card rounded-[26px] border border-[#d9e8df] bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-[#0b7653]">{section.icon}<h3 className="font-black text-[#163e31]">{section.title}</h3></div><div className="mt-3 grid gap-2">{section.items.map((item,i)=><div key={i} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold ${item.ok?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-950"}`}>{item.ok?<CheckCircle2 size={17}/>:<TriangleAlert size={17}/>}<span>{item.label}</span></div>)}</div></section>)}</div>
   <section className="package-card mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileText size={19} className="text-[#087a55]"/><h3 className="font-black">Arquivos vinculados</h3></div>{loading?<p className="mt-3 text-sm">Carregando...</p>:docs.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{docs.map(d=><a key={d.id} href={d.url||"#"} target="_blank" rel="noreferrer" className="rounded-xl border border-[#e0eae4] px-3 py-3 no-underline"><strong className="block text-sm text-[#163e31]">{DOC_LABELS[d.tipo]||d.tipo}</strong><span className="mt-1 block truncate text-xs text-[#718078]">{d.nome}</span></a>)}</div>:<p className="mt-3 text-sm text-[#718078]">Nenhum documento enviado para esta OS.</p>}</section>
   <div className="no-print mt-4 grid gap-3 sm:grid-cols-3"><Link href="/apps/dronegestor/documentos" className="rounded-2xl bg-[#087a55] px-4 py-4 text-center font-black text-white no-underline">SARPAS e documentos</Link><Link href="/apps/dronegestor/fichas" className="rounded-2xl border border-[#c8ddd1] bg-white px-4 py-4 text-center font-black text-[#176a4c] no-underline">Ficha da operação</Link><Link href="/apps/dronegestor/relatorio-mensal" className="rounded-2xl border border-[#c8ddd1] bg-white px-4 py-4 text-center font-black text-[#176a4c] no-underline">Relatório mensal MAPA</Link></div>
   <p className="mt-4 text-xs leading-5 text-[#718078]">Este pacote organiza evidências e documentos da operação. Ele não substitui protocolo em SARPAS, SEI, SIPEAGRO, SISANT ou documento oficial emitido pelo órgão competente.</p>
  </>}
 </div></main>
}
