"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, FileArchive, FileText, Printer, TriangleAlert, XCircle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Mission={ordemServicoId?:string;ordemServicoNumero?:string;clienteNome?:string;fazendaNome?:string;talhaoNome?:string;municipio?:string;uf?:string;cultura?:string;alvo?:string;area?:number;drone?:string;registroAnac?:string;pontaModelo?:string;produtos?:Array<{nome?:string;dose?:number;unidade?:string}>;sarpasSituacao?:string;sarpasNumero?:string;climaCampoConfirmado?:boolean;climaCampoMedidoEm?:string;ventoCampoKmh?:number|null;direcaoVentoCampo?:string;temperaturaCampo?:number|null;umidadeCampo?:number|null};
type Doc={id:string;tipo:string;nome:string;url:string;validade:string};
type Evidence={url?:string}|null;
type Sarpas={status?:string;numero?:string}|null;
type LocalState={mission:Mission;calibration?:Record<string,boolean>;checklist?:Record<string,boolean>;weather?:Record<string,unknown>;tankRecords?:unknown[];occurrences?:unknown[];startedAt?:string;endedAt?:string;riskAccepted?:boolean;operationStarted?:boolean;missionStatus?:string};
type Level="block"|"doc";
type Check={ok:boolean;label:string;level:Level;href?:string;action?:string};

const LABELS:Record<string,string>={sarpas_autorizacao:"Autorização SARPAS",sisant_certidao:"Certidão SISANT/ANAC",avaliacao_risco:"Avaliação de risco",receituario:"Receituário agronômico",mapa_aplicacao:"Mapa da aplicação",seguro:"Seguro",exame_piloto_anac:"Documento do piloto",registro_mapa:"Registro MAPA/SIPEAGRO",relatorio_mapa:"Relatório mensal MAPA",outro:"Outro documento"};
function read<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function done(value?:Record<string,boolean>){return Boolean(value&&Object.keys(value).length&&Object.values(value).every(Boolean))}
function fmt(value:unknown){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:2}).format(n):"—"}

export function DroneOperationPackage(){
 const[state,setState]=useState<LocalState>({mission:{}}),[docs,setDocs]=useState<Doc[]>([]),[map,setMap]=useState<Evidence>(null),[sarpas,setSarpas]=useState<Sarpas>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const local:LocalState={mission:read("dronegestor:mission:v2",{}),calibration:read("dronegestor:calibration:v2",{}),checklist:read("dronegestor:checklist:v2",{}),weather:read("dronegestor:weather",{}),tankRecords:read("dronegestor:tankRecords:v4",[]),occurrences:read("dronegestor:occurrences:v2",[]),startedAt:read("dronegestor:startedAt:v4",""),endedAt:read("dronegestor:endedAt:v4",""),riskAccepted:read("dronegestor:riskAccepted:v2",false),operationStarted:read("dronegestor:started:v3",false),missionStatus:read("dronegestor:missionStatus:v4","rascunho")};setState(local);const osId=local.mission.ordemServicoId;if(!osId){setLoading(false);return}void Promise.all([fetch(`/api/dronegestor/documentos?osId=${encodeURIComponent(osId)}`,{cache:"no-store"}),fetch(`/api/dronegestor/mapa?osId=${encodeURIComponent(osId)}`,{cache:"no-store"}),fetch(`/api/dronegestor/sarpas?osId=${encodeURIComponent(osId)}`,{cache:"no-store"})]).then(async([a,b,c])=>{const[d,m,s]=await Promise.all([a.json().catch(()=>null),b.json().catch(()=>null),c.json().catch(()=>null)]);if(a.ok)setDocs(d?.items||[]);if(b.ok)setMap(m?.evidence||null);if(c.ok)setSarpas(s?.sarpas||null)}).finally(()=>setLoading(false))},[]);
 const m=state.mission,has=(type:string)=>docs.some(d=>d.tipo===type),sStatus=sarpas?.status||m.sarpasSituacao||"",sNumber=sarpas?.numero||m.sarpasNumero||"",sFinal=["autorizado","dispensado","nao_aplicavel"].includes(sStatus);
 const climate=Boolean(m.climaCampoConfirmado&&m.climaCampoMedidoEm&&m.direcaoVentoCampo?.trim()&&m.ventoCampoKmh!==null&&m.ventoCampoKmh!==undefined&&m.temperaturaCampo!==null&&m.temperaturaCampo!==undefined&&m.umidadeCampo!==null&&m.umidadeCampo!==undefined);
 const gps=Boolean(state.weather&&Number.isFinite(Number(state.weather.latitude))&&Number.isFinite(Number(state.weather.longitude))),started=Boolean(state.operationStarted||state.startedAt),ended=Boolean(state.endedAt||["finalizada","pendente_sync"].includes(state.missionStatus||""));
 const checks=useMemo<Check[]>(()=>[
  {ok:Boolean(m.ordemServicoId&&m.clienteNome&&m.fazendaNome&&m.talhaoNome&&m.municipio&&m.uf),label:"OS, cliente, fazenda e talhão completos",level:"block",href:"/apps/dronegestor/gestao",action:"Corrigir OS"},
  {ok:Boolean(m.drone&&m.registroAnac&&m.pontaModelo),label:"Drone, ANAC e sistema de aplicação definidos",level:"block",href:"/apps/dronegestor/equipamentos",action:"Conferir drone"},
  {ok:Boolean(m.cultura&&m.alvo),label:"Cultura e alvo informados",level:"block",href:"/apps/dronegestor/campo?resolver=nova",action:"Completar missão"},
  {ok:Boolean(m.produtos?.length&&m.produtos.every(p=>p.nome&&Number(p.dose)>0&&p.unidade)),label:"Produtos e doses conferidos",level:"block",href:"/apps/dronegestor/campo?resolver=calda",action:"Conferir calda"},
  {ok:climate,label:"Clima real medido no talhão",level:"block",href:"/apps/dronegestor/campo?resolver=seguranca",action:"Medir clima"},
  {ok:Boolean(state.riskAccepted),label:"Análise de risco confirmada",level:"block",href:"/apps/dronegestor/campo?resolver=seguranca",action:"Revisar segurança"},
  {ok:gps,label:"Ponto GPS registrado",level:"block",href:"/apps/dronegestor/campo?resolver=seguranca",action:"Registrar GPS"},
  {ok:done(state.calibration),label:"Calibração concluída",level:"block",href:"/apps/dronegestor/campo?resolver=calibracao",action:"Calibrar"},
  {ok:done(state.checklist),label:"Checklist pré-voo concluído",level:"block",href:"/apps/dronegestor/campo?resolver=checklist",action:"Fazer checklist"},
  {ok:sFinal,label:"Situação SARPAS conferida",level:"block",href:"/apps/dronegestor/documentos?focus=sarpas#sarpas-card",action:"Resolver SARPAS"},
  {ok:sStatus!=="autorizado"||Boolean(sNumber),label:"Referência SARPAS informada quando autorizada",level:"block",href:"/apps/dronegestor/documentos?focus=sarpas#sarpas-card",action:"Informar referência"},
  {ok:has("sisant_certidao"),label:"Certidão SISANT anexada",level:"doc",href:"/apps/dronegestor/documentos?doc=sisant_certidao#document-upload",action:"Anexar SISANT"},
  {ok:sStatus!=="autorizado"||has("sarpas_autorizacao"),label:"Comprovante SARPAS anexado quando autorizado",level:"doc",href:"/apps/dronegestor/documentos?doc=sarpas_autorizacao#document-upload",action:"Anexar autorização"},
  {ok:has("receituario"),label:"Receituário anexado quando aplicável",level:"doc",href:"/apps/dronegestor/documentos?doc=receituario#document-upload",action:"Anexar receituário"},
  {ok:Boolean(map?.url)||has("mapa_aplicacao"),label:"Mapa usado na operação registrado",level:"doc",href:"/apps/dronegestor/campo?resolver=seguranca",action:"Registrar mapa"},
  {ok:has("registro_mapa"),label:"Registro MAPA/SIPEAGRO disponível no pacote",level:"doc",href:"/apps/dronegestor/documentos?doc=registro_mapa#document-upload",action:"Anexar registro"},
  {ok:!started&&!ended||Boolean(state.tankRecords?.length),label:!started&&!ended?"Cargas serão registradas durante a aplicação":"Cargas reais registradas",level:"block",href:"/apps/dronegestor/campo?resolver=execucao",action:"Registrar cargas"}
 ],[m,state,docs,map,sStatus,sNumber,sFinal,climate,gps,started,ended]);
 const pending=checks.filter(c=>!c.ok),blocks=pending.filter(c=>c.level==="block"),docPending=pending.filter(c=>c.level==="doc"),percent=Math.round(checks.filter(c=>c.ok).length/checks.length*100);
 const status=loading?{title:"CONFERINDO",text:"Carregando documentos e evidências.",cls:"border-sky-200 bg-sky-50 text-sky-950",icon:<TriangleAlert/>}:blocks.length?{title:ended?"PACOTE COM PENDÊNCIA CRÍTICA":"LIBERAÇÃO BLOQUEADA",text:ended?"A operação terminou, mas ainda existem pendências críticas no pacote.":"Resolva as travas operacionais antes de iniciar a aplicação.",cls:"border-red-200 bg-red-50 text-red-950",icon:<XCircle/>}:docPending.length?{title:"PENDÊNCIA DOCUMENTAL",text:"As travas operacionais estão atendidas, mas o dossiê ainda precisa de documentos/evidências.",cls:"border-amber-200 bg-amber-50 text-amber-950",icon:<TriangleAlert/>}:{title:ended?"PACOTE COMPLETO":started?"EM EXECUÇÃO — CONFERIDO":"LIBERADO",text:ended?"A conferência técnica e documental está completa.":"A central não aponta pendências nesta conferência.",cls:"border-emerald-200 bg-emerald-50 text-emerald-950",icon:<CheckCircle2/>};
 return <main className="min-h-screen bg-[#f4f8f1] px-3 pb-28 pt-4 text-[#143d31] sm:px-6 sm:py-8"><style>{`@media print{.no-print{display:none!important}.card{break-inside:avoid;box-shadow:none!important}}`}</style><div className="mx-auto w-full max-w-5xl">
  <div className="no-print flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Link href="/apps/dronegestor" className="grid size-11 shrink-0 place-items-center rounded-2xl border bg-white"><ArrowLeft size={20}/></Link><div className="min-w-0"><h1 className="text-2xl font-black">Central de liberação</h1><p className="text-sm text-[#6b7c73]">Travas, documentos e pacote da operação em uma tela.</p></div></div><button onClick={()=>window.print()} className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#087a55] text-white"><Printer size={19}/></button></div>
  {!m.ordemServicoId?<section className="mt-5 rounded-3xl border border-amber-200 bg-amber-50 p-5"><strong>Selecione uma ordem de serviço.</strong><p className="mt-2 text-sm">A central pertence à OS ativa.</p><Link href="/apps/dronegestor/gestao" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#087a55] px-4 font-black text-white no-underline">Selecionar OS <ArrowRight size={16}/></Link></section>:<>
   <section className="mt-5 rounded-[28px] bg-[#063f2d] p-5 text-white"><div className="flex items-start gap-3"><FileArchive className="shrink-0"/><div className="min-w-0 flex-1"><span className="text-xs font-black uppercase text-[#8ed8af]">{m.ordemServicoNumero||"OS ativa"}</span><h2 className="mt-1 text-xl font-black">{[m.fazendaNome,m.talhaoNome].filter(Boolean).join(" • ")||"Operação"}</h2><p className="mt-1 text-sm text-[#c9ddd2]">{m.cultura||"—"} • {fmt(m.area)} ha • {m.drone||"—"}</p></div><div className="grid size-14 shrink-0 place-items-center rounded-full bg-white/10 font-black">{percent}%</div></div></section>
   <section className={`card mt-4 rounded-3xl border p-5 ${status.cls}`}><div className="flex items-start gap-3"><span className="mt-1 shrink-0">{status.icon}</span><div><span className="text-xs font-black uppercase">Status da operação</span><h2 className="mt-1 text-2xl font-black">{status.title}</h2><p className="mt-1 text-sm leading-6">{status.text}</p></div></div>{!loading&&<div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat value={blocks.length} label="Travas"/><Stat value={docPending.length} label="Documentos"/><Stat value={`${percent}%`} label="Completo"/></div>}</section>
   {!loading&&pending.length>0&&<section className="card mt-4 rounded-3xl border border-[#d9e8df] bg-white p-5"><h3 className="font-black">O que falta resolver</h3><p className="mt-1 text-sm text-[#718078]">O botão leva direto para a etapa correspondente.</p><div className="mt-4 grid gap-2">{pending.map((c,i)=><div key={`${c.label}-${i}`} className={`rounded-2xl border p-3 ${c.level==="block"?"border-red-200 bg-red-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2"><TriangleAlert size={17}/><strong className="text-sm">{c.label}</strong></div>{c.href&&<Link href={c.href} className={`mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl px-3 text-sm font-black text-white no-underline ${c.level==="block"?"bg-red-700":"bg-amber-700"}`}>{c.action||"Resolver agora"}<ArrowRight size={15}/></Link>}</div>)}</div></section>}
   <section className="card mt-4 rounded-3xl border border-[#d9e8df] bg-white p-5"><h3 className="font-black">Conferência completa</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{checks.map((c,i)=><div key={i} className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-bold ${c.ok?"bg-emerald-50 text-emerald-900":c.level==="block"?"bg-red-50 text-red-950":"bg-amber-50 text-amber-950"}`}>{c.ok?<CheckCircle2 size={17}/>:<TriangleAlert size={17}/>}<span>{c.label}</span></div>)}</div></section>
   <section className="card mt-4 rounded-3xl border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-2"><FileText size={18}/><h3 className="font-black">Arquivos vinculados</h3></div>{loading?<p className="mt-3 text-sm">Carregando...</p>:docs.length?<div className="mt-3 grid gap-2 sm:grid-cols-2">{docs.map(d=><a key={d.id} href={d.url||"#"} target="_blank" rel="noreferrer" className="rounded-xl border p-3 no-underline"><strong className="block text-sm text-[#163e31]">{LABELS[d.tipo]||d.tipo}</strong><span className="block truncate text-xs text-[#718078]">{d.nome}</span></a>)}</div>:<p className="mt-3 text-sm text-[#718078]">Nenhum documento anexado.</p>}</section>
   <div className="no-print mt-4 grid gap-3 sm:grid-cols-3"><Link href="/apps/dronegestor/documentos" className="rounded-2xl bg-[#087a55] px-4 py-4 text-center font-black text-white no-underline">SARPAS e documentos</Link><Link href="/apps/dronegestor/fichas" className="rounded-2xl border bg-white px-4 py-4 text-center font-black no-underline">Ficha da operação</Link><Link href="/apps/dronegestor/relatorio-mensal" className="rounded-2xl border bg-white px-4 py-4 text-center font-black no-underline">Relatório mensal MAPA</Link></div>
   <p className="mt-4 text-xs leading-5 text-[#718078]">Esta central organiza a conferência interna e o dossiê. Ela não substitui autorizações, documentos oficiais, bula, receituário ou decisão do responsável técnico.</p>
  </>}
 </div></main>
}
function Stat({value,label}:{value:string|number;label:string}){return <div className="rounded-xl bg-white/70 p-2"><strong className="block text-lg">{value}</strong><span className="text-[10px] font-black uppercase">{label}</span></div>}
