"use client";

import { AlertTriangle, CheckCircle2, ChevronRight, CirclePause, ClipboardList, Clock3, FileCheck2, Loader2, PlaneTakeoff, RefreshCw, Signal, Sprout, UserRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Counts={total:number;aplicando:number;pausada:number;aguardandoSarpas:number;regularizacao:number;prontaEncerrar:number};
type Item={osId:string;numero:string;status:string;stage:string;stageLabel:string;nextAction:string;pilotId:string;pilotName:string;cliente:string;fazenda:string;talhao:string;municipio:string;uf:string;cultura:string;alvo:string;areaHa:number;progressHa:number;percent:number;tanks:number;occurrences:number;paused:boolean;sarpasStatus:string;sarpasNumero:string;closureStatus:string;pending:string[];lastSync:string;dataPrevista:string;createdAt:string};
type Payload={ok:boolean;items:Item[];counts:Counts;updatedAt:string;error?:string};
const empty:Counts={total:0,aplicando:0,pausada:0,aguardandoSarpas:0,regularizacao:0,prontaEncerrar:0};
function fmt(v:unknown,d=1){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}).format(n):"0"}
function since(value:string){if(!value)return"Sem atualização do aparelho";const ms=Date.now()-Date.parse(value);if(!Number.isFinite(ms))return"Atualização sem horário";const min=Math.max(0,Math.floor(ms/60000));if(min<1)return"Atualizado agora";if(min<60)return`Atualizado há ${min} min`;const h=Math.floor(min/60);if(h<24)return`Atualizado há ${h} h`;return`Atualizado há ${Math.floor(h/24)} d`}
function attention(stage:string){return["pausada","aguardando_sarpas","regularizacao","pronta_encerrar"].includes(stage)}
function tone(stage:string){if(stage==="aplicando")return"border-emerald-200 bg-emerald-50 text-emerald-800";if(stage==="pausada")return"border-amber-300 bg-amber-50 text-amber-900";if(stage==="aguardando_sarpas")return"border-sky-200 bg-sky-50 text-sky-900";if(stage==="regularizacao")return"border-orange-200 bg-orange-50 text-orange-900";if(stage==="pronta_encerrar")return"border-violet-200 bg-violet-50 text-violet-900";if(stage==="encerrada")return"border-slate-200 bg-slate-50 text-slate-600";if(stage==="cancelada")return"border-red-200 bg-red-50 text-red-700";return"border-slate-200 bg-white text-slate-700"}

export function DroneManagerOperationsPanel(){
  const[data,setData]=useState<Payload>({ok:true,items:[],counts:empty,updatedAt:""}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[onlyAttention,setOnlyAttention]=useState(false);
  async function load(silent=false){if(!silent)setLoading(true);try{const response=await fetch("/api/dronegestor/painel-gestor",{cache:"no-store"}),payload=await response.json().catch(()=>null);if(!response.ok||!payload?.ok)throw new Error(payload?.error||"Não foi possível carregar o painel.");setData(payload as Payload);setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar painel.")}finally{if(!silent)setLoading(false)}}
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),20000);return()=>window.clearInterval(timer)},[]);
  const visible=useMemo(()=>onlyAttention?data.items.filter(i=>attention(i.stage)):data.items.filter(i=>i.stage!=="cancelada"),[data.items,onlyAttention]);
  function selectOs(item:Item,target?:string){
    let current:Record<string,unknown>={};try{current=JSON.parse(localStorage.getItem("dronegestor:mission:v2")||"{}")}catch{}
    const mission={...current,ordemServicoId:item.osId,ordemServicoNumero:item.numero,clienteNome:item.cliente,fazendaNome:item.fazenda,talhaoNome:item.talhao,municipio:item.municipio,uf:item.uf,area:item.areaHa,cultura:item.cultura,alvo:item.alvo};
    localStorage.setItem("dronegestor:mission:v2",JSON.stringify(mission));localStorage.setItem("dronegestor:activeMissionContext:v1",JSON.stringify(mission));
    if(target)window.location.href=target;else document.getElementById("drone-os-management")?.scrollIntoView({behavior:"smooth",block:"start"});
  }

  return <section className="mx-auto mt-4 w-full max-w-6xl px-3 sm:mt-6 sm:px-6">
    <div className="overflow-hidden rounded-[28px] border border-emerald-200 bg-white shadow-sm">
      <header className="bg-[linear-gradient(135deg,#064e3b,#087a55)] p-5 text-white sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-black uppercase tracking-wider"><Sprout size={15}/> Painel do gestor</div><h2 className="mt-3 text-2xl font-black">O que precisa da sua atenção agora</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-emerald-100">Acompanhe equipe e OS sem abrir uma por uma. O painel mostra a situação e a próxima ação em linguagem simples.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="grid size-11 shrink-0 place-items-center rounded-2xl bg-white/10 text-white disabled:opacity-50" aria-label="Atualizar painel">{loading?<Loader2 className="animate-spin" size={20}/>:<RefreshCw size={20}/>}</button></div>
        <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5"><Kpi label="Aplicando" value={data.counts.aplicando} icon={<Signal size={17}/>} /><Kpi label="Pausadas" value={data.counts.pausada} icon={<CirclePause size={17}/>} warn/><Kpi label="Aguardando SARPAS" value={data.counts.aguardandoSarpas} icon={<PlaneTakeoff size={17}/>} /><Kpi label="Regularização" value={data.counts.regularizacao} icon={<AlertTriangle size={17}/>} warn/><Kpi label="Prontas p/ encerrar" value={data.counts.prontaEncerrar} icon={<FileCheck2 size={17}/>} /></div>
      </header>

      <div className="p-4 sm:p-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm text-slate-950">{data.counts.total} OS ativa(s)</strong><p className="mt-1 text-xs text-slate-500">Atualização automática a cada 20 segundos quando houver conexão.</p></div><button type="button" onClick={()=>setOnlyAttention(v=>!v)} className={`min-h-10 rounded-xl border px-3 text-sm font-black ${onlyAttention?"border-amber-300 bg-amber-50 text-amber-900":"border-slate-200 bg-white text-slate-700"}`}>{onlyAttention?"Mostrando só pendências":"Mostrar só o que exige atenção"}</button></div>
        {error&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
        {loading&&data.items.length===0?<div className="grid min-h-32 place-items-center text-sm font-bold text-slate-500"><Loader2 className="mb-2 animate-spin"/>Carregando operações...</div>:visible.length===0?<div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-center"><CheckCircle2 className="mx-auto text-emerald-700"/><strong className="mt-2 block text-emerald-950">Nenhuma pendência nesta visão</strong><p className="mt-1 text-sm text-emerald-800">O gestor não precisa agir em nenhuma OS agora.</p></div>:<div className="mt-4 grid gap-3">{visible.map(item=><OperationCard key={item.osId} item={item} onSelect={selectOs}/>)}</div>}
      </div>
    </div>
  </section>
}

function Kpi({label,value,icon,warn=false}:{label:string;value:number;icon:React.ReactNode;warn?:boolean}){return <div className={`rounded-2xl p-3 ${warn&&value>0?"bg-amber-300/20":"bg-white/10"}`}><div className="flex items-center gap-2 text-emerald-100">{icon}<span className="text-[11px] font-bold leading-4">{label}</span></div><strong className="mt-2 block text-2xl font-black">{value}</strong></div>}
function OperationCard({item,onSelect}:{item:Item;onSelect:(item:Item,target?:string)=>void}){
  const location=[item.fazenda,item.talhao].filter(Boolean).join(" • "),sync=since(item.lastSync),stale=item.lastSync&&Date.now()-Date.parse(item.lastSync)>10*60*1000;
  const closeTarget=["regularizacao","pronta_encerrar","encerrada"].includes(item.stage)?`/apps/dronegestor/pacote-operacao?osId=${encodeURIComponent(item.osId)}`:"";
  const actionTarget=item.stage==="aguardando_sarpas"?`/apps/dronegestor/documentos?osId=${encodeURIComponent(item.osId)}`:closeTarget||undefined;
  const actionLabel=item.stage==="aguardando_sarpas"?"Resolver SARPAS":item.stage==="regularizacao"?"Regularizar esta OS":item.stage==="pronta_encerrar"?"Encerrar esta OS":item.stage==="encerrada"?"Ver fechamento":"Ver detalhes";
  return <article className="rounded-[22px] border border-slate-200 bg-[#fcfdfc] p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-base font-black text-slate-950">{item.numero}</strong><span className={`rounded-full border px-2.5 py-1 text-[11px] font-black ${tone(item.stage)}`}>{item.stageLabel}</span></div><p className="mt-1 text-sm font-semibold text-slate-700">{location}</p><p className="mt-1 text-xs text-slate-500">{item.cliente}{item.cultura?` • ${item.cultura}`:""}{item.alvo?` • ${item.alvo}`:""}</p></div><div className="text-right"><span className="inline-flex items-center gap-1 text-xs font-bold text-slate-600"><UserRound size={14}/>{item.pilotName}</span><span className={`mt-1 flex items-center justify-end gap-1 text-[11px] font-bold ${stale?"text-amber-700":"text-slate-400"}`}><Clock3 size={13}/>{sync}</span></div></div>
    {(item.stage==="aplicando"||item.stage==="pausada")&&<div className="mt-4 rounded-2xl bg-slate-50 p-3"><div className="flex items-end justify-between gap-3"><div><span className="text-xs text-slate-500">Progresso informado pelo aparelho</span><strong className="mt-1 block text-xl text-slate-950">{fmt(item.percent,0)}%</strong></div><span className="text-xs font-bold text-slate-600">{fmt(item.progressHa,2)} / {fmt(item.areaHa,2)} ha</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-600" style={{width:`${Math.max(0,Math.min(100,item.percent))}%`}}/></div><p className="mt-2 text-xs text-slate-500">{item.tanks} carga(s) • {item.occurrences} ocorrência(s)</p></div>}
    <div className={`mt-4 rounded-2xl border p-3 ${attention(item.stage)?"border-amber-200 bg-amber-50":"border-emerald-100 bg-emerald-50"}`}><span className="text-[11px] font-black uppercase tracking-wider text-slate-500">Próxima ação</span><strong className="mt-1 block text-sm text-slate-950">{item.nextAction}</strong>{item.pending.length>1&&<p className="mt-1 text-xs text-slate-600">+ {item.pending.length-1} outra(s) pendência(s) registrada(s)</p>}</div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>onSelect(item)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-black text-slate-700"><ClipboardList size={17}/>Gerenciar esta OS</button><button type="button" onClick={()=>onSelect(item,actionTarget)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-3 text-sm font-black text-white">{actionLabel} <ChevronRight size={17}/></button></div>
  </article>
}
