"use client";

import { ShieldAlert, X } from "lucide-react";
import { useEffect, useState } from "react";

type Permissions={executarOs:boolean;editarParametros:boolean;editarSeguranca:boolean;registrarSarpas:boolean;anexarEvidencias:boolean;finalizarOperacao:boolean;verRelatorios:boolean};
type Pilot={usuarioId?:string;nome?:string;permissoes?:Permissions};
const full:Permissions={executarOs:true,editarParametros:true,editarSeguranca:true,registrarSarpas:true,anexarEvidencias:true,finalizarOperacao:true,verRelatorios:true};

export function DronePilotPermissionBridge({currentUserId,canManage}:{currentUserId:string;canManage:boolean}){
  const[permissions,setPermissions]=useState<Permissions>(full),[pilotName,setPilotName]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{if(canManage)return;fetch("/api/dronegestor/pilotos",{cache:"no-store"}).then(async response=>{const payload=await response.json().catch(()=>null);if(!response.ok)return;const pilot=(payload?.items??[] as Pilot[]).find((item:Pilot)=>item.usuarioId===currentUserId);if(pilot?.permissoes){setPermissions({...full,...pilot.permissoes});setPilotName(String(pilot.nome||"Piloto"))}}).catch(()=>undefined)},[canManage,currentUserId]);
  useEffect(()=>{if(canManage)return;const warn=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(""),4200)};const stop=(event:Event,text:string)=>{event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();warn(text)};const guard=(event:Event)=>{const element=event.target instanceof Element?event.target:null;if(!element)return;const view=localStorage.getItem("dronegestor:view:v3")||"inicio",interactive=element.closest("input,select,textarea,button,a") as HTMLElement|null;if(!interactive)return;const text=(interactive.textContent||interactive.getAttribute("aria-label")||"").trim();if(!permissions.anexarEvidencias&&(interactive.getAttribute("aria-label")==="Registrar mapa usado no voo"||interactive.closest("[aria-label='Registrar mapa usado no voo']")))return stop(event,"O gestor não liberou envio de evidências para este piloto.");if(!permissions.executarOs&&((view==="sarpas"&&text.includes("Iniciar operação"))||view==="execucao"))return stop(event,"O gestor não liberou a execução de OS para este piloto.");if(view==="nova"&&!permissions.editarParametros){const field=interactive.matches("input,select,textarea"),editButton=text.includes("Adicionar produto")||text.includes("Remover");if(field||editButton)return stop(event,"Parâmetros técnicos estão em somente leitura para este piloto.")};if(view==="seguranca"&&!permissions.editarSeguranca){const field=interactive.matches("input,select,textarea"),confirm=text.includes("Confirmar medição")||text.includes("Confirmar análise de risco");if(field||confirm)return stop(event,"O gestor não liberou alterações na etapa de Segurança.")};if(view==="sarpas"&&!permissions.registrarSarpas&&interactive.matches("input,select,textarea"))return stop(event,"O gestor não liberou registro de SARPAS para este piloto.");if(view==="execucao"&&!permissions.finalizarOperacao&&text.includes("Concluir e salvar"))return stop(event,"O gestor não liberou a finalização da operação para este piloto.");if(view==="relatorios"&&!permissions.verRelatorios&&(text.includes("Rascunho da operação")||text.includes("Dados operacionais CSV")||text.includes("Abrir histórico")))return stop(event,"O gestor não liberou relatórios para este piloto.")};document.addEventListener("click",guard,true);document.addEventListener("input",guard,true);document.addEventListener("change",guard,true);return()=>{document.removeEventListener("click",guard,true);document.removeEventListener("input",guard,true);document.removeEventListener("change",guard,true)}},[canManage,permissions]);
  if(canManage||!pilotName)return null;
  return <>{notice&&<div className="fixed left-3 right-3 top-3 z-[160] mx-auto flex max-w-md items-start gap-2 rounded-2xl border border-amber-300 bg-amber-50 p-3 text-amber-950 shadow-xl"><ShieldAlert size={18} className="mt-0.5 shrink-0"/><div className="min-w-0 flex-1"><strong className="block text-xs">Ação não autorizada</strong><p className="mt-0.5 text-xs leading-4">{notice}</p></div><button type="button" onClick={()=>setNotice("")} className="grid size-7 place-items-center rounded-full text-amber-800" aria-label="Fechar aviso"><X size={15}/></button></div>}</>
}
