"use client";

import { AlertTriangle, ArrowLeft, Calculator, Check, ChevronRight, ClipboardCheck, CloudSun, Compass, Drone, Droplets, FileSpreadsheet, FileText, Gauge, Home, Map, Pause, Play, RotateCcw, Route, Settings2, ShieldCheck, Sparkles, Sprout, Target, TimerReset, Wind, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { snapshotDroneLocalState } from "./DronePersistenceSync";

type View = "inicio"|"nova"|"calda"|"estrategia"|"seguranca"|"controle"|"calibracao"|"checklist"|"sarpas"|"execucao"|"relatorios"|"config";
type DoseUnit = "mL/ha"|"L/ha"|"g/ha"|"kg/ha"|"mL/100L"|"g/100L";
type SarpasStatus = ""|"autorizado"|"dispensado"|"nao_aplicavel";
type Product = { id:string; nome:string; dose:number; unidade:DoseUnit };
type CalibrationState = { ar:boolean; fluxometro:boolean; bomba:boolean };
type ChecklistState = { area:boolean; pessoasAnimais:boolean; obstaculos:boolean; drone:boolean; controle:boolean; pulverizacao:boolean; clima:boolean; documentos:boolean };
type CompanySettings = { insightsObrigatorios:boolean; margemPreventiva:number; bloquearMargemPreventiva:boolean; exigirConfirmacao:boolean; protocoloBordaduraCigarrinha:boolean };
type ModelWeather = { latitude:number; longitude:number; capturedAt:string; temperature:number; humidity:number; windSpeed:number; windDirection:number; windGust:number; precipitation:number };
type Occurrence = { id:string; at:string; text:string };
type Mission = {
  cultura:string; alvo:string; tipoAtividade:string; area:number; drone:string; identificacaoAnac:string; pontaPulverizacao:string;
  volume:number; tanque:number; faixa:number; velocidadeKmh:number; alturaM:number; produtos:Product[];
  distanciaSensivel:number; semAreaSensivel:boolean; ventoCampoKmh:number; ventoCampoMedido:boolean; direcaoVentoCampo:string; temperaturaCampo:number; umidadeCampo:number;
  climaCampoConfirmado:boolean; climaCampoMedidoEm:string; tempoAbastecimentoMin:number; tempoTrocaBateriaMin:number; tanquesPorBateria:number;
  tempoDeslocamentoMin:number; tempoBordaduraMin:number; sarpasNumero:string; sarpasSituacao:SarpasStatus; sarpasConfirmado:boolean;
  documentoTecnicoReferencia:string;
  ordemServicoId?:string; ordemServicoNumero?:string; clienteId?:string; clienteNome?:string; fazendaId?:string; fazendaNome?:string; municipio?:string; uf?:string; talhaoId?:string; talhaoNome?:string;
};
type PendingFinalization = { operationId:string; pilotName:string; state:Record<string,unknown>; requestedAt:string; ordemServicoId?:string };

const KEYS = {
  mission:"dronegestor:mission:v2", settings:"dronegestor:settings:v2", calibration:"dronegestor:calibration:v2", checklist:"dronegestor:checklist:v2",
  occurrences:"dronegestor:occurrences:v2", weather:"dronegestor:weather", progress:"dronegestor:progress:v2", insight:"dronegestor:insightAccepted:v2",
  risk:"dronegestor:riskAccepted:v2", view:"dronegestor:view:v3", started:"dronegestor:started:v3", paused:"dronegestor:paused:v3",
  operationId:"dronegestor:operationId:v3", lastFinalized:"dronegestor:lastFinalizedOperationId:v3", finalQueue:"dronegestor:finalizationQueue:v4",
  startedAt:"dronegestor:startedAt:v4", finalizedAt:"dronegestor:finalizedAt:v4"
} as const;
const blankMission:Mission = { cultura:"", alvo:"", tipoAtividade:"Pulverização", area:0, drone:"", identificacaoAnac:"", pontaPulverizacao:"", volume:0, tanque:0, faixa:0, velocidadeKmh:0, alturaM:0,
  produtos:[{id:"produto-1",nome:"",dose:0,unidade:"mL/ha"}], distanciaSensivel:0, semAreaSensivel:false, ventoCampoKmh:0, ventoCampoMedido:false, direcaoVentoCampo:"", temperaturaCampo:0, umidadeCampo:0,
  climaCampoConfirmado:false, climaCampoMedidoEm:"", tempoAbastecimentoMin:0, tempoTrocaBateriaMin:0, tanquesPorBateria:0, tempoDeslocamentoMin:0, tempoBordaduraMin:0,
  sarpasNumero:"", sarpasSituacao:"", sarpasConfirmado:false, documentoTecnicoReferencia:"" };
const defaultSettings:CompanySettings = { insightsObrigatorios:true, margemPreventiva:90, bloquearMargemPreventiva:true, exigirConfirmacao:true, protocoloBordaduraCigarrinha:false };
const blankCalibration:CalibrationState = { ar:false, fluxometro:false, bomba:false };
const blankChecklist:ChecklistState = { area:false,pessoasAnimais:false,obstaculos:false,drone:false,controle:false,pulverizacao:false,clima:false,documentos:false };
const flow:View[] = ["nova","calda","estrategia","seguranca","controle","calibracao","checklist","sarpas","execucao","relatorios"];

function raw<T>(key:string,fallback:T):T{try{const v=localStorage.getItem(key);return v?JSON.parse(v) as T:fallback}catch{return fallback}}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function round(v:number,d=2){const f=10**d;return Math.round(v*f)/f}
function fmt(v:number,d=1){return new Intl.NumberFormat("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number.isFinite(v)?v:0)}
function duration(h:number){if(!h||h<=0)return "—";const m=Math.round(h*60);return `${Math.floor(m/60)}h${String(m%60).padStart(2,"0")}`}
function id(prefix:string){return typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function normalizeMission(v:Partial<Mission>|null):Mission{const produtos=Array.isArray(v?.produtos)&&v!.produtos!.length?v!.produtos!:blankMission.produtos;return {...blankMission,...(v??{}),produtos}}
function human(v:number,u:string){return u==="mL"&&v>=1000?{value:v/1000,unit:"L"}:u==="g"&&v>=1000?{value:v/1000,unit:"kg"}:{value:v,unit:u}}
function productAmount(p:Product,area:number,totalCalda:number,areaTank:number,tank:number,lastTank:number,volume:number){const dose=n(p.dose);let total=0;let full=0;let last=0;let unit="";const lastArea=volume>0?lastTank/volume:0;
  if(p.unidade==="mL/ha"){total=area*dose;full=areaTank*dose;last=lastArea*dose;unit="mL"} if(p.unidade==="L/ha"){total=area*dose;full=areaTank*dose;last=lastArea*dose;unit="L"}
  if(p.unidade==="g/ha"){total=area*dose;full=areaTank*dose;last=lastArea*dose;unit="g"} if(p.unidade==="kg/ha"){total=area*dose;full=areaTank*dose;last=lastArea*dose;unit="kg"}
  if(p.unidade==="mL/100L"){total=totalCalda/100*dose;full=tank/100*dose;last=lastTank/100*dose;unit="mL"} if(p.unidade==="g/100L"){total=totalCalda/100*dose;full=tank/100*dose;last=lastTank/100*dose;unit="g"}
  return {total:human(total,unit),full:human(full,unit),last:human(last,unit)} }
function protocolFor(target:string,s:CompanySettings){const active=target.toLowerCase().includes("cigarrinha")&&s.protocoloBordaduraCigarrinha;return {gota:"Definir pelo protocolo validado",janela:"Cruzar clima, bula e protocolo",strategy:active?"Padrão interno: bordadura → interior.":"Usar o protocolo técnico aprovado para cultura, alvo e produto.",note:active?"Protocolo interno ativo. Confirme produto, estágio, clima e talhão.":"O sistema não inventa dose, gota ou estratégia. Use receita, bula e orientação técnica.",active}}

export function DroneGestorAppV3({userName,userType,canManage}:{userName:string;userType:string;canManage:boolean}){
  const [hydrated,setHydrated]=useState(false),[view,setView]=useState<View>("inicio"),[returnView,setReturnView]=useState<View>("inicio");
  const [mission,setMission]=useState<Mission>(blankMission),[settings,setSettings]=useState<CompanySettings>(defaultSettings),[calibration,setCalibration]=useState<CalibrationState>(blankCalibration),[checklist,setChecklist]=useState<ChecklistState>(blankChecklist);
  const [insightAccepted,setInsightAccepted]=useState(false),[riskAccepted,setRiskAccepted]=useState(false),[progressHa,setProgressHa]=useState(0),[operationStarted,setOperationStarted]=useState(false),[paused,setPaused]=useState(false);
  const [modelWeather,setModelWeather]=useState<ModelWeather|null>(null),[occurrences,setOccurrences]=useState<Occurrence[]>([]),[notice,setNotice]=useState(""),[savingFinal,setSavingFinal]=useState(false),[finalSaved,setFinalSaved]=useState(false),[pendingCount,setPendingCount]=useState(0),[pendingCurrent,setPendingCurrent]=useState(false);

  useEffect(()=>{const m=normalizeMission(raw<Partial<Mission>|null>(KEYS.mission,null));setMission(m);setSettings({...defaultSettings,...raw(KEYS.settings,defaultSettings)});setCalibration(raw(KEYS.calibration,blankCalibration));setChecklist(raw(KEYS.checklist,blankChecklist));setOccurrences(raw(KEYS.occurrences,[] as Occurrence[]));setProgressHa(n(raw(KEYS.progress,0)));setInsightAccepted(Boolean(raw(KEYS.insight,false)));setRiskAccepted(Boolean(raw(KEYS.risk,false)));setOperationStarted(Boolean(raw(KEYS.started,false)));setPaused(Boolean(raw(KEYS.paused,false)));setModelWeather(raw(KEYS.weather,null as ModelWeather|null));const v=localStorage.getItem(KEYS.view) as View|null;if(v&&["inicio",...flow,"config"].includes(v))setView(v);const op=localStorage.getItem(KEYS.operationId)||"";const q=raw<PendingFinalization[]>(KEYS.finalQueue,[]);setPendingCount(q.length);setPendingCurrent(Boolean(op&&q.some(x=>x.operationId===op)));setFinalSaved(Boolean(op&&localStorage.getItem(KEYS.lastFinalized)===op));setHydrated(true)},[]);
  useEffect(()=>{if(!hydrated)return;localStorage.setItem(KEYS.mission,JSON.stringify(mission));localStorage.setItem(KEYS.settings,JSON.stringify(settings));localStorage.setItem(KEYS.calibration,JSON.stringify(calibration));localStorage.setItem(KEYS.checklist,JSON.stringify(checklist));localStorage.setItem(KEYS.occurrences,JSON.stringify(occurrences));localStorage.setItem(KEYS.progress,JSON.stringify(progressHa));localStorage.setItem(KEYS.insight,JSON.stringify(insightAccepted));localStorage.setItem(KEYS.risk,JSON.stringify(riskAccepted));localStorage.setItem(KEYS.started,JSON.stringify(operationStarted));localStorage.setItem(KEYS.paused,JSON.stringify(paused));localStorage.setItem(KEYS.view,view)},[hydrated,mission,settings,calibration,checklist,occurrences,progressHa,insightAccepted,riskAccepted,operationStarted,paused,view]);
  useEffect(()=>{if(!hydrated)return;void fetch("/api/dronegestor/config",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(p=>{if(p?.settings)setSettings({...defaultSettings,...p.settings})}).catch(()=>null)},[hydrated]);
  useEffect(()=>{const fn=(e:Event)=>{const c=e as CustomEvent<ModelWeather>;if(c.detail)setModelWeather(c.detail)};window.addEventListener("dronegestor:weather-updated",fn);return()=>window.removeEventListener("dronegestor:weather-updated",fn)},[]);

  const calc=useMemo(()=>{const totalCalda=mission.area>0&&mission.volume>0?mission.area*mission.volume:0;const areaTank=mission.volume>0&&mission.tanque>0?mission.tanque/mission.volume:0;const exact=mission.tanque>0?totalCalda/mission.tanque:0;const tanks=exact>0?Math.ceil(exact):0;const rem=tanks?totalCalda-Math.floor(exact)*mission.tanque:0;const lastTank=tanks?(rem>0?rem:mission.tanque):0;const speedMs=mission.velocidadeKmh>0?mission.velocidadeKmh/3.6:0;const flowLMin=mission.volume>0&&mission.velocidadeKmh>0&&mission.faixa>0?mission.volume*mission.velocidadeKmh*mission.faixa/600:0;const haH=mission.velocidadeKmh>0&&mission.faixa>0?mission.velocidadeKmh*mission.faixa/10:0;const sprayHours=haH>0?mission.area/haH:0;const refills=Math.max(0,tanks-1);const batteryChanges=mission.tanquesPorBateria>0&&tanks>0?Math.floor((tanks-1)/mission.tanquesPorBateria):0;const stopsMin=refills*Math.max(0,mission.tempoAbastecimentoMin)+batteryChanges*Math.max(0,mission.tempoTrocaBateriaMin)+Math.max(0,mission.tempoDeslocamentoMin)+Math.max(0,mission.tempoBordaduraMin);const estimatedHours=sprayHours>0?sprayHours+stopsMin/60:0;const products=mission.produtos.map(product=>({product,amount:productAmount(product,mission.area,totalCalda,areaTank,mission.tanque,lastTank,mission.volume)}));return{totalCalda,areaTank,tanks,lastTank,speedMs,flowLMin,haH,estimatedHours,products}},[mission]);
  const protocol=useMemo(()=>protocolFor(mission.alvo,settings),[mission.alvo,settings]);
  const productsReady=mission.produtos.length>0&&mission.produtos.every(p=>p.nome.trim()&&p.dose>0&&p.unidade);
  const missionReady=Boolean(mission.cultura.trim()&&mission.alvo.trim()&&mission.tipoAtividade.trim()&&mission.drone.trim()&&mission.identificacaoAnac.trim()&&mission.pontaPulverizacao.trim()&&mission.documentoTecnicoReferencia.trim()&&mission.area>0&&mission.volume>0&&mission.tanque>0&&mission.faixa>0&&mission.velocidadeKmh>0&&mission.alturaM>0&&productsReady);
  const sensitiveReady=mission.semAreaSensivel||mission.distanciaSensivel>0;
  const marginReady=!settings.bloquearMargemPreventiva||mission.semAreaSensivel||mission.distanciaSensivel>=settings.margemPreventiva;
  const weatherPlausible=mission.ventoCampoMedido&&mission.ventoCampoKmh>=0&&mission.ventoCampoKmh<=100&&mission.direcaoVentoCampo.trim()&&mission.temperaturaCampo>=-20&&mission.temperaturaCampo<=60&&mission.umidadeCampo>0&&mission.umidadeCampo<=100;
  const weatherReady=Boolean(mission.climaCampoConfirmado&&weatherPlausible);
  const preliminarySafety=sensitiveReady&&marginReady&&weatherReady&&(!settings.insightsObrigatorios||insightAccepted);
  const safetyReady=Boolean(preliminarySafety&&(!settings.exigirConfirmacao||riskAccepted));
  const calibrationReady=calibration.ar&&calibration.fluxometro&&calibration.bomba, checklistReady=Object.values(checklist).every(Boolean);
  const sarpasReady=mission.sarpasConfirmado&&Boolean(mission.sarpasSituacao)&&(mission.sarpasSituacao!=="autorizado"||mission.sarpasNumero.trim().length>0);
  const frozen=finalSaved||pendingCurrent;
  const canStart=missionReady&&safetyReady&&calibrationReady&&checklistReady&&sarpasReady&&!frozen;
  const areaDone=mission.area>0&&progressHa>=mission.area-0.01;

  function flash(t:string){setNotice(t);window.setTimeout(()=>setNotice(""),3600)} function go(v:View){setView(v);window.scrollTo({top:0,behavior:"smooth"})}
  function resumeView():View{if(frozen)return"relatorios";if(operationStarted)return"execucao";if(!missionReady)return"nova";if(settings.insightsObrigatorios&&!insightAccepted)return"estrategia";if(!safetyReady)return"seguranca";if(!calibrationReady)return"calibracao";if(!checklistReady)return"checklist";return"sarpas"}
  function guarded(t:View){if(frozen&&!["relatorios","inicio"].includes(t)){flash(pendingCurrent?"Esta missão já foi concluída no aparelho e aguarda sincronização.":"Esta missão já foi finalizada. Inicie uma nova aplicação para voar novamente.");return go("relatorios")}if(t==="nova")return go("nova");if(["calda","estrategia"].includes(t)&&!missionReady){flash("Complete os dados obrigatórios da missão primeiro.");return go("nova")}if(t==="seguranca"&&(!missionReady||(settings.insightsObrigatorios&&!insightAccepted))){flash("Conclua a missão e a estratégia antes da segurança.");return go(resumeView())}if(["controle","calibracao"].includes(t)&&!safetyReady){flash("Conclua a análise de segurança antes dos parâmetros e da calibração.");return go(resumeView())}if(t==="checklist"&&!calibrationReady){flash("Conclua a calibração antes do checklist.");return go("calibracao")}if(t==="sarpas"&&!checklistReady){flash("Conclua o checklist antes do SARPAS.");return go(resumeView())}if(t==="execucao"&&!operationStarted){flash("Inicie a operação pela etapa SARPAS.");return go("sarpas")}go(t)}
  function back(){if(view==="inicio")return;if(view==="config")return go(returnView);if(view==="execucao"&&operationStarted)return go("inicio");if(view==="relatorios")return go("inicio");const i=flow.indexOf(view);go(i<=0?"inicio":flow[i-1])}
  function editable(){if(operationStarted){flash("A operação já começou. Parâmetros e confirmações ficam somente leitura.");return false}if(frozen){flash("Missão concluída não pode ser alterada.");return false}return true}
  function invalidateCore(){setInsightAccepted(false);setRiskAccepted(false);setCalibration(blankCalibration);setChecklist(blankChecklist);setMission(c=>({...c,sarpasConfirmado:false,sarpasSituacao:"",sarpasNumero:""}))}
  function updateMission<K extends keyof Mission>(key:K,value:Mission[K]){if(!editable())return;const core:Array<keyof Mission>=["cultura","alvo","tipoAtividade","area","drone","identificacaoAnac","pontaPulverizacao","documentoTecnicoReferencia","volume","tanque","faixa","velocidadeKmh","alturaM"];const safety:Array<keyof Mission>=["distanciaSensivel","semAreaSensivel","ventoCampoKmh","ventoCampoMedido","direcaoVentoCampo","temperaturaCampo","umidadeCampo"];setMission(c=>{const x={...c,[key]:value} as Mission;if(core.includes(key)){x.sarpasConfirmado=false;x.sarpasSituacao="";x.sarpasNumero=""}if(safety.includes(key)){x.climaCampoConfirmado=false;x.climaCampoMedidoEm=""}return x});if(core.includes(key)){setInsightAccepted(false);setRiskAccepted(false);setCalibration(blankCalibration);setChecklist(blankChecklist)}if(safety.includes(key)){setRiskAccepted(false);setChecklist(c=>({...c,clima:false}))}}
  function updateProduct(pid:string,patch:Partial<Product>){if(!editable())return;setMission(c=>({...c,produtos:c.produtos.map(p=>p.id===pid?{...p,...patch}:p),sarpasConfirmado:false,sarpasSituacao:"",sarpasNumero:""}));setInsightAccepted(false);setRiskAccepted(false);setCalibration(blankCalibration);setChecklist(blankChecklist)}
  function addProduct(){if(!editable())return;setMission(c=>({...c,produtos:[...c.produtos,{id:id("produto"),nome:"",dose:0,unidade:"mL/ha"}]}));invalidateCore()} function removeProduct(pid:string){if(!editable())return;setMission(c=>({...c,produtos:c.produtos.length<=1?c.produtos:c.produtos.filter(p=>p.id!==pid)}));invalidateCore()}
  function confirmClimate(){if(!editable())return;if(!mission.ventoCampoMedido)return flash("Confirme que a velocidade do vento foi realmente medida no talhão.");if(!weatherPlausible)return flash("Revise vento, direção, temperatura e umidade. Há campo ausente ou valor fora da faixa plausível.");if(!sensitiveReady)return flash("Informe a distância da área sensível ou marque que não há área sensível aplicável.");if(!marginReady)return flash(`Distância abaixo da margem preventiva interna de ${settings.margemPreventiva} m. A operação permanece bloqueada.`);setMission(c=>({...c,climaCampoConfirmado:true,climaCampoMedidoEm:new Date().toISOString()}));setChecklist(c=>({...c,clima:true}));setRiskAccepted(false);flash("Medição de campo registrada. Faça a confirmação final de risco.")}
  async function releaseOrder(){if(!mission.ordemServicoId)return true;try{const r=await fetch("/api/dronegestor/cadastros",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"os",entityId:mission.ordemServicoId,data:{status:"aberta"}}),cache:"no-store"});return r.ok}catch{return false}}
  async function resetMission(){if(operationStarted)return flash("Existe uma operação em andamento. Pause/retome e conclua antes de trocar de missão.");if(!frozen&&mission.ordemServicoId&&!(await releaseOrder()))return flash("Não foi possível liberar a OS atual. Conecte-se à internet e tente novamente antes de trocar de missão.");if(!window.confirm(frozen?"Arquivar esta missão no aparelho e iniciar uma nova aplicação?":"Limpar a missão atual e iniciar uma nova aplicação?"))return;const b=normalizeMission(null);setMission(b);setCalibration(blankCalibration);setChecklist(blankChecklist);setInsightAccepted(false);setRiskAccepted(false);setProgressHa(0);setPaused(false);setOccurrences([]);setFinalSaved(false);setPendingCurrent(false);localStorage.removeItem(KEYS.operationId);localStorage.removeItem(KEYS.lastFinalized);localStorage.removeItem(KEYS.startedAt);localStorage.removeItem(KEYS.finalizedAt);go("nova")}
  async function patchOs(status:string){if(!mission.ordemServicoId)return true;const r=await fetch("/api/dronegestor/cadastros",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"os",entityId:mission.ordemServicoId,data:{status}}),cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok){flash(p?.error||"Não foi possível atualizar a OS.");return false}return true}
  async function startOperation(){if(frozen)return flash("Esta missão já foi concluída.");if(!canStart)return flash("Ainda existem etapas obrigatórias pendentes.");if(!(await patchOs("em_execucao")))return;let op=localStorage.getItem(KEYS.operationId)||"";if(!op){op=id("op");localStorage.setItem(KEYS.operationId,op)}localStorage.setItem(KEYS.startedAt,new Date().toISOString());setOperationStarted(true);setPaused(false);setFinalSaved(false);go("execucao")}
  async function togglePause(){if(!operationStarted)return;const next=!paused;if(!(await patchOs(next?"suspensa":"em_execucao")))return;setPaused(next);flash(next?"Operação suspensa. O progresso foi preservado.":"Operação retomada.")}
  function recordTankArea(){if(paused)return flash("Retome a operação antes de registrar área executada.");const remaining=Math.max(0,mission.area-progressHa);const text=window.prompt(`Informe a área REAL executada neste tanque (ha). Restante planejado: ${fmt(remaining,2)} ha.`,String(round(Math.min(calc.areaTank,remaining),2)));if(text===null)return;const value=n(text.replace(",","."));if(value<=0||value>remaining+0.01)return flash("Informe uma área válida, maior que zero e não superior ao restante planejado.");const next=Math.min(mission.area,round(progressHa+value,2));setProgressHa(next);flash(next>=mission.area?"100% da área planejada registrada.":`Área real acumulada: ${fmt(next,2)} ha.`)}
  function correctProgress(){const text=window.prompt(`Informe o total REAL já executado (0 a ${fmt(mission.area,2)} ha).`,String(progressHa));if(text===null)return;const value=n(text.replace(",","."));if(value<0||value>mission.area+0.01)return flash("Total de área inválido.");setProgressHa(round(Math.min(value,mission.area),2));flash("Área real acumulada corrigida.")}
  function addOccurrence(){const text=window.prompt("Descreva a ocorrência observada em campo:");if(!text?.trim())return;setOccurrences(c=>[...c,{id:id("oc"),at:new Date().toISOString(),text:text.trim()}]);flash("Ocorrência registrada.")}
  async function sendFinalization(payload:PendingFinalization){const r=await fetch("/api/dronegestor/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:payload.state,operationId:payload.operationId,pilotName:payload.pilotName}),cache:"no-store",keepalive:true});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Não foi possível registrar a operação.");return p}
  async function retryQueue(){if(!navigator.onLine)return;const q=raw<PendingFinalization[]>(KEYS.finalQueue,[]);if(!q.length){setPendingCount(0);return}const rest:PendingFinalization[]=[];for(const item of q){try{await sendFinalization(item);localStorage.setItem(KEYS.lastFinalized,item.operationId);if(localStorage.getItem(KEYS.operationId)===item.operationId){setFinalSaved(true);setPendingCurrent(false)}}catch{rest.push(item)}}localStorage.setItem(KEYS.finalQueue,JSON.stringify(rest));setPendingCount(rest.length)}
  useEffect(()=>{if(!hydrated)return;void retryQueue();const fn=()=>void retryQueue();window.addEventListener("online",fn);return()=>window.removeEventListener("online",fn)},[hydrated]);
  async function finalizeOperation(){if(!operationStarted||!areaDone||!canStart||savingFinal||frozen)return flash("A conclusão só é liberada depois de 100% da área real registrada e de todas as validações obrigatórias.");if(!window.confirm(`Confirmar conclusão de ${fmt(progressHa,2)} ha e salvar definitivamente?`))return;const operationId=localStorage.getItem(KEYS.operationId)||id("op");localStorage.setItem(KEYS.operationId,operationId);const finalizedAt=new Date().toISOString();localStorage.setItem(KEYS.finalizedAt,finalizedAt);const state=snapshotDroneLocalState() as Record<string,unknown>;state.progressHa=progressHa;state.operationStarted=false;state.concluida=true;state.concluidaNoDispositivoEm=finalizedAt;state.operationId=operationId;state.startedAt=localStorage.getItem(KEYS.startedAt)||"";state.finalizedAt=finalizedAt;state.progressSource="manual_campo";const payload:PendingFinalization={operationId,pilotName:userName,state,requestedAt:finalizedAt,ordemServicoId:mission.ordemServicoId};if(!navigator.onLine){const q=raw<PendingFinalization[]>(KEYS.finalQueue,[]);if(!q.some(x=>x.operationId===operationId))localStorage.setItem(KEYS.finalQueue,JSON.stringify([...q,payload]));setPendingCount(q.some(x=>x.operationId===operationId)?q.length:q.length+1);setPendingCurrent(true);setOperationStarted(false);setPaused(false);go("relatorios");return flash("Sem internet. A missão foi congelada e ficou protegida para sincronização.")}setSavingFinal(true);try{await sendFinalization(payload);localStorage.setItem(KEYS.lastFinalized,operationId);setFinalSaved(true);setOperationStarted(false);setPaused(false);go("relatorios");flash("Operação e OS registradas no histórico.")}catch(e){const q=raw<PendingFinalization[]>(KEYS.finalQueue,[]);if(!q.some(x=>x.operationId===operationId))localStorage.setItem(KEYS.finalQueue,JSON.stringify([...q,payload]));setPendingCount(q.some(x=>x.operationId===operationId)?q.length:q.length+1);setPendingCurrent(true);setOperationStarted(false);setPaused(false);go("relatorios");flash(e instanceof Error?`${e.message} A missão ficou congelada para nova tentativa.`:"Conclusão pendente de sincronização.")}finally{setSavingFinal(false)}}
  async function saveSettings(next:CompanySettings){if(!canManage)return flash("Somente ADMIN/RT pode alterar padrões.");const r=await fetch("/api/dronegestor/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({settings:next}),cache:"no-store"});const p=await r.json().catch(()=>null);if(!r.ok)return flash(p?.error||"Não foi possível salvar.");setSettings(next);setInsightAccepted(false);setRiskAccepted(false);setChecklist(c=>({...c,clima:false}));flash("Padrão da empresa salvo.")}
  function download(filename:string,content:string,type="text/plain;charset=utf-8"){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
  function exportDraft(){const lines=["DRONEGESTOR AGRO - RASCUNHO","Não substitui envio oficial, receituário, bula ou RT.",`OS: ${mission.ordemServicoNumero||"—"}`,`Cliente: ${mission.clienteNome||"—"}`,`Fazenda/Talhão: ${[mission.fazendaNome,mission.talhaoNome].filter(Boolean).join(" / ")||"—"}`,`Cultura: ${mission.cultura}`,`Alvo: ${mission.alvo}`,`Atividade: ${mission.tipoAtividade}`,`Área planejada: ${mission.area} ha`,`Área real registrada: ${progressHa} ha`,`Drone: ${mission.drone}`,`Identificação ANAC: ${mission.identificacaoAnac}`,`Ponta/atomizador: ${mission.pontaPulverizacao}`,`Documento técnico: ${mission.documentoTecnicoReferencia}`,`SARPAS: ${mission.sarpasSituacao} ${mission.sarpasNumero}`,`Ocorrências: ${occurrences.length}`];download("dronegestor-rascunho.txt",lines.join("\n"))}

  const title:Record<View,string>={inicio:"Copiloto de aplicação",nova:"Dados da aplicação",calda:"Cálculo de calda",estrategia:"Estratégia e insight",seguranca:"Mapa e segurança",controle:"Parâmetros do controle",calibracao:"Calibração",checklist:"Checklist pré-voo",sarpas:"SARPAS",execucao:"Operação em andamento",relatorios:"Dados e relatórios",config:"Configurações da empresa"};
  if(!hydrated)return <main className="min-h-screen bg-emerald-950 grid place-items-center text-emerald-100"><div>Carregando DroneGestor...</div></main>;
  return <main className="min-h-screen bg-[linear-gradient(180deg,#052e16_0%,#064e3b_22%,#f8fafc_22%,#f8fafc_100%)] px-3 py-4"><div className="mx-auto w-full max-w-3xl overflow-hidden rounded-[30px] border border-emerald-200 bg-white shadow-2xl">
    <header className="sticky top-0 z-30 flex items-center gap-3 border-b border-emerald-100 bg-white/95 px-4 py-3"><button className="grid size-10 place-items-center rounded-xl border" onClick={back}>{view==="inicio"?<Home size={20}/>:<ArrowLeft size={20}/>}</button><div className="min-w-0 flex-1"><span className="block truncate text-[11px] font-black uppercase text-emerald-700">{view==="inicio"?`Olá, ${userName.split(" ")[0]}`:"DroneGestor Agro"}</span><strong>{title[view]}</strong></div><button className="grid size-10 place-items-center rounded-xl border" onClick={()=>{if(operationStarted||frozen)return flash("Configurações ficam bloqueadas para missão iniciada/concluída.");setReturnView(view);go("config")}}><Settings2 size={20}/></button></header>
    {pendingCount>0&&<div className="mx-4 mt-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900">{pendingCount} conclusão(ões) aguardando sincronização. A fila não é apagada por nova missão.</div>}{notice&&<div className="mx-4 mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-900">{notice}</div>}
    <div className="grid gap-4 p-4 pb-24 sm:p-6 sm:pb-24">
      {view==="inicio"&&<><div className="grid grid-cols-2 gap-3 rounded-3xl bg-gradient-to-br from-emerald-950 to-emerald-800 p-4 text-white"><Metric icon={<CloudSun/>} label="Modelo meteorológico" value={modelWeather?`${fmt(modelWeather.temperature,1)}°C`:"—"} dark/><Metric icon={<Wind/>} label="Vento modelo 10 m" value={modelWeather?`${fmt(modelWeather.windSpeed,1)} km/h`:"—"} dark/></div>{mission.ordemServicoId&&<Info>{mission.ordemServicoNumero||"OS vinculada"} • {[mission.clienteNome,mission.fazendaNome,mission.talhaoNome].filter(Boolean).join(" • ")}</Info>}{frozen&&<Warning>{pendingCurrent?"Esta missão foi concluída no aparelho e está congelada até sincronizar.":"Esta missão foi finalizada e está somente para consulta."}</Warning>}<CardButton icon={<Drone/>} title={frozen?"Ver operação concluída":mission.area>0?"Retomar operação":"Nova operação"} text={frozen?"Abra os dados ou inicie uma nova aplicação.":mission.area>0?`${fmt(mission.area,1)} ha • ${mission.cultura||"cultura pendente"}`:"Comece pelos dados reais."} onClick={()=>guarded(resumeView())} primary/><div className="grid gap-3 sm:grid-cols-2"><CardButton icon={<Droplets/>} title="Calcular calda" text="Somente com missão completa." onClick={()=>guarded("calda")}/><CardButton icon={<Map/>} title="Mapa e segurança" text="Medição de campo e margem interna." onClick={()=>guarded("seguranca")}/><CardButton icon={<FileText/>} title="Dados / rascunho" text="Consulta e exportação." onClick={()=>go("relatorios")}/><CardButton icon={<RotateCcw/>} title="Nova aplicação" text="Preserva conclusões offline." onClick={()=>void resetMission()}/></div><Info>Sincronização ativa com controle de revisão no Supabase. SARPAS/MAPA oficiais continuam separados.</Info></>}
      {view==="nova"&&<><Title icon={<Sprout/>} title="Dados da aplicação" text="Alterações antes do voo invalidam confirmações dependentes."/><FormGrid><TextField label="Cultura *" value={mission.cultura} onChange={v=>updateMission("cultura",v)}/><TextField label="Alvo *" value={mission.alvo} onChange={v=>updateMission("alvo",v)}/><TextField label="Tipo de atividade *" value={mission.tipoAtividade} onChange={v=>updateMission("tipoAtividade",v)}/><NumberField label="Área *" value={mission.area} suffix="ha" onChange={v=>updateMission("area",v)}/><TextField label="Drone *" value={mission.drone} onChange={v=>updateMission("drone",v)}/><TextField label="Identificação ANAC *" value={mission.identificacaoAnac} onChange={v=>updateMission("identificacaoAnac",v)}/><TextField label="Ponta / atomizador *" value={mission.pontaPulverizacao} onChange={v=>updateMission("pontaPulverizacao",v)}/><TextField label="Receita / protocolo / RT *" value={mission.documentoTecnicoReferencia} onChange={v=>updateMission("documentoTecnicoReferencia",v)}/><NumberField label="Volume *" value={mission.volume} suffix="L/ha" onChange={v=>updateMission("volume",v)}/><NumberField label="Tanque *" value={mission.tanque} suffix="L" onChange={v=>updateMission("tanque",v)}/><NumberField label="Faixa *" value={mission.faixa} suffix="m" onChange={v=>updateMission("faixa",v)}/><NumberField label="Velocidade *" value={mission.velocidadeKmh} suffix="km/h" onChange={v=>updateMission("velocidadeKmh",v)}/><NumberField label="Altura *" value={mission.alturaM} suffix="m" onChange={v=>updateMission("alturaM",v)}/></FormGrid><Title icon={<Droplets/>} title="Produtos" text="Todos os itens adicionados precisam estar completos."/>{mission.produtos.map((p,i)=><div key={p.id} className="grid gap-3 rounded-2xl border p-4"><div className="flex justify-between"><strong>Produto {i+1}</strong>{mission.produtos.length>1&&<button className="text-red-600" onClick={()=>removeProduct(p.id)}>Remover</button>}</div><TextField label="Nome comercial *" value={p.nome} onChange={v=>updateProduct(p.id,{nome:v})}/><div className="grid grid-cols-[1fr_140px] gap-2"><NumberField label="Dose *" value={p.dose} suffix="" onChange={v=>updateProduct(p.id,{dose:v})}/><label className="grid gap-1 text-sm font-bold"><span>Unidade</span><select className="min-h-11 rounded-xl border px-3" value={p.unidade} onChange={e=>updateProduct(p.id,{unidade:e.target.value as DoseUnit})}>{["mL/ha","L/ha","g/ha","kg/ha","mL/100L","g/100L"].map(u=><option key={u}>{u}</option>)}</select></label></div></div>)}<button className="min-h-11 rounded-xl border border-emerald-300 bg-emerald-50 font-black text-emerald-800" onClick={addProduct}>+ Adicionar produto</button><Primary disabled={!missionReady} onClick={()=>guarded("calda")}>Calcular missão <ChevronRight size={18}/></Primary></>}
      {view==="calda"&&<><Title icon={<Calculator/>} title="Cálculo de calda" text="Resultado matemático; não é recomendação agronômica."/><div className="grid grid-cols-2 gap-3"><Metric icon={<Droplets/>} label="Calda total" value={`${fmt(calc.totalCalda,1)} L`}/><Metric icon={<Route/>} label="Área por tanque" value={`${fmt(calc.areaTank,2)} ha`}/><Metric icon={<RotateCcw/>} label="Tanques" value={`${calc.tanks}`} detail={`Último: ${fmt(calc.lastTank,1)} L`}/><Metric icon={<Gauge/>} label="Vazão" value={`${fmt(calc.flowLMin,2)} L/min`}/></div>{calc.products.map(({product,amount})=><div key={product.id} className="grid grid-cols-4 gap-2 rounded-2xl border p-4 text-sm"><div><small>Produto</small><strong className="block">{product.nome}</strong></div><div><small>Total</small><strong className="block">{fmt(amount.total.value,3)} {amount.total.unit}</strong></div><div><small>Tanque cheio</small><strong className="block">{fmt(amount.full.value,3)} {amount.full.unit}</strong></div><div><small>Último tanque</small><strong className="block">{fmt(amount.last.value,3)} {amount.last.unit}</strong></div></div>)}<Warning>Confirme receita, bula, compatibilidade e ordem de mistura.</Warning><Primary onClick={()=>go("estrategia")}>Ver estratégia <ChevronRight size={18}/></Primary></>}
      {view==="estrategia"&&<><Metric icon={<Target/>} label="Alvo" value={mission.alvo}/><Metric icon={<Droplets/>} label="Gota" value={protocol.gota}/><Metric icon={<Route/>} label="Estratégia" value={protocol.strategy}/><Metric icon={<TimerReset/>} label="Janela" value={protocol.janela}/><Info>{protocol.note}</Info><CheckRow disabled={operationStarted||frozen} checked={insightAccepted} onChange={setInsightAccepted} title={settings.insightsObrigatorios?"Confirmação obrigatória":"Confirmar leitura"} detail="Li e vou conferir produto, bula, receita e protocolo técnico."/><Primary disabled={settings.insightsObrigatorios&&!insightAccepted} onClick={()=>guarded("seguranca")}>Analisar segurança <ChevronRight size={18}/></Primary></>}
      {view==="seguranca"&&<><Title icon={<Map/>} title="Segurança e condição real" text="Modelo meteorológico ajuda; a liberação usa medição feita no talhão."/>{modelWeather&&<iframe title="Mapa do ponto GPS" className="h-52 w-full rounded-2xl border" src={`https://www.openstreetmap.org/export/embed.html?bbox=${modelWeather.longitude-.003}%2C${modelWeather.latitude-.003}%2C${modelWeather.longitude+.003}%2C${modelWeather.latitude+.003}&layer=mapnik&marker=${modelWeather.latitude}%2C${modelWeather.longitude}`}/>}<div className={`rounded-2xl border p-4 text-sm ${marginReady?"border-emerald-200 bg-emerald-50":"border-red-300 bg-red-50"}`}><strong>Margem preventiva interna: {settings.margemPreventiva} m</strong><p>Distância informada: {mission.semAreaSensivel?"sem área sensível aplicável":mission.distanciaSensivel?`${mission.distanciaSensivel} m`:"pendente"}</p>{!marginReady&&<p className="font-black text-red-700">BLOQUEIO INTERNO: distância abaixo do padrão da empresa.</p>}</div><FormGrid><NumberField label="Distância área sensível" value={mission.distanciaSensivel} suffix="m" onChange={v=>updateMission("distanciaSensivel",v)}/><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input disabled={operationStarted||frozen} type="checkbox" checked={mission.semAreaSensivel} onChange={e=>updateMission("semAreaSensivel",e.target.checked)}/>Não há área sensível próxima aplicável</label><NumberField label="Vento medido" value={mission.ventoCampoKmh} suffix="km/h" onChange={v=>updateMission("ventoCampoKmh",v)}/><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input disabled={operationStarted||frozen} type="checkbox" checked={mission.ventoCampoMedido} onChange={e=>updateMission("ventoCampoMedido",e.target.checked)}/>Confirmei a leitura do anemômetro</label><TextField label="Direção do vento *" value={mission.direcaoVentoCampo} onChange={v=>updateMission("direcaoVentoCampo",v)}/><NumberField label="Temperatura *" value={mission.temperaturaCampo} suffix="°C" onChange={v=>updateMission("temperaturaCampo",v)}/><NumberField label="Umidade *" value={mission.umidadeCampo} suffix="%" onChange={v=>updateMission("umidadeCampo",v)}/></FormGrid><button className="min-h-11 rounded-xl bg-slate-950 px-4 font-black text-white disabled:opacity-40" disabled={operationStarted||frozen} onClick={confirmClimate}>{mission.climaCampoConfirmado?"Medição de campo registrada":"Confirmar medição de campo"}</button><CheckRow disabled={!preliminarySafety||operationStarted||frozen} checked={riskAccepted} onChange={setRiskAccepted} title="Confirmar análise de risco" detail="Só habilita com medição de campo e margem interna atendida."/><Primary disabled={!safetyReady} onClick={()=>go("controle")}>Gerar parâmetros-base <ChevronRight size={18}/></Primary></>}
      {view==="controle"&&<><Warning>Parâmetros calculados; ainda não liberados para voo.</Warning><div className="grid grid-cols-2 gap-3"><Metric icon={<Gauge/>} label="Velocidade" value={`${fmt(calc.speedMs,1)} m/s`} detail={`${fmt(mission.velocidadeKmh,1)} km/h`}/><Metric icon={<Droplets/>} label="Volume" value={`${fmt(mission.volume,1)} L/ha`}/><Metric icon={<Route/>} label="Faixa" value={`${fmt(mission.faixa,1)} m`}/><Metric icon={<Sparkles/>} label="Vazão" value={`${fmt(calc.flowLMin,2)} L/min`}/><Metric icon={<Gauge/>} label="Capacidade teórica" value={`${fmt(calc.haH,1)} ha/h`}/><Metric icon={<TimerReset/>} label="Tempo estimado" value={duration(calc.estimatedHours)}/></div><Primary onClick={()=>go("calibracao")}>Ir para calibração <ChevronRight size={18}/></Primary></>}
      {view==="calibracao"&&<><Title icon={<Wrench/>} title="Calibração" text="Eliminar ar → fluxômetro → bomba."/><Task index="1" title="Eliminar o ar" checked={calibration.ar} disabled={operationStarted||frozen} onChange={v=>setCalibration({ar:v,fluxometro:v?calibration.fluxometro:false,bomba:v?calibration.bomba:false})}/><Task index="2" title="Calibrar fluxômetro" checked={calibration.fluxometro} disabled={!calibration.ar||operationStarted||frozen} onChange={v=>setCalibration({...calibration,fluxometro:v,bomba:v?calibration.bomba:false})}/><Task index="3" title="Calibrar bomba" checked={calibration.bomba} disabled={!calibration.fluxometro||operationStarted||frozen} onChange={v=>setCalibration({...calibration,bomba:v})}/><Primary disabled={!calibrationReady} onClick={()=>go("checklist")}>Ir para checklist <ChevronRight size={18}/></Primary></>}
      {view==="checklist"&&<><Title icon={<ClipboardCheck/>} title="Checklist pré-voo" text={`${Object.values(checklist).filter(Boolean).length} de 8 itens.`}/>{([['area','Área e decolagem'],['pessoasAnimais','Pessoas e animais'],['obstaculos','Obstáculos e rede elétrica'],['drone','Drone'],['controle','Controle e navegação'],['pulverizacao','Pulverização'],['clima','Medição climática'],['documentos','Documentos']] as Array<[keyof ChecklistState,string]>).map(([k,t],i)=><Task key={k} index={String(i+1)} title={t} checked={checklist[k]} disabled={k==='clima'||operationStarted||frozen} onChange={v=>setChecklist({...checklist,[k]:v})}/>)}<Primary disabled={!checklistReady} onClick={()=>go("sarpas")}>Ir para SARPAS <ChevronRight size={18}/></Primary></>}
      {view==="sarpas"&&<><Title icon={<ShieldCheck/>} title="SARPAS" text="A consulta/autorização ocorre no sistema oficial."/><a className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-sky-700 px-4 font-black text-white" href="https://servicos.decea.mil.br/sarpas/?login=1" target="_blank" rel="noreferrer"><Compass size={18}/> Abrir SARPAS oficial</a><label className="grid gap-1 text-sm font-bold"><span>Situação *</span><select disabled={operationStarted||frozen} className="min-h-11 rounded-xl border px-3" value={mission.sarpasSituacao} onChange={e=>updateMission("sarpasSituacao",e.target.value as SarpasStatus)}><option value="">Selecione...</option><option value="autorizado">Autorizado / referência emitida</option><option value="dispensado">Dispensado após conferência oficial aplicável</option><option value="nao_aplicavel">Não aplicável após conferência</option></select></label>{mission.sarpasSituacao==='autorizado'&&<TextField label="Nº / referência SARPAS *" value={mission.sarpasNumero} onChange={v=>updateMission("sarpasNumero",v)}/>}<CheckRow disabled={operationStarted||frozen} checked={mission.sarpasConfirmado} onChange={v=>updateMission("sarpasConfirmado",v)} title="Confirmei no sistema oficial" detail="Marque somente após a verificação."/><Warning>O DroneGestor não envia nem aprova solicitações SARPAS automaticamente.</Warning><Primary disabled={!canStart} onClick={()=>void startOperation()}><Play size={18}/> Iniciar operação</Primary></>}
      {view==="execucao"&&<><div className="rounded-3xl bg-gradient-to-br from-emerald-950 to-emerald-700 p-5 text-white"><strong className="text-4xl">{fmt(mission.area>0?Math.min(100,progressHa/mission.area*100):0,0)}%</strong><span className="ml-3 text-sm">{fmt(progressHa,2)} de {fmt(mission.area,2)} ha REAIS registrados</span></div><div className="grid grid-cols-2 gap-3"><Metric icon={<Map/>} label="Área restante" value={`${fmt(Math.max(0,mission.area-progressHa),2)} ha`}/><Metric icon={<AlertTriangle/>} label="Ocorrências" value={`${occurrences.length}`}/></div><div className="grid grid-cols-2 gap-3"><button className="min-h-12 rounded-xl border font-black" onClick={()=>void togglePause()}>{paused?<><Play className="mr-2 inline" size={18}/>Retomar</>:<><Pause className="mr-2 inline" size={18}/>Pausar</>}</button><button className="min-h-12 rounded-xl border border-amber-200 bg-amber-50 font-black text-amber-900" onClick={addOccurrence}><AlertTriangle className="mr-2 inline" size={18}/>Ocorrência</button><button className="min-h-12 rounded-xl border border-emerald-200 bg-emerald-50 font-black text-emerald-900 disabled:opacity-40" disabled={paused||areaDone} onClick={recordTankArea}><Check className="mr-2 inline" size={18}/>Registrar tanque/área</button><button className="min-h-12 rounded-xl border bg-slate-100 font-black" onClick={correctProgress}>Corrigir área real</button></div><Info>A área executada é informada manualmente pelo piloto e identificada no histórico como fonte manual. Futuramente poderá ser substituída/validada pela importação DJI AGRAS.</Info>{areaDone?<Info>100% da área planejada registrada. Conclusão definitiva liberada.</Info>:<Warning>A conclusão permanece bloqueada até 100% da área real.</Warning>}<Primary disabled={!areaDone||!canStart||savingFinal||frozen} onClick={()=>void finalizeOperation()}>{savingFinal?"Salvando...":frozen?"Operação congelada":"Concluir e salvar no histórico"}</Primary></>}
      {view==="relatorios"&&<><Title icon={<FileText/>} title="Dados da operação" text="Rascunho atual e acesso ao histórico."/><Info>{finalSaved?"Operação salva no histórico.":pendingCurrent?"Conclusão aguardando sincronização; missão congelada.":"Missão em rascunho."} • {fmt(progressHa,2)} ha registrados.</Info><ReportButton icon={<FileText/>} title="Rascunho da operação" onClick={exportDraft}/><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border font-black" href="/apps/dronegestor/historico"><FileSpreadsheet size={18}/> Abrir histórico salvo</a><Info>O histórico é base estruturada; relatório oficial MAPA e protocolo oficial continuam separados.</Info></>}
      {view==="config"&&<SettingsPanel settings={settings} canManage={canManage} userType={userType} onSave={v=>void saveSettings(v)}/>} 
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-40 mx-auto grid max-w-3xl grid-cols-5 border-t bg-white/95 px-2 py-2"><Nav icon={<Home/>} label="Início" onClick={()=>go("inicio")}/><Nav icon={<Drone/>} label={operationStarted?"Retomar":"Operação"} onClick={()=>guarded(resumeView())}/><Nav icon={<Map/>} label="Segurança" onClick={()=>guarded("seguranca")}/><Nav icon={<FileText/>} label="Dados" onClick={()=>go("relatorios")}/><Nav icon={<Settings2/>} label="Mais" onClick={()=>{if(operationStarted||frozen)return flash("Configurações bloqueadas.");setReturnView(view);go("config")}}/></nav>
  </div></main>
}

function SettingsPanel({settings,canManage,userType,onSave}:{settings:CompanySettings;canManage:boolean;userType:string;onSave:(v:CompanySettings)=>void}){const [draft,setDraft]=useState(settings);useEffect(()=>setDraft(settings),[settings]);const set=<K extends keyof CompanySettings>(k:K,v:CompanySettings[K])=>setDraft(c=>({...c,[k]:v}));return <><Info>Perfil: {userType}. {canManage?"Você pode alterar os padrões.":"Somente leitura."}</Info><Toggle label="Insights obrigatórios" checked={draft.insightsObrigatorios} disabled={!canManage} onChange={v=>set("insightsObrigatorios",v)}/><label className="flex items-center justify-between rounded-2xl border p-4"><span><strong>Margem preventiva interna</strong><small className="block">Padrão interno, não regra legal.</small></span><input disabled={!canManage} className="w-24 rounded-xl border px-3 py-2" type="number" value={draft.margemPreventiva} onChange={e=>set("margemPreventiva",Math.max(0,n(e.target.value)))}/></label><Toggle label="Bloquear abaixo da margem interna" checked={draft.bloquearMargemPreventiva} disabled={!canManage} onChange={v=>set("bloquearMargemPreventiva",v)}/><Toggle label="Exigir confirmação de risco" checked={draft.exigirConfirmacao} disabled={!canManage} onChange={v=>set("exigirConfirmacao",v)}/><Toggle label="Bordadura para cigarrinha (interno)" checked={draft.protocoloBordaduraCigarrinha} disabled={!canManage} onChange={v=>set("protocoloBordaduraCigarrinha",v)}/>{canManage&&<Primary onClick={()=>onSave(draft)}><Check size={18}/> Salvar padrão</Primary>}</>}
function CardButton({icon,title,text,onClick,primary=false}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void;primary?:boolean}){return <button className={`flex min-h-28 items-start gap-3 rounded-2xl border p-4 text-left ${primary?"border-emerald-300 bg-emerald-50":"border-slate-200 bg-white"}`} onClick={onClick}><span>{icon}</span><span><strong className="block">{title}</strong><small>{text}</small></span><ChevronRight className="ml-auto" size={18}/></button>}
function FormGrid({children}:{children:React.ReactNode}){return <div className="grid gap-3 rounded-2xl border p-4 sm:grid-cols-2">{children}</div>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-1 text-sm font-bold"><span>{label}</span><input className="min-h-11 rounded-xl border px-3" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,suffix,onChange}:{label:string;value:number;suffix:string;onChange:(v:number)=>void}){return <label className="grid gap-1 text-sm font-bold"><span>{label}</span><div className="flex min-h-11 items-center rounded-xl border px-3"><input className="min-w-0 flex-1" type="number" step="any" value={value||""} onChange={e=>onChange(n(e.target.value))}/><b className="ml-2 text-xs">{suffix}</b></div></label>}
function Metric({icon,label,value,detail,dark=false}:{icon:React.ReactNode;label:string;value:string;detail?:string;dark?:boolean}){return <div className={`rounded-2xl p-4 ${dark?"bg-white/10":"border bg-white"}`}><span>{icon}</span><small className="mt-2 block">{label}</small><strong className="block text-lg">{value}</strong>{detail&&<span className="text-xs">{detail}</span>}</div>}
function Title({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3"><span>{icon}</span><div><strong className="text-lg">{title}</strong><p className="text-sm text-slate-500">{text}</p></div></div>}
function Warning({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{children}</div>}
function Info({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950">{children}</div>}
function Primary({children,onClick,disabled=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 font-black text-white disabled:bg-slate-300">{children}</button>}
function CheckRow({checked,onChange,title,detail,disabled=false}:{checked:boolean;onChange:(v:boolean)=>void;title:string;detail:string;disabled?:boolean}){return <label className="flex gap-3 rounded-2xl border p-4"><input type="checkbox" disabled={disabled} checked={checked} onChange={e=>onChange(e.target.checked)}/><span><strong className="block">{title}</strong><small>{detail}</small></span></label>}
function Task({index,title,checked,onChange,disabled=false}:{index:string;title:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="flex items-center gap-3 rounded-2xl border p-4"><span className="font-black">{index}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><strong>{title}</strong></label>}
function ReportButton({icon,title,onClick}:{icon:React.ReactNode;title:string;onClick:()=>void}){return <button className="flex min-h-12 items-center gap-3 rounded-xl border px-4 font-black" onClick={onClick}>{icon}{title}</button>}
function Nav({icon,label,onClick}:{icon:React.ReactNode;label:string;onClick:()=>void}){return <button className="grid place-items-center gap-1 text-[11px] font-black" onClick={onClick}>{icon}{label}</button>}
function Toggle({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="flex items-center justify-between rounded-2xl border p-4"><strong>{label}</strong><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
