"use client";

import Link from "next/link";
import { CheckCircle2, Drone, Loader2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Equipment={id:string;entityId:string;data:{nome:string;marca:string;modelo:string;registroAnac:string;tanqueL:number;pontaModelo:string;faixaPadraoM:number;velocidadePadraoKmh:number;alturaPadraoM:number;volumePadraoLHa:number}};
const MISSION_KEY="dronegestor:mission:v2";
const EQUIPMENT_KEY="dronegestor:equipmentId:v1";
const STARTED_KEY="dronegestor:started:v3";
const SLOT_ID="dronegestor-equipment-select-slot";
function readJson<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function findField(){return Array.from(document.querySelectorAll("label")).find((label)=>label.querySelector(":scope > span")?.textContent?.trim()==="Drone *")??null}

export function DroneEquipmentPicker({canManage}:{canManage:boolean}){
  const[items,setItems]=useState<Equipment[]>([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[slot,setSlot]=useState<HTMLElement|null>(null),[message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/dronegestor/equipamentos",{cache:"no-store"}).then(async response=>{const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error||"Falha ao carregar drones.");const next=(payload.items??[]) as Equipment[];setItems(next);const mission=readJson<Record<string,any>>(MISSION_KEY,{});const id=String(mission.equipamentoId||localStorage.getItem(EQUIPMENT_KEY)||"");setSelectedId(next.some(item=>item.entityId===id)?id:"")}).catch(error=>setMessage(error instanceof Error?error.message:"Falha ao carregar drones.")).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const mount=()=>{const label=findField();if(!label)return;const input=label.querySelector("input") as HTMLInputElement|null;if(input){input.style.display="none";input.tabIndex=-1;input.setAttribute("aria-hidden","true")}let node=label.querySelector(`#${SLOT_ID}`) as HTMLElement|null;if(!node){node=document.createElement("div");node.id=SLOT_ID;node.className="grid gap-1";label.appendChild(node)}setSlot(node)};mount();const observer=new MutationObserver(mount);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
  const selected=useMemo(()=>items.find(item=>item.entityId===selectedId)??null,[items,selectedId]);
  const started=typeof window!=="undefined"&&Boolean(readJson(STARTED_KEY,false));
  function apply(id:string){if(started){setMessage("A operação já foi iniciada. O drone não pode ser trocado.");return}const item=items.find(candidate=>candidate.entityId===id);if(!item)return;const previous=readJson<Record<string,any>>(MISSION_KEY,{});const next={...previous,equipamentoId:item.entityId,equipamentoNome:item.data.nome,drone:`${item.data.marca||""} ${item.data.modelo||""}`.trim()||item.data.nome,registroAnac:item.data.registroAnac||"",tanque:Number(item.data.tanqueL)||0,pontaModelo:item.data.pontaModelo||"",faixa:Number(item.data.faixaPadraoM)>0?Number(item.data.faixaPadraoM):previous.faixa||0,velocidadeKmh:Number(item.data.velocidadePadraoKmh)>0?Number(item.data.velocidadePadraoKmh):previous.velocidadeKmh||0,alturaM:Number(item.data.alturaPadraoM)>0?Number(item.data.alturaPadraoM):previous.alturaM||0,volume:Number(item.data.volumePadraoLHa)>0?Number(item.data.volumePadraoLHa):previous.volume||0,sarpasConfirmado:false,sarpasSituacao:"",sarpasNumero:""};localStorage.setItem(MISSION_KEY,JSON.stringify(next));localStorage.setItem(EQUIPMENT_KEY,item.entityId);localStorage.setItem("dronegestor:calibration:v2",JSON.stringify({ar:false,fluxometro:false,bomba:false}));localStorage.setItem("dronegestor:checklist:v2",JSON.stringify({area:false,pessoasAnimais:false,obstaculos:false,drone:false,controle:false,pulverizacao:false,clima:false,documentos:false}));localStorage.setItem("dronegestor:insightAccepted:v2",JSON.stringify(false));localStorage.setItem("dronegestor:riskAccepted:v2",JSON.stringify(false));window.location.reload()}
  if(!slot)return null;
  return createPortal(<div className="grid gap-1.5"><div className="relative"><select value={selectedId} disabled={loading||started||items.length===0} onChange={event=>apply(event.target.value)} className="min-h-11 w-full appearance-none rounded-xl border border-slate-200 bg-white px-3 pr-10 text-sm font-bold text-slate-900 outline-none focus:border-emerald-500 disabled:bg-slate-100"><option value="">{loading?"Carregando drones...":items.length?"Selecione o drone cadastrado...":"Nenhum drone cadastrado"}</option>{items.map(item=><option key={item.entityId} value={item.entityId}>{item.data.nome} — {item.data.marca} {item.data.modelo}</option>)}</select><Drone size={17} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-emerald-700"/></div>{loading&&<span className="inline-flex items-center gap-1 text-[11px] text-slate-500"><Loader2 size={13} className="animate-spin"/>Buscando drones...</span>}{selected&&<span className="inline-flex items-center gap-1 text-[11px] font-semibold text-emerald-700"><CheckCircle2 size={13}/>ANAC, tanque e padrões preenchidos pelo cadastro.</span>}{!loading&&items.length===0&&<span className="text-[11px] font-semibold text-amber-800">Cadastre um drone antes de continuar. {canManage&&<Link href="/apps/dronegestor/equipamentos" className="font-black underline">Cadastrar drone</Link>}</span>}{message&&<span className="text-[11px] font-bold text-red-700">{message}</span>}</div>,slot)
}
