"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ChevronRight, ExternalLink, FileCheck2, FileUp, MapPinned, PlaneTakeoff, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Mission={ordemServicoId?:string;ordemServicoNumero?:string;drone?:string;registroAnac?:string;fazendaNome?:string;talhaoNome?:string;tipoAtividade?:string;cultura?:string;alvo?:string};
type Doc={id:string;tipo:string;nome:string;numero:string;validade:string;observacao:string;url:string;uploadedAt:string};
type Sarpas={status:string;numero:string;solicitadoEm:string;validoDe:string;validoAte:string;observacao:string;updatedAt?:string}|null;
type Evidence={url?:string}|null;
type GuideItem={id:string;label:string;detail:string;ok:boolean;phase:"antes"|"depois";docType?:string;action?:"campo"|"sarpas"};
const TYPES=[
 ["sisant_certidao","SISANT / Certidão ANAC"],["sarpas_autorizacao","Autorização SARPAS"],["avaliacao_risco","Avaliação de risco"],["receituario","Receituário agronômico"],["mapa_aplicacao","Mapa da aplicação"],["exame_piloto_anac","Comprovante exame ANAC"],["seguro","Seguro (se aplicável)"],["registro_mapa","Registro MAPA / SIPEAGRO"],["relatorio_mapa","Relatório mensal MAPA"],["outro","Outro documento"]
] as const;
const SARPAR_URL="https://servicos.decea.mil.br/sarpas/?login=1";
const SISANT_URL="https://sistemas.anac.gov.br/sisant";
function localMission():Mission{try{return JSON.parse(localStorage.getItem("dronegestor:mission:v2")||"{}")}catch{return{}}}
function labelStatus(status:string){return({nao_solicitado:"Não solicitado",em_preparacao:"Em preparação",solicitado:"Solicitado",autorizado:"Autorizado",negado:"Negado"} as Record<string,string>)[status]||status}
function activityLabel(value?:string){if(value==="pulverizacao")return"Pulverização";if(value==="dispersao")return"Dispersão / semeadura";if(value==="outro")return"Outra atividade";return"Atividade não informada"}

export function DroneDocumentsCenter(){
 const[mission,setMission]=useState<Mission>({}); const[docs,setDocs]=useState<Doc[]>([]); const[sarpas,setSarpas]=useState<Sarpas>(null); const[mapa,setMapa]=useState<Evidence>(null); const[loading,setLoading]=useState(true); const[msg,setMsg]=useState("");
 const[status,setStatus]=useState("nao_solicitado"); const[numero,setNumero]=useState(""); const[solicitadoEm,setSolicitadoEm]=useState(""); const[validoDe,setValidoDe]=useState(""); const[validoAte,setValidoAte]=useState(""); const[observacao,setObservacao]=useState("");
 const[tipo,setTipo]=useState("sisant_certidao"); const[docNumero,setDocNumero]=useState(""); const[validade,setValidade]=useState(""); const[file,setFile]=useState<File|null>(null); const[saving,setSaving]=useState(false);
 async function load(){const m=localMission();setMission(m);if(!m.ordemServicoId){setLoading(false);return;}setLoading(true);try{const osId=encodeURIComponent(m.ordemServicoId);const[d,s,map]=await Promise.all([fetch(`/api/dronegestor/documentos?osId=${osId}`,{cache:"no-store"}),fetch(`/api/dronegestor/sarpas?osId=${osId}`,{cache:"no-store"}),fetch(`/api/dronegestor/mapa?osId=${osId}`,{cache:"no-store"})]);const dp=await d.json().catch(()=>null),sp=await s.json().catch(()=>null),mp=await map.json().catch(()=>null);if(d.ok)setDocs(dp?.items||[]);if(map.ok)setMapa(mp?.evidence||null);if(s.ok&&sp?.sarpas){setSarpas(sp.sarpas);setStatus(sp.sarpas.status||"nao_solicitado");setNumero(sp.sarpas.numero||"");setSolicitadoEm((sp.sarpas.solicitadoEm||"").slice(0,10));setValidoDe((sp.sarpas.validoDe||"").slice(0,10));setValidoAte((sp.sarpas.validoAte||"").slice(0,10));setObservacao(sp.sarpas.observacao||"");}}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const has=(t:string)=>docs.some(d=>d.tipo===t);
 const guide=useMemo<GuideItem[]>(()=>{
  const pulverizacao=(mission.tipoAtividade||"pulverizacao")==="pulverizacao";
  const items:GuideItem[]=[
   {id:"anac",label:"Drone identificado",detail:mission.registroAnac?`ANAC: ${mission.registroAnac}`:"Selecione um drone cadastrado com identificação ANAC.",ok:Boolean(mission.registroAnac),phase:"antes",action:"campo"},
   {id:"sisant",label:"Certidão SISANT / ANAC",detail:has("sisant_certidao")?"Documento anexado.":"Anexe a certidão do drone usado nesta operação.",ok:has("sisant_certidao"),phase:"antes",docType:"sisant_certidao"}
  ];
  if(pulverizacao)items.push({id:"receita",label:"Receituário da aplicação",detail:has("receituario")?"Receituário anexado.":"Para o fluxo de pulverização do DroneGestor, anexe o receituário antes da liberação.",ok:has("receituario"),phase:"antes",docType:"receituario"});
  items.push(
   {id:"sarpas",label:"Autorização SARPAS",detail:status==="autorizado"&&numero.trim()?`Autorizado • ${numero.trim()}`:status==="solicitado"?"Solicitação registrada. Quando a autorização sair, volte aqui e informe a referência.":status==="negado"?"Situação negada. A operação não está liberada.":"Abra o SARPAS oficial, faça a solicitação e volte para registrar o resultado.",ok:status==="autorizado"&&Boolean(numero.trim()),phase:"antes",action:"sarpas"},
   {id:"sarpas-doc",label:"Comprovante SARPAS",detail:has("sarpas_autorizacao")?"Comprovante anexado.":"Depois de autorizado, anexe o comprovante da autorização.",ok:has("sarpas_autorizacao"),phase:"antes",docType:"sarpas_autorizacao"},
   {id:"mapa",label:"Mapa usado no voo",detail:(Boolean(mapa?.url)||has("mapa_aplicacao"))?"Mapa/evidência vinculado a esta OS.":"Depois do voo, envie o mapa/evidência desta operação. Uma OS nova não reutiliza o mapa anterior.",ok:Boolean(mapa?.url)||has("mapa_aplicacao"),phase:"depois",docType:"mapa_aplicacao"}
  );
  return items;
 },[mission,docs,status,numero,mapa]);
 const before=guide.filter(item=>item.phase==="antes"),after=guide.filter(item=>item.phase==="depois"),preflightDone=before.filter(item=>item.ok).length,preflightReady=before.every(item=>item.ok),packageDone=guide.filter(item=>item.ok).length,packageReady=guide.every(item=>item.ok),readiness=Math.round(packageDone/Math.max(1,guide.length)*100),next=before.find(item=>!item.ok)||after.find(item=>!item.ok)||null;
 function prepareUpload(docType:string){setTipo(docType);setFile(null);setMsg(`Passo selecionado: ${TYPES.find(t=>t[0]===docType)?.[1]||"documento"}. Escolha o arquivo e toque em Salvar documento.`);window.setTimeout(()=>document.getElementById("upload-card")?.scrollIntoView({behavior:"smooth",block:"start"}),80)}
 async function saveSarpas(){if(!mission.ordemServicoId)return setMsg("Abra ou selecione uma OS primeiro.");if(status==="autorizado"&&!numero.trim())return setMsg("Para marcar como Autorizado, informe o número ou referência emitida no SARPAS.");setSaving(true);setMsg("");try{const r=await fetch("/api/dronegestor/sarpas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,numero,solicitadoEm,validoDe,validoAte,observacao,ordemServicoId:mission.ordemServicoId,ordemServicoNumero:mission.ordemServicoNumero})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Falha ao salvar.");setSarpas(p.sarpas);setMsg(status==="autorizado"?"Autorização SARPAS registrada. Agora anexe o comprovante.":"Situação SARPAS salva. O sistema continuará mostrando o próximo passo.");}catch(e){setMsg(e instanceof Error?e.message:"Falha ao salvar.")}finally{setSaving(false)}}
 async function upload(){if(!file||!mission.ordemServicoId)return setMsg("Escolha um arquivo e uma OS.");setSaving(true);setMsg("");try{const f=new FormData();f.append("arquivo",file);f.append("tipo",tipo);f.append("numero",docNumero);f.append("validade",validade);f.append("ordemServicoId",mission.ordemServicoId);f.append("ordemServicoNumero",mission.ordemServicoNumero||"");const r=await fetch("/api/dronegestor/documentos",{method:"POST",body:f});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Falha ao enviar.");setDocs(current=>[p.item,...current]);setFile(null);setDocNumero("");setValidade("");setMsg("Documento salvo nesta OS. O checklist foi atualizado automaticamente.");}catch(e){setMsg(e instanceof Error?e.message:"Falha ao enviar.")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#f4f8f1] px-3 pb-28 pt-4 text-[#143d31] sm:px-6 sm:py-8"><div className="mx-auto w-full max-w-4xl">
  <div className="flex items-center gap-3"><Link href="/apps/dronegestor" className="grid size-11 shrink-0 place-items-center rounded-2xl border border-[#d6e5dc] bg-white text-[#276650]"><ArrowLeft size={20}/></Link><div className="min-w-0"><h1 className="text-2xl font-black">SARPAS e documentos</h1><p className="text-sm text-[#6b7c73]">O sistema mostra o próximo passo. Você não precisa decorar quais documentos usar.</p></div></div>
  {!mission.ordemServicoId?<div className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-amber-950"><TriangleAlert className="mr-2 inline" size={18}/><strong>Nenhuma OS selecionada.</strong><p className="mt-2 text-sm">Entre em Operação, selecione a OS e depois volte aqui. O checklist será montado automaticamente.</p></div>:<>
   <section className="mt-5 rounded-[28px] bg-[#063f2d] p-5 text-white"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><span className="text-xs font-black uppercase tracking-[.14em] text-[#8ed8af]">{mission.ordemServicoNumero||"OS ativa"}</span><h2 className="mt-2 truncate text-xl font-black sm:text-2xl">{mission.fazendaNome||"Operação"} {mission.talhaoNome?`• ${mission.talhaoNome}`:""}</h2><p className="mt-2 text-sm text-[#c9ddd2]">{activityLabel(mission.tipoAtividade)} • Drone: {mission.drone||"—"}</p></div><div className="grid size-16 shrink-0 place-items-center rounded-full bg-white/10 text-xl font-black">{readiness}%</div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-emerald-100">Antes do voo</span><strong className="mt-1 block text-lg">{preflightDone}/{before.length}</strong></div><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-emerald-100">Pacote da OS</span><strong className="mt-1 block text-lg">{packageDone}/{guide.length}</strong></div></div></section>

   <section className={`mt-4 rounded-[26px] border p-5 ${preflightReady?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-start gap-3">{preflightReady?<CheckCircle2 className="mt-0.5 shrink-0 text-emerald-700"/>:<ChevronRight className="mt-0.5 shrink-0 text-amber-700"/>}<div className="min-w-0 flex-1"><span className="text-xs font-black uppercase tracking-wider">{preflightReady?"Pré-voo documental pronto":"Seu próximo passo"}</span><h2 className="mt-1 text-lg font-black">{preflightReady?"Documentação pré-voo conferida":next?.label||"Tudo conferido"}</h2><p className="mt-1 text-sm leading-6">{preflightReady?"Continue o passo a passo do DroneGestor até a liberação e início da operação. O mapa do voo será exigido depois da execução.":next?.detail}</p></div></div>{!preflightReady&&next?.docType&&<button type="button" onClick={()=>prepareUpload(next.docType!)} className="mt-4 min-h-11 w-full rounded-xl bg-amber-700 px-4 text-sm font-black text-white">Enviar este documento agora</button>}{!preflightReady&&next?.action==="campo"&&<Link href="/apps/dronegestor/campo" className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-amber-700 px-4 text-sm font-black text-white no-underline">Voltar aos dados da operação</Link>}{!preflightReady&&next?.action==="sarpas"&&<a href={SARPAR_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-amber-700 px-4 text-sm font-black text-white no-underline">Abrir SARPAS oficial <ExternalLink size={15}/></a>}</section>

   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-[#087a55]"/><div><h2 className="font-black">Checklist desta operação</h2><p className="text-sm text-[#6c7c73]">Montado automaticamente para {activityLabel(mission.tipoAtividade).toLowerCase()}.</p></div></div><h3 className="mt-4 text-xs font-black uppercase tracking-wider text-slate-500">Antes de liberar o voo</h3><div className="mt-2 grid gap-2">{before.map(item=><GuideRow key={item.id} item={item} onUpload={prepareUpload}/>)}</div><h3 className="mt-5 text-xs font-black uppercase tracking-wider text-slate-500">Depois do voo</h3><div className="mt-2 grid gap-2">{after.map(item=><GuideRow key={item.id} item={item} onUpload={prepareUpload}/>)}</div>{mission.tipoAtividade==="outro"&&<div className="mt-4 rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm leading-6 text-sky-950"><strong>Atividade “Outro”:</strong> o sistema aplica os documentos comuns e deixa documentos técnicos adicionais para conferência do gestor/RT. Ele não presume uma exigência específica sem regra cadastrada.</div>}</section>

   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><PlaneTakeoff className="text-[#087a55]"/><div><h2 className="font-black">SARPAS</h2><p className="text-sm text-[#6c7c73]">1. Abra o sistema oficial. 2. Solicite. 3. Quando sair a autorização, registre a referência aqui. 4. Anexe o comprovante.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Situação<select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"><option value="nao_solicitado">Ainda não solicitei</option><option value="em_preparacao">Estou preparando a solicitação</option><option value="solicitado">Solicitei e aguardo resposta</option><option value="autorizado">Autorizado</option><option value="negado">Negado — não libera o voo</option></select></label><label className="grid gap-1 text-sm font-bold">Número / referência{status==="autorizado"?" *":""}<input value={numero} onChange={e=>setNumero(e.target.value)} placeholder={status==="autorizado"?"Informe a referência emitida":"Opcional enquanto aguarda"} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Solicitado em<input type="date" value={solicitadoEm} onChange={e=>setSolicitadoEm(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Validade até<input type="date" value={validoAte} onChange={e=>setValidoAte(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label></div><label className="mt-3 grid gap-1 text-sm font-bold">Observação<textarea value={observacao} onChange={e=>setObservacao(e.target.value)} className="min-h-20 rounded-xl border border-[#cfddd5] p-3"/></label><div className="mt-4 grid gap-2 sm:grid-cols-3"><button disabled={saving} onClick={()=>void saveSarpas()} className="min-h-11 rounded-xl bg-[#087a55] px-4 font-black text-white">Salvar situação</button><a href={SARPAR_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#bcd5c6] bg-white px-4 font-black text-[#176a4c] no-underline">Abrir SARPAS <ExternalLink size={15}/></a><a href={SISANT_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#bcd5c6] bg-white px-4 font-black text-[#176a4c] no-underline">Abrir SISANT <ExternalLink size={15}/></a></div>{sarpas&&<p className="mt-3 text-sm font-bold text-slate-600">Situação salva: {labelStatus(sarpas.status)}{sarpas.numero?` • ${sarpas.numero}`:""}</p>}</section>

   <section id="upload-card" className="mt-4 scroll-mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><FileUp className="text-[#087a55]"/><div><h2 className="font-black">Enviar documento</h2><p className="text-sm text-[#6c7c73]">Escolha o arquivo. O tipo já pode ser selecionado pelo passo acima.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Que documento é este?<select value={tipo} onChange={e=>setTipo(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3">{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">Número / referência<input value={docNumero} onChange={e=>setDocNumero(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Validade<input type="date" value={validade} onChange={e=>setValidade(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Arquivo<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xlsx" onChange={e=>setFile(e.target.files?.[0]||null)} className="min-h-12 rounded-xl border border-[#cfddd5] p-2"/></label></div><button disabled={saving||!file} onClick={()=>void upload()} className="mt-4 min-h-11 w-full rounded-xl bg-[#087a55] px-4 font-black text-white disabled:opacity-50">Salvar documento nesta OS</button></section>

   <section className={`mt-4 rounded-[26px] border p-5 ${packageReady?"border-emerald-200 bg-emerald-50":"border-[#d9e8df] bg-white"}`}><div className="flex items-center gap-3">{packageReady?<CheckCircle2 className="text-emerald-700"/>:<MapPinned className="text-[#087a55]"/>}<div><h2 className="font-black">{packageReady?"Pacote obrigatório conferido":"Resumo simples"}</h2><p className="text-sm text-slate-600">{preflightReady?"Pré-voo documental pronto.":`${before.length-preflightDone} item(ns) ainda impedem a liberação documental.`} {!after.every(item=>item.ok)?"Depois do voo ainda será necessário vincular o mapa/evidência.":"Mapa/evidência do voo já vinculado."}</p></div></div></section>

   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><h2 className="font-black">Documentos desta OS</h2>{loading?<p className="mt-3 text-sm">Carregando...</p>:docs.length?<div className="mt-3 grid gap-2">{docs.map(d=><a key={d.id} href={d.url||"#"} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-[#e1ebe5] p-3 no-underline"><FileCheck2 size={19} className="text-[#087a55]"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#173f31]">{TYPES.find(t=>t[0]===d.tipo)?.[1]||d.tipo}</strong><span className="block truncate text-xs text-[#718078]">{d.nome}{d.validade?` • validade ${d.validade}`:""}</span></span><ExternalLink size={15}/></a>)}</div>:<p className="mt-3 text-sm text-[#718078]">Nenhum documento anexado ainda. Use o bloco “Seu próximo passo” acima.</p>}</section>
  </>}{msg&&<div className="fixed bottom-24 left-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 rounded-2xl bg-[#063f2d] px-4 py-3 text-sm font-bold text-white shadow-xl">{msg}</div>}
 </div></main>
}

function GuideRow({item,onUpload}:{item:GuideItem;onUpload:(type:string)=>void}){return <div className={`rounded-xl border px-3 py-3 ${item.ok?"border-emerald-100 bg-emerald-50":"border-amber-100 bg-amber-50"}`}><div className="flex items-start gap-3">{item.ok?<CheckCircle2 className="mt-0.5 shrink-0 text-emerald-700" size={18}/>:<TriangleAlert className="mt-0.5 shrink-0 text-amber-700" size={18}/>}<div className="min-w-0 flex-1"><strong className="block text-sm">{item.label}</strong><p className="mt-1 text-sm leading-5 text-slate-600">{item.detail}</p></div></div>{!item.ok&&item.docType&&<button type="button" onClick={()=>onUpload(item.docType!)} className="mt-2 min-h-9 rounded-lg border border-amber-300 bg-white px-3 text-xs font-black text-amber-900">Enviar agora</button>}{!item.ok&&item.action==="sarpas"&&<a href={SARPAR_URL} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-9 items-center rounded-lg border border-amber-300 bg-white px-3 text-xs font-black text-amber-900 no-underline">Abrir SARPAS</a>}{!item.ok&&item.action==="campo"&&<Link href="/apps/dronegestor/campo" className="mt-2 inline-flex min-h-9 items-center rounded-lg border border-amber-300 bg-white px-3 text-xs font-black text-amber-900 no-underline">Corrigir na operação</Link>}</div>}
