"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, FileCheck2, FileUp, PlaneTakeoff, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Mission={ordemServicoId?:string;ordemServicoNumero?:string;drone?:string;registroAnac?:string;fazendaNome?:string;talhaoNome?:string};
type Doc={id:string;tipo:string;nome:string;numero:string;validade:string;observacao:string;url:string;uploadedAt:string};
type Sarpas={status:string;numero:string;solicitadoEm:string;validoDe:string;validoAte:string;observacao:string;updatedAt?:string}|null;
const TYPES=[
 ["sisant_certidao","SISANT / Certidão ANAC"],["sarpas_autorizacao","Autorização SARPAS"],["avaliacao_risco","Avaliação de risco"],["receituario","Receituário agronômico"],["mapa_aplicacao","Mapa da aplicação"],["exame_piloto_anac","Comprovante exame ANAC"],["seguro","Seguro (se aplicável)"],["registro_mapa","Registro MAPA / SIPEAGRO"],["relatorio_mapa","Relatório mensal MAPA"],["outro","Outro documento"]
] as const;
const SARPAR_URL="https://servicos.decea.mil.br/sarpas/?login=1";
const SISANT_URL="https://sistemas.anac.gov.br/sisant";
function localMission():Mission{try{return JSON.parse(localStorage.getItem("dronegestor:mission:v2")||"{}")}catch{return{}}}
function labelStatus(status:string){return({nao_solicitado:"Não solicitado",em_preparacao:"Em preparação",solicitado:"Solicitado",autorizado:"Autorizado",negado:"Negado",dispensado:"Dispensado",nao_aplicavel:"Não aplicável"} as Record<string,string>)[status]||status}

export function DroneDocumentsCenter(){
 const[mission,setMission]=useState<Mission>({}); const[docs,setDocs]=useState<Doc[]>([]); const[sarpas,setSarpas]=useState<Sarpas>(null); const[loading,setLoading]=useState(true); const[msg,setMsg]=useState("");
 const[status,setStatus]=useState("nao_solicitado"); const[numero,setNumero]=useState(""); const[solicitadoEm,setSolicitadoEm]=useState(""); const[validoDe,setValidoDe]=useState(""); const[validoAte,setValidoAte]=useState(""); const[observacao,setObservacao]=useState("");
 const[tipo,setTipo]=useState("sisant_certidao"); const[docNumero,setDocNumero]=useState(""); const[validade,setValidade]=useState(""); const[file,setFile]=useState<File|null>(null); const[saving,setSaving]=useState(false);
 async function load(){const m=localMission();setMission(m);if(!m.ordemServicoId){setLoading(false);return;}setLoading(true);try{const [d,s]=await Promise.all([fetch(`/api/dronegestor/documentos?osId=${encodeURIComponent(m.ordemServicoId)}`,{cache:"no-store"}),fetch(`/api/dronegestor/sarpas?osId=${encodeURIComponent(m.ordemServicoId)}`,{cache:"no-store"})]);const dp=await d.json().catch(()=>null),sp=await s.json().catch(()=>null);if(d.ok)setDocs(dp?.items||[]);if(s.ok&&sp?.sarpas){setSarpas(sp.sarpas);setStatus(sp.sarpas.status||"nao_solicitado");setNumero(sp.sarpas.numero||"");setSolicitadoEm((sp.sarpas.solicitadoEm||"").slice(0,10));setValidoDe((sp.sarpas.validoDe||"").slice(0,10));setValidoAte((sp.sarpas.validoAte||"").slice(0,10));setObservacao(sp.sarpas.observacao||"");}}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const has=(t:string)=>docs.some(d=>d.tipo===t); const readiness=useMemo(()=>{const checks=[Boolean(mission.ordemServicoId),Boolean(mission.registroAnac),has("sisant_certidao"),status==="autorizado"||status==="dispensado"||status==="nao_aplicavel",status!=="autorizado"||has("sarpas_autorizacao")];return Math.round(checks.filter(Boolean).length/checks.length*100)},[mission,docs,status]);
 async function saveSarpas(){if(!mission.ordemServicoId)return setMsg("Abra ou selecione uma OS primeiro.");setSaving(true);setMsg("");try{const r=await fetch("/api/dronegestor/sarpas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,numero,solicitadoEm,validoDe,validoAte,observacao,ordemServicoId:mission.ordemServicoId,ordemServicoNumero:mission.ordemServicoNumero})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Falha ao salvar.");setSarpas(p.sarpas);setMsg("Status SARPAS salvo.");}catch(e){setMsg(e instanceof Error?e.message:"Falha ao salvar.")}finally{setSaving(false)}}
 async function upload(){if(!file||!mission.ordemServicoId)return setMsg("Escolha um arquivo e uma OS.");setSaving(true);setMsg("");try{const f=new FormData();f.append("arquivo",file);f.append("tipo",tipo);f.append("numero",docNumero);f.append("validade",validade);f.append("ordemServicoId",mission.ordemServicoId);f.append("ordemServicoNumero",mission.ordemServicoNumero||"");const r=await fetch("/api/dronegestor/documentos",{method:"POST",body:f});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Falha ao enviar.");setDocs(current=>[p.item,...current]);setFile(null);setDocNumero("");setValidade("");setMsg("Documento salvo no pacote da operação.");}catch(e){setMsg(e instanceof Error?e.message:"Falha ao enviar.")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#f4f8f1] px-3 pb-28 pt-4 text-[#143d31] sm:px-6 sm:py-8"><div className="mx-auto w-full max-w-4xl">
  <div className="flex items-center gap-3"><Link href="/apps/dronegestor" className="grid size-11 place-items-center rounded-2xl border border-[#d6e5dc] bg-white text-[#276650]"><ArrowLeft size={20}/></Link><div><h1 className="text-2xl font-black">Central SARPAS e documentos</h1><p className="text-sm text-[#6b7c73]">Uma tela para saber o que está pronto e o que ainda falta.</p></div></div>
  {!mission.ordemServicoId?<div className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-amber-950"><TriangleAlert className="mr-2 inline" size={18}/><strong>Nenhuma OS selecionada.</strong><p className="mt-2 text-sm">Entre em Operação, selecione a OS e depois volte aqui.</p></div>:<>
   <section className="mt-5 rounded-[28px] bg-[#063f2d] p-5 text-white"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.14em] text-[#8ed8af]">{mission.ordemServicoNumero||"OS ativa"}</span><h2 className="mt-2 text-2xl font-black">{mission.fazendaNome||"Operação"} {mission.talhaoNome?`• ${mission.talhaoNome}`:""}</h2><p className="mt-2 text-sm text-[#c9ddd2]">Drone: {mission.drone||"—"} • ANAC: {mission.registroAnac||"—"}</p></div><div className="grid size-16 place-items-center rounded-full bg-white/10 text-xl font-black">{readiness}%</div></div></section>
   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><PlaneTakeoff className="text-[#087a55]"/><div><h2 className="font-black">SARPAS</h2><p className="text-xs text-[#6c7c73]">O SARPAS é o sistema oficial do DECEA para solicitação de acesso ao espaço aéreo.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Situação<select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"><option value="nao_solicitado">Não solicitado</option><option value="em_preparacao">Em preparação</option><option value="solicitado">Solicitado</option><option value="autorizado">Autorizado</option><option value="negado">Negado</option><option value="dispensado">Dispensado — somente após conferência</option><option value="nao_aplicavel">Não aplicável — somente após conferência</option></select></label><label className="grid gap-1 text-sm font-bold">Número / protocolo<input value={numero} onChange={e=>setNumero(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Solicitado em<input type="date" value={solicitadoEm} onChange={e=>setSolicitadoEm(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Validade até<input type="date" value={validoAte} onChange={e=>setValidoAte(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label></div><label className="mt-3 grid gap-1 text-sm font-bold">Observação<textarea value={observacao} onChange={e=>setObservacao(e.target.value)} className="min-h-20 rounded-xl border border-[#cfddd5] p-3"/></label><div className="mt-4 flex flex-wrap gap-2"><button disabled={saving} onClick={()=>void saveSarpas()} className="min-h-11 rounded-xl bg-[#087a55] px-4 font-black text-white">Salvar SARPAS</button><a href={SARPAR_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#bcd5c6] bg-white px-4 font-black text-[#176a4c] no-underline">Abrir SARPAS oficial <ExternalLink size={15}/></a><a href={SISANT_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#bcd5c6] bg-white px-4 font-black text-[#176a4c] no-underline">Abrir SISANT <ExternalLink size={15}/></a></div></section>
   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><FileUp className="text-[#087a55]"/><div><h2 className="font-black">Adicionar ao pacote da operação</h2><p className="text-xs text-[#6c7c73]">PDF, imagem ou XLSX. Máximo 10 MB por arquivo.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Documento<select value={tipo} onChange={e=>setTipo(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3">{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">Número / referência<input value={docNumero} onChange={e=>setDocNumero(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Validade<input type="date" value={validade} onChange={e=>setValidade(e.target.value)} className="min-h-12 rounded-xl border border-[#cfddd5] px-3"/></label><label className="grid gap-1 text-sm font-bold">Arquivo<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xlsx" onChange={e=>setFile(e.target.files?.[0]||null)} className="min-h-12 rounded-xl border border-[#cfddd5] p-2"/></label></div><button disabled={saving||!file} onClick={()=>void upload()} className="mt-4 min-h-11 rounded-xl bg-[#087a55] px-4 font-black text-white disabled:opacity-50">Salvar documento</button></section>
   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-[#087a55]"/><h2 className="font-black">Conferência rápida</h2></div><div className="mt-4 grid gap-2">{[[Boolean(mission.registroAnac),"Identificação ANAC do drone"],[has("sisant_certidao"),"Certidão SISANT anexada"],[status==="autorizado"||status==="dispensado"||status==="nao_aplicavel",`SARPAS: ${labelStatus(status)}`],[status!=="autorizado"||has("sarpas_autorizacao"),"Comprovante/autorização SARPAS anexado quando aplicável"],[has("receituario"),"Receituário anexado quando aplicável"],[has("mapa_aplicacao"),"Mapa da aplicação anexado"]].map(([ok,label],i)=><div key={i} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${ok?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-950"}`}>{ok?<CheckCircle2 size={18}/>:<TriangleAlert size={18}/>}<span>{label as string}</span></div>)}</div></section>
   <section className="mt-4 rounded-[26px] border border-[#d9e8df] bg-white p-5"><h2 className="font-black">Documentos desta OS</h2>{loading?<p className="mt-3 text-sm">Carregando...</p>:docs.length?<div className="mt-3 grid gap-2">{docs.map(d=><a key={d.id} href={d.url||"#"} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-[#e1ebe5] p-3 no-underline"><FileCheck2 size={19} className="text-[#087a55]"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#173f31]">{TYPES.find(t=>t[0]===d.tipo)?.[1]||d.tipo}</strong><span className="block truncate text-xs text-[#718078]">{d.nome}{d.validade?` • validade ${d.validade}`:""}</span></span><ExternalLink size={15}/></a>)}</div>:<p className="mt-3 text-sm text-[#718078]">Nenhum documento anexado ainda.</p>}</section>
  </>}{msg&&<div className="fixed bottom-24 left-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 rounded-2xl bg-[#063f2d] px-4 py-3 text-sm font-bold text-white shadow-xl">{msg}</div>}
 </div></main>
}
