import { NextRequest, NextResponse } from "next/server";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";
const ACTION="sarpas_operacao_v1";
const STATUSES=new Set(["nao_solicitado","em_preparacao","solicitado","autorizado","negado","dispensado","nao_aplicavel"]);
type Context={userId:string;empresaId:string|null;userName:string};
function normalize(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function text(v:unknown,max=200){return typeof v==="string"?v.trim().slice(0,max):""}
async function context():Promise<{current:Context|null;response:NextResponse|null}>{const s=await getSessionProfile();if(!s.user||!s.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const t=normalize(s.profile.tipo||""),master=["super_admin","admin_master"].includes(t),allowed=(s.appsLiberados??[]).some(a=>a.slug==="dronegestor"&&a.canAccess);if(!master&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{userId:s.profile.id,empresaId:s.profile.empresa_id,userName:s.profile.nome||"Piloto"},response:null}}
function scope(q:any,c:Context){return c.empresaId?q.eq("empresa_id",c.empresaId):q.eq("usuario_id",c.userId)}
function sanitize(source:any){const status=text(source?.status,40);return{status:STATUSES.has(status)?status:"nao_solicitado",numero:text(source?.numero,120),solicitadoEm:text(source?.solicitadoEm,40),validoDe:text(source?.validoDe,40),validoAte:text(source?.validoAte,40),observacao:text(source?.observacao,800),ordemServicoId:text(source?.ordemServicoId,120),ordemServicoNumero:text(source?.ordemServicoNumero,120)}}

export async function GET(request:NextRequest){try{const a=await context();if(a.response)return a.response;const c=a.current!,admin=createSupabaseAdminClient() as any,osId=text(request.nextUrl.searchParams.get("osId"),120);let q=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",ACTION).order("created_at",{ascending:false}).limit(100);q=scope(q,c);const {data,error}=await q;if(error)throw error;const row=(data??[]).find((r:any)=>!osId||text(r?.detalhes?.ordemServicoId,120)===osId);return NextResponse.json({ok:true,sarpas:row?{...sanitize(row.detalhes),updatedAt:row.created_at,updatedBy:text(row?.detalhes?.updatedBy,180)}:null});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao carregar SARPAS."},{status:500})}}

export async function POST(request:NextRequest){try{const a=await context();if(a.response)return a.response;const c=a.current!,body=await request.json(),sarpas=sanitize(body),admin=createSupabaseAdminClient() as any,now=new Date().toISOString();if(!sarpas.ordemServicoId)return NextResponse.json({ok:false,error:"Selecione uma OS antes de registrar o SARPAS."},{status:400});if(sarpas.status==="autorizado"&&!sarpas.numero)return NextResponse.json({ok:false,error:"Informe o número da autorização SARPAS."},{status:400});const details={...sarpas,updatedAt:now,updatedBy:c.userName};const {error}=await admin.from("core_logs").insert({empresa_id:c.empresaId,usuario_id:c.userId,app_slug:"dronegestor",acao:ACTION,detalhes:details});if(error)throw error;return NextResponse.json({ok:true,sarpas:{...details}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao salvar SARPAS."},{status:500})}}
