import { NextRequest, NextResponse } from "next/server";
import ExcelJS from "exceljs";
import { getSessionProfile } from "@/lib/core-data";
import { createSupabaseAdminClient } from "@mba-labs/shared/supabase/server";

export const dynamic = "force-dynamic";
const FINALIZED_ACTION="operacao_finalizada";
const PROFILE_ACTION="perfil_operacional_v1";

type Context={userId:string;userName:string;userType:string;empresaId:string|null;companyHistory:boolean};
function normalize(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","_")}
function text(v:unknown){return typeof v==="string"?v.trim():""}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0}
function obj(v:unknown):Record<string,any>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>: {}}
function monthRange(month:string){const match=/^(\d{4})-(\d{2})$/.exec(month);if(!match)throw new Error("Competência inválida.");const y=Number(match[1]),m=Number(match[2]);if(m<1||m>12)throw new Error("Competência inválida.");return{start:new Date(Date.UTC(y,m-1,1)).toISOString(),end:new Date(Date.UTC(y,m,1)).toISOString(),year:y,month:m}}
function durationHours(start:unknown,end:unknown){const a=Date.parse(text(start)),b=Date.parse(text(end));return Number.isFinite(a)&&Number.isFinite(b)&&b>=a?(b-a)/3600000:0}
async function context():Promise<{current:Context|null;response:NextResponse|null}>{const s=await getSessionProfile();if(!s.user||!s.profile)return{current:null,response:NextResponse.json({ok:false,error:"Autenticação necessária."},{status:401})};const type=normalize(s.profile.tipo||""),master=["super_admin","admin_master"].includes(type),allowed=(s.appsLiberados??[]).some(a=>a.slug==="dronegestor"&&a.canAccess);if(!master&&!allowed)return{current:null,response:NextResponse.json({ok:false,error:"Acesso ao DroneGestor não liberado."},{status:403})};return{current:{userId:s.profile.id,userName:s.profile.nome||"Piloto",userType:s.profile.tipo,empresaId:s.profile.empresa_id,companyHistory:master||["admin_empresa","responsavel_tecnico","rt"].includes(type)},response:null}}
function scope(q:any,c:Context){return c.companyHistory&&c.empresaId?q.eq("empresa_id",c.empresaId):q.eq("usuario_id",c.userId)}
async function profile(admin:any,c:Context){let q=admin.from("core_logs").select("detalhes").eq("app_slug","dronegestor").eq("acao",PROFILE_ACTION).order("created_at",{ascending:false}).limit(1);q=c.empresaId?q.eq("empresa_id",c.empresaId):q.eq("usuario_id",c.userId);const {data}=await q.maybeSingle();return obj(data?.detalhes?.profile)}

export async function GET(request:NextRequest){
 try{
  const access=await context();if(access.response)return access.response;const c=access.current!,admin=createSupabaseAdminClient() as any;
  const month=text(request.nextUrl.searchParams.get("month"))||new Date().toISOString().slice(0,7);const range=monthRange(month);
  let q=admin.from("core_logs").select("id,detalhes,created_at").eq("app_slug","dronegestor").eq("acao",FINALIZED_ACTION).gte("created_at",range.start).lt("created_at",range.end).order("created_at",{ascending:true}).limit(500);q=scope(q,c);const[{data,error},p]=await Promise.all([q,profile(admin,c)]);if(error)throw error;
  const rows:Array<{municipioUf:string;arp:string;area:number;horas:number;atividade:string;produto:string;volume:number;dose:string}>=[];
  for(const item of data??[]){const summary=obj(item?.detalhes?.summary),products=Array.isArray(summary.produtos)&&summary.produtos.length?summary.produtos:[{}],area=num(summary.areaConcluidaHa??summary.areaHa),hours=durationHours(summary.iniciadaEm,summary.finalizadaEm),volume=num(summary.totalCaldaRealL??summary.totalCaldaL);products.forEach((raw:any,index:number)=>{const product=obj(raw);rows.push({municipioUf:[text(summary.municipio),text(summary.uf)].filter(Boolean).join("/")||"—",arp:[text(summary.drone),text(summary.registroAnac)].filter(Boolean).join(" • ")||"—",area:index===0?area:0,horas:index===0?hours:0,atividade:text(summary.tipoAtividade)||"—",produto:text(product.nome)||"—",volume:index===0?volume:0,dose:`${num(product.dose).toFixed(2)} ${text(product.unidade)}`.trim()})})}

  const workbook=new ExcelJS.Workbook();workbook.creator="DroneGestor — MBA Labs";workbook.created=new Date();workbook.modified=new Date();
  const ws=workbook.addWorksheet("RELATORIO MENSAL",{pageSetup:{orientation:"landscape",paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:0.25,right:0.25,top:0.35,bottom:0.35,header:0.15,footer:0.15}}});
  ws.mergeCells("A1:H1");ws.getCell("A1").value="RELATÓRIO MENSAL DE ATIVIDADES — ARP (DRONE)";ws.getCell("A1").font={bold:true,size:16};ws.getCell("A1").alignment={horizontal:"center",vertical:"middle"};ws.getRow(1).height=28;
  ws.mergeCells("A2:H2");ws.getCell("A2").value=`Competência: ${month} | Gerado pelo DroneGestor | Campos consolidados conforme Portaria MAPA nº 298/2021, art. 11`;ws.getCell("A2").font={italic:true,size:9};ws.getCell("A2").alignment={horizontal:"center"};
  const info=[["Operador aeroagrícola",text(p.operadorNome)],["CPF/CNPJ",text(p.cpfCnpj)],["Registro MAPA / SIPEAGRO",text(p.registroMapa)],["Processo SEI",text(p.processoSei)],["Responsável técnico",text(p.rtNome)],["Conselho / registro",[text(p.rtConselho),text(p.rtRegistro)].filter(Boolean).join(" ")]];
  let row=4;for(let i=0;i<info.length;i+=2){const a=info[i],b=info[i+1];ws.getCell(row,1).value=a[0];ws.getCell(row,2).value=a[1]||"";ws.mergeCells(row,2,row,4);if(b){ws.getCell(row,5).value=b[0];ws.getCell(row,6).value=b[1]||"";ws.mergeCells(row,6,row,8)}for(const col of [1,5])ws.getCell(row,col).font={bold:true,size:9};row++}
  row++;
  const headers=["Município/UF","ARP / identificação ANAC","Área aplicada (ha)","Horas de execução (h)","Tipo de atividade","Marca comercial","Volume aplicado (L)","Dosagem aplicada"];
  headers.forEach((h,i)=>{const cell=ws.getCell(row,i+1);cell.value=h;cell.font={bold:true,color:{argb:"FFFFFFFF"},size:9};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF07553B"}};cell.alignment={vertical:"middle",wrapText:true,horizontal:"center"};cell.border={top:{style:"thin"},left:{style:"thin"},bottom:{style:"thin"},right:{style:"thin"}}});ws.getRow(row).height=32;const headerRow=row;row++;
  if(rows.length===0){ws.mergeCells(row,1,row,8);const cell=ws.getCell(row,1);cell.value="NENHUMA ATIVIDADE REALIZADA";cell.font={bold:true,size:12};cell.alignment={horizontal:"center",vertical:"middle"};cell.border={top:{style:"thin"},left:{style:"thin"},bottom:{style:"thin"},right:{style:"thin"}};ws.getRow(row).height=36;row++;}
  else{for(const item of rows){const values=[item.municipioUf,item.arp,item.area||"",item.horas||"",item.atividade,item.produto,item.volume||"",item.dose];values.forEach((v,i)=>{const cell=ws.getCell(row,i+1);cell.value=v;cell.font={size:9};cell.alignment={vertical:"top",wrapText:true};cell.border={top:{style:"thin",color:{argb:"FF9CA3AF"}},left:{style:"thin",color:{argb:"FF9CA3AF"}},bottom:{style:"thin",color:{argb:"FF9CA3AF"}},right:{style:"thin",color:{argb:"FF9CA3AF"}}};if([3,4,7].includes(i+1)&&typeof v==="number")cell.numFmt=i+1===4?"0.00":"0.00"});row++;}const totalArea=rows.reduce((s,r)=>s+r.area,0),totalHours=rows.reduce((s,r)=>s+r.horas,0),totalVolume=rows.reduce((s,r)=>s+r.volume,0);ws.mergeCells(row,1,row,2);ws.getCell(row,1).value="TOTAL DO MÊS";ws.getCell(row,1).font={bold:true};ws.getCell(row,3).value=totalArea;ws.getCell(row,4).value=totalHours;ws.getCell(row,7).value=totalVolume;for(let c2=1;c2<=8;c2++){const cell=ws.getCell(row,c2);cell.font={...cell.font,bold:true,size:9};cell.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF4EE"}};cell.border={top:{style:"thin"},left:{style:"thin"},bottom:{style:"thin"},right:{style:"thin"}}}row++;}
  ws.columns=[{width:18},{width:28},{width:15},{width:18},{width:18},{width:28},{width:18},{width:20}];ws.autoFilter={from:{row:headerRow,column:1},to:{row:headerRow,column:8}};ws.views=[{state:"frozen",ySplit:headerRow}];
  row+=2;ws.mergeCells(row,1,row,8);ws.getCell(row,1).value="ATENÇÃO: este XLSX é gerado pelo DroneGestor com os campos obrigatórios conhecidos do relatório mensal. O MAPA informa que a remessa de 2026 deve utilizar a planilha oficial versão 01-01-2026 disponibilizada no Drive oficial e protocolada via SEI. Enquanto o arquivo oficial não estiver incorporado ao sistema, confira/transfira os dados antes do protocolo.";ws.getCell(row,1).alignment={wrapText:true,vertical:"top"};ws.getCell(row,1).font={size:9,color:{argb:"FF92400E"}};ws.getCell(row,1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFFFF7ED"}};ws.getRow(row).height=58;

  const meta=workbook.addWorksheet("ORIENTACOES");meta.getColumn(1).width=30;meta.getColumn(2).width=100;meta.addRow(["Documento","XLSX de consolidação gerado pelo DroneGestor"]);meta.addRow(["Competência",month]);meta.addRow(["Base","Portaria MAPA nº 298/2021, art. 11"]);meta.addRow(["Remessa 2026","O MAPA orienta uso da planilha oficial versão 01-01-2026 e envio pelo processo SEI tipo Relatório Mensal Aviação Agrícola."]);meta.addRow(["Status do modelo","Não é cópia binária/visual 1:1 do arquivo oficial enquanto o Drive do MAPA exigir autenticação Microsoft."]);meta.getColumn(1).font={bold:true};meta.eachRow(r=>{r.alignment={vertical:"top",wrapText:true}});
  const buffer=await workbook.xlsx.writeBuffer();
  return new NextResponse(Buffer.from(buffer),{status:200,headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="dronegestor-relatorio-mapa-${month}.xlsx"`,`Cache-Control":"private, no-store"}});
 }catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Falha ao gerar XLSX."},{status:500})}
}
